### ISSUE TITLE
How to use CURLOPT_CAINFO

### ISSUE THREAD

**Issue by ricardofarina96** [mailgun/mailgun-php#101]
For a application I'm developing i use the mailgun-php library for sending mails, but i keep getting cUrl error 60. After a quick search i discovered that i have to provide a certificate file. Which is set using the cUrl option CURLOPT_CAINFO. I found that these settings are set in RestClient.php and after testing with CURLOPT_SSL_VERIFYPEER => false it worked.

Configuring this option via Apache is not enough because i use a background queue-er to do the actual request to the mailgun API.

Is there a way to do this without changing the core files of the library?

**Comment by Nyholm** [comment]
If/When #94 is merged you can configure your own http client with `CURLOPT_SSL_VERIFYPEER => false` or `verify=>false` if you use Guzzle.

**Comment by Nyholm** [comment]
Fixed in 2.0
