### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by marcelstoer** [mailgun/mailgun-php#105]
I guess this is an issue for your "core" project which doesn't seem to be on GitHub. The jQuery sample shows the same false positive...

If the server is rejecting a user because it's invalid (SMTP 550) you shouldn't be reporting it as valid. I'm testing with `info@sbb.ch`.

```
220 sbbmail03.sbb.ch ESMTP Ready
EHLO ******
250-sbbmail03.sbb.ch Hello ******
250-STARTTLS
250 SIZE
MAIL FROM:<>
250 sender ok <>
RCPT TO:<info@sbb.ch>
550 info@sbb.ch refused: user invalid
```

**Comment by Nyholm** [comment]
Thank you for this issue. I think you are correct. This is not a problem with the client, it it a problem with the API server. You should talk to the support.
