### ISSUE TITLE
Howto add attachment data?

### ISSUE THREAD

**Issue by onokje** [mailgun/mailgun-php#109]
I know how to add attachment files, but what about attachments that are not stored as local file? There is plenty examples for this, like PDF's generated on the fly, or files downloaded from some cloudstorage.

Correct me if i'm wrong, but the only way to add these files as attachments at the moment, is storing them in a temp file, then attach them, and finally remove the temp file.
Can we make this easier?

**Comment by Nyholm** [comment]
That's correct, You have to store them locally. I would prefer to leave that to the library consumer because of the single responsibility principle.

**Comment by emporium-nsalter** [comment]
That's not actually correct, you can use the data wrapper to base64 encode your data then it will be decoded before sending the files: https://secure.php.net/manual/en/wrappers.data.php
