### ISSUE TITLE
Serious problems

### ISSUE THREAD

**Issue by zhil** [mailgun/mailgun-php#110]
I am trying to migrate from Mand... - they become paid for all accounts. I hided title, because I do not promote them :)
But I got a lot of problems.

1) I cant use single SMTP login/pass for different domains. Thats very annoying, because we have few different domains in the same system and used to send emails using the same SMTP credentials. Also I used to simply put the same SMTP in ALL my projects. 
2) There are no "overview all domains activity page" on your site. When you have a lot of domains - its annoying.
3) API handler do not report errors, if something went wrong. $mailGun->sendMessage , but in some cases it just dont send email silently.
4) I tried to use bin.mailgun.net, but got error
got exception [curl] 51: SSL: no alternative certificate subject name matches target host name 'bin.mailgun.net' [url] https://bin.mailgun.net/A9311655/*****/messages

kind of too much simple problems for 3 years old libs. Looks like I will need to migrate back to old service.

Not sure, what plans do you have on your service - you should check company I mention (I am sure, you know it) - they have really nice tool.

**Comment by jessespears** [comment]
Hi!  Those are some big problems, and we can help you with all of them!  From your Mailgun Control Panel, in the Support menu, you can create a support ticket.  I'm confident you'll get speedy service!

Since these issues aren't specific to `mailgun-php`, I'm closing this issue.

**Comment by zhil** [comment]
@jessespears well, actually 3rd problem is directly related to mailgun-php. not sure about 4th
