### ISSUE TITLE
The parameters passed to the API were invalid. Check your inputs

### ISSUE THREAD

**Issue by zeon** [mailgun/mailgun-php#119]
I Every time when I call BatchMessage->finalize() it gives me "The parameters passed to the API were invalid. Check your inputs", does anyone know why?

**Comment by korshoj** [comment]
If you still have this problem:
The "The parameters passed to the API were invalid. Check your inputs" error message is the default error message for any response that returns a 400 http status code. You might be better of updating the RestClient placed in https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Connection/RestClient.php to give a better response (or just the entire responseObj) that should assist in finding where the error is. Else it requires  a bit more code to try and debug on.

**Comment by Nyholm** [comment]
Thank you for the good answer @korshoj.
