### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by eyeonx** [mailgun/mailgun-php#124]
Hi,

I use the mailgun-php for a web app based on Themosis (A WordPress framework). I made some test on my dev environment and it works perfectly.
Somehow when I port the code to the production environment and fire the same AJAX request to my admin-ajax.php file (the file responsible for all AJAX operation) I get a 500 error in response without details or errors.
However the e-mail will be sent correctly, I receive it always in SPAM folder, but I receive it.

I made a research and I found that the 500 error could be triggered by some exception from Guzzle6 library. That's happening on Laravel too (see [here](https://laracasts.com/discuss/channels/general-discussion/laravel-51-guzzle-6-serverexception-in-middlewarephp-line-68-server-error-500?page=1)).
 I don't have enough experience with that kind of libraries, so I was wondering if there was a way to use mailgun-php without extern libraries or someone that could help me figure out where the problem resides.

**Comment by Sam-Butler** [comment]
I'm getting this error too. I tried to catch it as a Guzzle exception but it still didn't catch, the error output seems to supersede any later output. I may just have to write my own wrapper for the RESTful calls I need to perform in my app.

**Comment by DavidGarciaCat** [comment]
Hello @eyeonx and @Sam-Butler 

Question: Have you checked if [Mailgun Wordpress Plugin](https://github.com/mailgun/wordpress-plugin) is working as you need, without throwing a 500 (Internal Server Error) during the call? Maybe you can use the official plugin to solve this issue and save time, I don't know.

Regards,

**Comment by Sam-Butler** [comment]
I'm not using Wordpress, and I get the same result.

**Comment by Nyholm** [comment]
Since 2.x of this library we are no longer coupled to Guzzle. You could use any HTTP messaging client. Since this seams like an issue with Guzzle I'll close this.
