### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 7: Failed to connect to api.mailgun.net port 443: Connection timed out

### ISSUE THREAD

**Issue by saurabhkumarvaish14** [mailgun/mailgun-php#126]
PHP Fatal error:  Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 7: Failed to connect to api.mailgun.net port 443: Connection timed out

**Comment by Nyholm** [comment]
This error is not related to the client, is it? You get a Guzzle exception that you could not reach the endpoint. If your problem still exists, please try to ping or curl the endpoint. Otherwise contact support
