### ISSUE TITLE
Class 'Http\Adapter\Guzzle6\Client' not found

### ISSUE THREAD

**Issue by julien731** [mailgun/mailgun-php#127]
I'm desperately trying to make this work, but when trying to instantiate `HttpClient`, I get the error `Class 'Http\Adapter\Guzzle6\Client' not found`.

My Composer dependencies are loaded using `autoload.php`. My code looks like this:

```
$client = new \Http\Adapter\Guzzle6\Client();
$mg     = new \Mailgun\Mailgun( trim( KEY ), $client, 'http://bin.mailgun.net/xxx' );
```

Using version 2.0 of the SDK.

**Comment by julien731** [comment]
Aw. Just when I post I realize I read the docs too fast. Didn't require `guzzle6-adapter`. Sorry for the annoyance, but I think this could be clarified in the docs.

**Comment by samantagupta** [comment]
Just include autoload file with this line-

 require __DIR__.'/vendor/autoload.php';
