### ISSUE TITLE
Feature request: follow pagination

### ISSUE THREAD

**Issue by yeslad** [mailgun/mailgun-php#128]
Unless I missed something, it seems there is no built in support to follow pagination returned by the /events endpoint (possibly others as well?).

I ended up adding my own methods to the Mailgun and RestClient classes, but I would something from the source.

**Comment by borisguery** [comment]
Same problem here.
I end up tweaking the request URI based on the `next` value.

`$requestUri = str_replace('/v2/', '', parse_url($result['paging']['next'], PHP_URL_PATH));`

**Comment by Nyholm** [comment]
Check out the Event's API implementation. That is how we will do pagination. See #245
