### ISSUE TITLE
localhost development - SSL certificate problem

### ISSUE THREAD

**Issue by jurchiks** [mailgun/mailgun-php#130]
I'm running my dev site on PHP's built-in development server (`php -S localhost:8000`).

The basic code I'm using to send e-mail is as follows:

```
function email_pdf($pdf, $recipient)
{
	$client = new \Http\Adapter\Guzzle6\Client();
	$mgClient = new Mailgun\Mailgun('my-api-key', $client);
	
	$result = $mgClient->sendMessage(
		'my-domain',
		[
			'from'    => 'e-mail server <mailgun@my-domain>',
			'to'      => $recipient,
			'subject' => 'subject',
			'html'    => 'html content'
		],
		[
			'attachment' => [
				// this structure is documented as "backwards compatibility" in code,
				// even though your documentation offers no other way - WTF?
				'filePath' => $pdf,
				'remoteName' => 'bill.pdf',
			]
	);
	
	return $result;
}
```

I've downloaded the libraries today, so the versions are `mailgun/mailgun-php v2.0`, `php-http/guzzle6-adapter 1.1.1`.

This code throws a `Http\Client\Exception\RequestException` with the message `cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`.

What can be done to make this work?

**Comment by nisbeti** [comment]
See

http://flwebsites.biz/posts/how-fix-curl-error-60-ssl-issue

And

https://laracasts.com/discuss/channels/general-discussion/curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate/replies/52954

**Comment by jurchiks** [comment]
But that's curl, I'm using your own API, which is using curl UNDER THE HOOD, where I can't get to it.

**Comment by nisbeti** [comment]
I had this problem (not with mailgun though) and it was fixed by amending the php.ini file

```
[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
curl.cainfo = "C:\php\extras\cacert.pem"
```
 and putting the correct cacert.pem in the php/extras folder.

**Comment by jurchiks** [comment]
I do not have access to php.ini.

**Comment by jurchiks** [comment]
In any case, it seems that mailgun PHP API can't be used unless you're on a virtual host with a valid SSL certificate, which isn't applicable to many web projects that just want to occasionally send out an e-mail...

**Comment by nisbeti** [comment]
When creating the mailgun class you can set an optional parameter $ssl to
false and cUrl will use http instead of https.

**Comment by jurchiks** [comment]
Uhhh...
`public function __construct($apiKey = null, HttpClient $httpClient = null, $apiEndpoint = 'api.mailgun.net')`
What parameter are you talking about?

**Comment by jurchiks** [comment]
God damn it, they removed the option in 2.0!!! What the fuck guys?

**Comment by RiLedyard** [comment]
Would also like to see a resolution for this, as I have the same issue

**Comment by DanReinders** [comment]
+1
2.0 is currently unusable for me.  I'm having the same problem as jurchiks.

**Comment by mwangepatrick** [comment]
C'mon guys not everyone wants to have a valid SSL in all projects. This is just useless to me now :(

**Comment by fidransky** [comment]
What about this?

```php
$client = new \GuzzleHttp\Client([
    'verify' => false,
]);
$adapter = new \Http\Adapter\Guzzle6\Client($client);
$mailgun = new \Mailgun\Mailgun($mailgunApiKey, $adapter);
```

**Comment by DigitalSolo** [comment]
fidransky's solution worked for me.  Damn I was pulling what little hair I have left out. Part of my issue is that I have never used composer and I was stuck between knowing if I was doing something wrong or if it was screwed up documentation.  I would say that the published documentation needs to be reviewed.

**Comment by jurchiks** [comment]
Well, that's still only a workaround...
As I wrote before, there is a method in code `$mgClient->setSslEnabled(false);`, but this actually breaks the requests.

**Comment by DigitalSolo** [comment]
I searched the code base for setSslEnabled and didn't find that method.  I think they depreciated the ability to perform non secure requests.

**Comment by jurchiks** [comment]
https://github.com/mailgun/mailgun-php/blame/master/README.md#L166
https://github.com/mailgun/mailgun-php/blob/v2.0/src/Mailgun/Mailgun.php#L156
I think you don't have v2.0.

**Comment by DigitalSolo** [comment]
Composer.lock:
"name": "mailgun/mailgun-php",
            "version": "v2.0",
            "source": {
                "type": "git",
                "url": "https://github.com/mailgun/mailgun-php.git",
                "reference": "976a76a3b5b46eb8d0dedbd48a5c98d054b6054f"
            },

**Comment by jurchiks** [comment]
And yet you say you couldn't find "public function setSslEnabled($sslEnabled)" in the code...

**Comment by Nyholm** [comment]
Since 2.0 Mailgun is not coupled to Guzzle, Curl or anything else. That means you are responsible for setting up the http client. 

@fidransky your solution is the recommended way to go.

**Comment by Bogardo** [comment]
The main issue here is that the Mailgun API is not accessible on HTTP, only on HTTPS though the [source](https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Connection/RestClient.php#L316) says otherwise. 

```php
    /**
     * @param $uri
     *
     * @return string
     */
    private function getApiUrl($uri)
    {
        return $this->generateEndpoint($this->apiHost, $this->apiVersion, $this->sslEnabled).$uri;
    }

    /**
     * @param string $apiEndpoint
     * @param string $apiVersion
     * @param bool   $ssl
     *
     * @return string
     */
    private function generateEndpoint($apiEndpoint, $apiVersion, $ssl)
    {
        return ($ssl ? 'https://' : 'http://').$apiEndpoint.'/'.$apiVersion.'/';
    }

```

When accessing the API over HTTP all requests return a 404 Not Found error.
This causes the `The endpoint you've tried to access does not exist. Check your URL.` errors.

I've contacted Mailgun Support about this in June multiple times though I haven't heard back from them yet.

**Comment by Nyholm** [comment]
> The main issue here is that the Mailgun API is not accessible on HTTP, only on HTTPS

This is not an "issue" =). HTTPS is secure and it always better than HTTP. 

> .. the source says otherwise.

Yes, because you may use this client to connect to other APIs, not only Mailgun. Say you have a own MailgunProxy server. Or you want to debug request with httpbin or maybe you want to disable all request.

So, bottom line, Do always use HTTPS when talking to api.mailgun.net and if you having trouble verifying ssl certs (for whatever reson), configure your http client. 

```php
$client = new \GuzzleHttp\Client([
    'verify' => false,
]);
$adapter = new \Http\Adapter\Guzzle6\Client($client);
$mailgun = new \Mailgun\Mailgun($mailgunApiKey, $adapter);
```

**Comment by Bogardo** [comment]
@Nyholm Thanks, that makes sense.

**Comment by mits-techreceptives** [comment]
@Nyholm  I am using https://packagist.org/packages/e96/yii2-mailgun-mailer this for my web app.
setup through composer , and it installed mailgun-php 1.8.
I am still on localhost , and facing same error as above : GuzzleHttp\Exception\RequestException
cURL error 60: SSL certificate problem: unable to get local issuer certificate
I created account on mailgun and set domain parameter and key parameter in my application's config file.

any solution for this ?  or anything i missed out from mailgun configuration end ?

**Comment by Nyholm** [comment]
Im not too sure how you would do it in 1.8. That version does not give you so much control of the HTTP client.

**Comment by mits-techreceptives** [comment]
actually.. i have not installed and configure it but it was installed by composer's dependency .
i found this yii2 extension from google to use mailgun library in yii2 based app

**Comment by mrfuad2007** [comment]
@Nyholm  
it throws fatal error
 Fatal error: Uncaught Error: Class 'GuzzleHttp\Client' not found in G:\wamp\www\mailgun1\api.php on line 14

**Comment by Nyholm** [comment]
@mrfuad2007 Please open a new issue so we do not ping the other 10 participants from 2016.
