### ISSUE TITLE
CampaignID is missed in Logs (but I've sent it via API)

### ISSUE THREAD

**Issue by lezhnev74** [mailgun/mailgun-php#132]
I use code to send a message:

```
$client      = new Client();
$mailgun     = new Mailgun(config('services.mailgun.secret'), $client);
$domain      = config('services.mailgun.domain');
$messageBldr = $mailgun->MessageBuilder();
...
$messageBldr->addCampaignId($this->campaign_code);
$messageBldr->addTag($this->campaign_code . "::" . $campaign_sequence_code);
```

I attach tag and campaign ID. But Logs in Dashboard show only tag:

```
{
  "tags": [
    "code_campaign_01::sequence_code_01"
  ],
...
"campaigns": [],
...
```

Why do I do wrong?

**Comment by Nyholm** [comment]
Have you created a campaign named `$this->campaign_code` before you send the email?

**Comment by shakaran** [comment]
@lezhnev74 could you update the feedback for this issue? So devs knows about if it is still a problem or they could close it. If not probably will be closed by inactivity at some point

**Comment by Nyholm** [comment]
Closing due inactivity.
