### ISSUE TITLE
Library download link on README not working

### ISSUE THREAD

**Issue by HazCod** [mailgun/mailgun-php#136]
`Rather just download the files? Library Download.`

**Comment by YupItsZac** [comment]
👍 Nice catch, @HazCod 

It looks like they just removed (or moved) the linked file and just never updated the README. You can, of course, always download the latest copy of the library from Github here: https://github.com/mailgun/mailgun-php/archive/master.zip 

@jessespears, know where the original file went? I feel like the best way to handle this would be t just link the Github zip download from Master. If you agree, I'll update the README and open a PR. If you diagree, why?

**Comment by Nyholm** [comment]
I think we could remove that link/paragraph. You have to use composer to fetch dependencies anyways. 

Would you mind sending a PR?

**Comment by YupItsZac** [comment]
Thanks for the PR @DavidGarciaCat, I didn't see these notifications until now. 👍

**Comment by DavidGarciaCat** [comment]
@YupItsZac no worries - I still need to apply an update, but I'll do it ASAP

**Comment by Nyholm** [comment]
The link is removed thanks to @DavidGarciaCat. I'm closing this.
