### ISSUE TITLE
How to add custom data in html email templates ?

### ISSUE THREAD

**Issue by iit2011081** [mailgun/mailgun-php#137]
I am using php sdk to send html mails. I want to add some fields in my html template and then from php set the values of these custom fields. But I don't know how to access custom parameters in html. Lets say "projectName" is my custom parameter then I tried to add proejctName in html using {projectName}, {{projectName}} and {{$projectName}} but none of them are working. I am setting their value by calling the function addCustomParameter(). e.g.
$messageBldr->addCustomParameter("projectName", "My project Name"); 
But in my email I am getting only html not the value of projectName. If I have more than one custom parameter, do I need to call addCustomParameter () as many time?

**Comment by DavidGarciaCat** [comment]
@iit2011081 hey there, are you using "pure php" or are you using a template engine like Twig or Smarty?

**Comment by iit2011081** [comment]
@DavidGarciaCat I was using mailgun php sdk and tried to pass some variable in html template by using below code.
$messageBldr->addToRecipient("john.doe@example.com", array("first" => "John", "last" => "Doe", "projectName"=> "Sopan"));
<html>
    <p>
        Hello %recipient.first%, <br/> <br/>
        Your project is: %recipient.projectName%. 
    </p>
</html> 
But it was not working so I use [string template engine](https://github.com/nicmart/StringTemplate) .
$data = ['projectName'=> "sopan", 'first' => 'John'];
$engine = new Engine();
$html = $engine->render($html, $data);
$messageBldr->setHtmlBody($html);
<html>
    <p>
        Hello %recipient.first%, <br/> <br/>
        Your project is: {projectName}. 
    </p>
</html> 
In this way I make it to work properly.

**Comment by DavidGarciaCat** [comment]
@iit2011081 👍 

I use Twig to manage templates and arguments, and I get the rendered content before send the email, so in the end is the same process.

I presume a Mailgun repository member can close this ticket.

Cheers,
