### ISSUE TITLE
2.1.0 No stream factories found. error

### ISSUE THREAD

**Issue by it-can** [mailgun/mailgun-php#141]
Hi,

after updating to version 2.1.0 I get this error:

```No stream factories found. To use Guzzle or Diactoros factories install php-http/message and the chosen message implementation.```

in 2.0 it works correctly... I use this way to connect:

```
$client = new \Http\Adapter\Guzzle6\Client();
$mailgun = new \Mailgun\Mailgun('api_key', $client);
```

**Comment by Nyholm** [comment]
The error message you got: 
> No stream factories found. To use Guzzle or Diactoros factories install php-http/message and the chosen message implementation.

Tells you what to do. Try installing `php-http/message` and it will work for you.

**Comment by it-can** [comment]
okay, maybe add this to the readme file? is a pretty breaking change in my opinion...

**Comment by Nyholm** [comment]
You are correct, We did not use the php-http/message before. This PR fixes that issue: https://github.com/mailgun/mailgun-php/pull/142
