### ISSUE TITLE
Avoid lazy initialization

### ISSUE THREAD

**Issue by sagikazarmark** [mailgun/mailgun-php#162]
In the RestClient both the HTTP Client and the message factory are lazily initialized: https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Connection/RestClient.php#L290

This should generally be avoided and dependencies should be resolved preferably in the constructor.

Also, the message factory cannot be injected into client in any ways, which means that custom message factory implementations can't be easily used. (They could be by configuring Puli).

**Comment by Nyholm** [comment]
Thank you. This is fixed in dev-master.
