### ISSUE TITLE
slash in remote name considered as path

### ISSUE THREAD

**Issue by murtraja** [mailgun/mailgun-php#164]
while trying to attach a file having remote name "my file on 30/8/2016", i discovered that only 2016 gets reflected in the actual name
(@Nyholm , i know how to open issues but not how to have a failing test case as PR)

**Comment by DavidGarciaCat** [comment]
hi @murtraja

Could you paste an example about how you're calling the API endpoint, attaching a file, and the provided response please?

Thanks,

**Comment by Nyholm** [comment]
Closing due inactivity.
