### ISSUE TITLE
.MSG attachments (Outlook mail export) are corrupted

### ISSUE THREAD

**Issue by WietseWind** [mailgun/mailgun-php#165]
Fix suggested @ [multipart-stream-builder module](https://github.com/php-http/multipart-stream-builder/pull/11)

.MSG files contain multipart data since they are raw dumps of an e-mail. Mail API's like mailgun will send corrupt .msg attachments when the attachment is using the default mimetype.

**Comment by Nyholm** [comment]
Thank you. 
I understand that you want to attach a *.msg file but you will not get any Mime Type from the MultipartStreamBuilder. Is that the issue?

**Comment by WietseWind** [comment]
It is, indeed, resulting in this:
P.S.
Before fix:
![](https://cdn.pbrd.co/images/fdenZfkyQ.png)
After fix:
![](https://cdn.pbrd.co/images/fdeSnqJmP.png)

**Comment by Nyholm** [comment]
This will be fixed when php-http/multipart-stream-builder is tagged 0.1.2. 

Im closing this issue for now. Thank you @WietseWind!

**Comment by Nyholm** [comment]
I've just taggad 0.1.2.
