### ISSUE TITLE
How to use a query

### ISSUE THREAD

**Issue by qwe356558603** [mailgun/mailgun-php#169]
$result = $mgClient->get("lists/$listAddress/members/pages", array(
    'subscribed' => 'yes',
    'limit'      =>  5
));

Due to too many malilist members, I want to query through the email address, can do it???
![image](https://cloud.githubusercontent.com/assets/18321666/18422317/b697392e-78cb-11e6-99a5-2c2be58166d3.png)

**Comment by qwe356558603** [comment]
![image](https://cloud.githubusercontent.com/assets/18321666/18422307/8a0e1c9c-78cb-11e6-99ad-2ec8b1ae7f3b.png)

**Comment by DavidGarciaCat** [comment]
Hey @qwe356558603 

I think that I understand what you want to do. However my first concern is the endpoint you're using, due I cannot see it on official MangoPay docs: https://documentation.mailgun.com/user_manual.html#mailing-lists

Where you ver that endpoint?

Regards,

**Comment by DavidGarciaCat** [comment]
Hey @qwe356558603 

I think that I understand what you want to do. However my first concern is the endpoint you're using, due I cannot see it on official Mailgun docs: https://documentation.mailgun.com/user_manual.html#mailing-lists

Where you get that endpoint?

Regards,
