### ISSUE TITLE
Recipient Variables on CC and BCC Recipients

### ISSUE THREAD

**Issue by travelton** [mailgun/mailgun-php#17]
Currently, the SDK does not support adding recipient variables for CC and BCC recipient types. The Mailgun API does support template variables for CC and BCC recipients.

**Comment by LTroya** [comment]
Is it still not supported ?

**Comment by lahiru1991** [comment]
Is it still not supported ?

**Comment by Nyholm** [comment]
Have a try with dev-master and open a new issue if you still can't make it work.
