### ISSUE TITLE
Events result possible error

### ISSUE THREAD

**Issue by andrejmk** [mailgun/mailgun-php#170]
When getting the events (event type: failed was tested), one of the properties returned is delivery-status, that it self contains 8 fields. 

When I get the results with the SDK, that field is null, although on the logs on the site there is data. I tried with cURL and the delivery-status IS there with all the fields. But, when I do json_decode on the result, the delivery-status becomes null. So I guess that json_decode somehow breaks it, but I'm not sure how.

Thanks,
Andrej

**Comment by DavidGarciaCat** [comment]
Hi @andrejmk 

Quick question please: what is the content that you get when you call the API endpoint via cURL binnary (through command line), and what is the content you get (don't process it) via yout HTTP client?

Given my personal experience, is a good idea compare the results printing them (given this case is `php` you can use an `echo` statement, followed by `exit();` to print the content). If you can get the same content on both cases, then we can say the API returns a bad response. If the content is different, we should consider a possible issue on `mailgun-php`.

Another question please: what HTTP client are you using to send your requests to Maingun API?

Regards,

**Comment by andrejmk** [comment]
Hi @DavidGarciaCat 

the results I get are the same in both cases, except for the delivery-status field. cURL returns the json string and the results are there. My point was that doing json_decode on the json string breaks the delivery-status field because of the dash in the name of the variable. The PHP SDK is doing the same thing, json_decode on the result and the delivery-status is NULL because of that. I continued to use cURL and not the SDK in this case and I fixed the issue by doing json_decode($result, true); which decodes the json into array, not a stdClass. In that case, delivery-status is not affected.

Thanks,
Andrej

**Comment by DavidGarciaCat** [comment]
Hi @andrejmk

If you get the expected response converting the response to an array instead of an object, at least you have not a very big blocker. However I understand your concern, IMHO OOP is much better than an array when we need to work with the provided data.

Let's see if we can provide a PR to fix this - in case the error is caused by the SDK - but if the problem comes from the API (I doubt it, given you say the cURL call returns the expected value) an API review will be required.

Regards,

**Comment by andrejmk** [comment]
@DavidGarciaCat I agree that OOP is better. The API is fine, the issue is json_decode and PHP, which does not support variable names with dashes in it. I don't have an idea for a fix at the moment, except returning an array.

Thanks,
Andrej

**Comment by mahaguru24** [comment]
@Nyholm I am having this issue as I get a different response on curl and different on the PHP mailgun-sdk? ANy proposed solution for it?

**Comment by Nyholm** [comment]
Could you show me the API call you are doing with cUrl and Mailgun. Also show the results.
