### ISSUE TITLE
Attaching Data to Batch Messages

### ISSUE THREAD

**Issue by pbowyer** [mailgun/mailgun-php#171]
I am trying to attach data to messages sent with the BatchMessage class. The docs say:
![image](https://cloud.githubusercontent.com/assets/89852/18668748/2d4fb618-7f2f-11e6-87e0-1782b1057d8c.png)

I've tried assigning as custom parameters:
```php
$batchSender->addToRecipient(
	$row2['email'],
	[
		'first' => $row2['first_name'],
		'last' => $row2['last_name'],
		'v:person-id' => $row2['person_id'],
		'v:account-id' => $row['account_id'],
	]
);
```
but they didn't show in the Mailgun Logs screen.

I tried JSON encoding before I sent, but it didn't show either:
```
        ...
		'v:person-id' => json_encode($row2['person_id']),
        ...
```

I am guessing I need to map the custom parameters to become custom data on the message itself, so that the values are associated, but I do not see how to. How should it be done?

#### Update
I have also tried:
```php
$batchSender->addCustomData('user', [
                    'accountId' => '%recipient.accountId%',
                    'mailingId' => '%recipient.mailingId%',
                    'personId' => "%recipient.personId%",
                ]);

// Fetch recipients, and then loop over
foreach (...) {
	$batchSender->addToRecipient(
		$row2['email'],
		[
			'first' => $row2['first_name'],
			'last' => $row2['last_name'],
			'mailing-id' => $row['id'],
			'person-id' => $row2['person_id'],
			'account-id' => $row['account_id'],
		]
	);
}
```

No placeholder substitution happens, according to the [logs in the Mailgun UI](https://mailgun.com/app/logs/docourses.com):
```
  "user-variables": {
    "user": "{\"accountId\":\"%recipient.accountId%\",\"mailingId\":\"%recipient.mailingId%\",\"personId\":\"%recipient.personId%\"}"
  },
```

**Comment by pbowyer** [comment]
I have also tried:
```php
$batchSender->addCustomData('mailing-id', '%recipient.mailing-id%');
$batchSender->addCustomData('person-id', '%recipient.person-id%');
$batchSender->addCustomData('account-id', '%recipient.account-id%');
foreach (...) {
	$batchSender->addToRecipient(
		$row2['email'],
		[
			'first' => $row2['first_name'],
			'last' => $row2['last_name'],
			'mailing-id' => $row['id'],
			'person-id' => $row2['person_id'],
			'account-id' => $row['account_id'],
		]
	);
}
```

No placeholder substitution happens:
![image](https://cloud.githubusercontent.com/assets/89852/18669518/58bc81ce-7f33-11e6-8099-03a289c8b713.png)

**Comment by pbowyer** [comment]
Update: the second way I tried appears correct; it's populating the data on events (e.g. email opened). Just not when the emails are sent (the 'Received for sending' and 'Sent' updates)

**Comment by Nyholm** [comment]
Thank you. Could you update the Readme with this information? Maybe create a FAQ section?

**Comment by iit2011081** [comment]
@pbowyer Hi try to do the same way but its not working, I added like this 
```
$batchSender->addCustomData('user', [
                    'fullName' => '%recipient.fullName%'
                ]);

// Fetch recipients, and then loop over
foreach (...) {
    $batchSender->addToRecipient(
        $row2['email'],
        [
            'first' => $row2['first_name'],
            'last' => $row2['last_name'],
            'fullName' => $row['fullName']
        ]
    );
}
```
When I used %fullName% in subject it is displaying as it is.

**Comment by pawprintdigital** [comment]
Hi all,

Is there any update on this? I'm too faced with this issue and can't appear to get this working.
I've also contacted Mailgun directly but haven't had a huge amount of support from them which is a shame.

I'm using the method as above but the 'user-variables' are still coming through blank in both the Mailgun logs and my webhooks.

Any assistance would be greatly appreciated!

Using the BatchMessage method I assumed the below should work?

```
$batchMsg->addCustomData('user', [
    'campaignId' => '%recipient.campaignId%',
    'recipientId' => '%recipient.recipientId%',
    'listId' => "%recipient.listId%",
]);

foreach ($this->campaign->contacts() as $contact) :
    $batchMsg->addToRecipient($contact->email, array('recipientId' => $contact->id, 'campaignId' => $this->campaign->id, 'listId' => $contact->list_id));
endforeach;
```

Thanks in advance!

Lee

**Comment by iit2011081** [comment]
@pawprintdigital 
No need to use addCustomData function , just pass additional data  while adding recipient. Use following code , it will work
```
$batchMsg->setSubject("%recipient.fullName% , %recipient.first%");
$receipients = [
	[
		"first_name" => "A",
		"last_name" => "B",
		"fullName" => "AB"
	],
	[
		"first_name" => "C",
		"last_name" => "D",
		"fullName" => "CD"
	],
]
foreach ($receipients as $row) {
    $batchSender->addToRecipient(
        $row['email'],
        [
            'first' => $row['first_name'],
            'last' => $row['last_name'],
            'fullName' => $row['fullName']
        ]
    );
}
```

**Comment by pawprintdigital** [comment]
Hi @iit2011081,

I tried the above but still appear to be having issues I'm afraid.

        $batchMsg = $mg->BatchMessage($domain);
        $batchMsg->setReplyToAddress(''.$this->campaign->data['sender_name'].' <'.$this->campaign->data['sender_email'].'>');
        $batchMsg->setFromAddress(''.$this->campaign->data['sender_name'].' <'.$this->campaign->data['sender_email'].'>');
        $batchMsg->setSubject($this->campaign->data['subject']);
        $batchMsg->setHtmlBody(file_get_contents($this->campaign->data['payload']));
        $batchMsg->setTextBody('Your email client does not appear to support HTML. Please visit '.$this->campaign->data['payload'].' to view this email.');
        $batchMsg->addCustomHeader('ppd_campaign_id', $this->campaign->id);
        $batchMsg->addCustomHeader('Sender', $this->campaign->data['sender_email']);

        foreach ($this->recipients as $contact) :
            $batchMsg->addToRecipient(
              $contact,
              [
                'recipient_id' => '1',
                'campaign_id' => $this->campaign->id,
                'list_id' => '1',
              ]
            );
        endforeach;

        // Finish our send
        $batchMsg->finalize();

This is the full block of code; I'm pulling my hair out trying to work out what's going on here so any insight would be most appreciated!

Thanks,
Lee

**Comment by popperz0r** [comment]
@pawprintdigital take a look at here: https://stackoverflow.com/a/37348816

I was struggling with the same.
