### ISSUE TITLE
endpoint you've tried to access does not exist. Check your URL

### ISSUE THREAD

**Issue by mits-techreceptives** [mailgun/mailgun-php#175]
i am using mailgun yii2 extension which have mailgun-php .
when i am trying to sending mail , it throws below error:
Mailgun\Connection\Exceptions\MissingEndpoint
The endpoint you've tried to access does not exist. Check your URL.

Mailgun V3 i am using. and in mailgun php api , it trying to connect with api.mailgun.net endpoint.
so how to fix it ?

**Comment by DavidGarciaCat** [comment]
Reading your issue description and the README.md file I assume you're using this Framework Integration: [katanyoo/yii2-mailgun-mailer](https://github.com/katanyoo/yii2-mailgun-mailer) for Yii2

Given this case, you should open an issue on that repository, given `katanyoo` is not `mailgun` so Mailgun is not the owner of that framework integration.

Regards,

**Comment by mits-techreceptives** [comment]
I am using this one : https://github.com/boundstate/yii2-mailgun
but internally its making calling through mailgun-php package. so i thought to ask solution over here.

**Comment by DavidGarciaCat** [comment]
This is the Mailgun way to send an email:
```
# First, instantiate the SDK with your API credentials and define your domain. 
$mg = new Mailgun("key-example");
$domain = "example.com";

# Now, compose and send your message.
$mg->sendMessage($domain, array('from'    => 'bob@example.com', 
                                'to'      => 'sally@example.com', 
                                'subject' => 'The PHP SDK is awesome!', 
                                'text'    => 'It is so simple to send a message.'));
```
And this is the one that you're using given the repository that you say you're using:
```
Yii::$app->mailer->compose('contact/html', ['contactForm' => $form])
    ->setFrom('from@domain.com')
    ->setTo($form->email)
    ->setSubject($form->subject)
    ->send();
```

As you can see the Yii code is not the same than Mailgun code.

Given this case, you have 2 options:
1. Open an issue on https://github.com/boundstate/yii2-mailgun and wait to get an update
2. Use Mailgun-PHP repository and send emails using the original SDK instead of an external resource

Regards,

**Comment by Nyholm** [comment]
This issue is related to #130 and #174. 

@mits-techreceptives Please do not comment on multiple issues/thread with same problem. 

Thank you @DavidGarciaCat for your answers.

**Comment by mits-techreceptives** [comment]
@Nyholm  yeah.. sorry man !! as in hurry .. forget this one
