### ISSUE TITLE
Fatal error: Uncaught exception 'Mailgun\Connection\Exceptions\MissingEndpoint' with message 'The endpoint you've tried to access does not exist. Check your URL

### ISSUE THREAD

**Issue by mithunjj** [mailgun/mailgun-php#178]
I'm not using any frameworks plain PHP only, just trying to integrate the official package.

I'm getting the following error:

**Fatal error: Uncaught exception 'Mailgun\Connection\Exceptions\MissingEndpoint' with message 'The endpoint you've tried to access does not exist. Check your URL**

I had tried:

1. Updating the package via Composer
2. Checked the API credentials

But in vain.

I'm running it in my localhost on a Windows 7 x64 machine using [XAMPP](https://www.apachefriends.org/)

Here is my code:

```

require 'vendor/autoload.php';

use Mailgun\Mailgun;

$mg = new Mailgun("key-mykey");
$mg->setApiVersion('v3');
$mg->setSslEnabled(false);
$domain = "mydomain.com";

# Now, compose and send your message.
$mg->sendMessage($domain, array('from' => 'bob@test.com',
    'to' => 'test@test.com',
    'subject' => 'The PHP SDK is awesome!',
    'text' => 'It is so simple to send a message.'));

```

Please help. Thanks in advance

**Comment by Nyholm** [comment]
Have you tried with ssl enabled?

**Comment by mithunjj** [comment]
In my local machine, there is no SSL so if I enable it, I'm getting the following error:

**Fatal error: Uncaught exception 'Http\Client\Exception\RequestException' with message 'SSL certificate problem: unable to get local issuer certificate'**

That's the reason why I've disabled it in the 1st place.

**Comment by Nyholm** [comment]
I do not think there is an endpoint for "http://api.mailgun.net". It should be "https://api.mailgun.net". That is why you get "The endpoint you've tried to access does not exist. Check your URL".

You could configure your API client to not verify the certificate.

**Comment by mithunjj** [comment]
If I don't verify the certificate, then I will get the first error.

The problem is happening on my Windows developer machine. Tried it on a Linux production server and all is well.

Any help is appreciated to make it work on the developer machine.

**Comment by Nyholm** [comment]
It sounds like the easiest solution for you would be to install OpenSSL php extension on your local environment.

**Comment by mithunjj** [comment]
OpenSSL php extension is already installed.

**Comment by DavidGarciaCat** [comment]
And enabled too? I assume the answer is "yes" but I must ask because I saw in the past some people that were getting an OpenSSL error because the local PHP was not loading the extension.

Are you writing automated tests? If yes, what is the response when you run this process?

Cheers,

**Comment by mithunjj** [comment]
I had enabled OpenSSL in XAMPP: http://www.qoncious.com/questions/enable-ssl-xampp-and-wampserver

No, I'm not writing automated tests.

**Comment by Nyholm** [comment]
To disable verification of the SSL you may configure your HTTP client. Here is an example with Guzzle:

```php
$client = new \GuzzleHttp\Client([
    'verify' => false,
]);
$adapter = new \Http\Adapter\Guzzle6\Client($client);
$mailgun = new \Mailgun\Mailgun($mailgunApiKey, $adapter);
$mailgun->setSslEnabled(true);
```

**Comment by natterstefan** [comment]
@Nyholm is [this](https://github.com/mailgun/mailgun-php/issues/178#issuecomment-250679233) necessary to solve this issue? I am running into this problem on my live system.

**Comment by Nyholm** [comment]
My answer was to configure the HTTP client not to verify the SSL protocol. 
What issue are you referring to?

Do you get a `Mailgun\Connection\Exceptions\MissingEndpoint`? If so, what endpoint are you using?

**Comment by natterstefan** [comment]
@Nyholm I was referring to the `'The endpoint you've tried to access does not exist. Check your URL` error response. But in the meanwhile I was able to solve it.

My `$domain = "mydomain.com";` was not the one I had set up on mailgun. That caused the error. Maybe the response should be more clearer on what is wrong.

**Comment by Nyholm** [comment]
Yeah, you may be correct. It may include the URL. Can you submit a PR?

**Comment by natterstefan** [comment]
@Nyholm I submitted a [PR](https://github.com/mailgun/mailgun-php/pull/373). Did not find a Contribution Readme. So hopefully I did not forget something.

**Comment by Nyholm** [comment]
Thank you. It all looks good.

**Comment by xfechx** [comment]
Hi, I am having the same issue..
Mailgun\Connection\Exceptions\MissingEndpoint: The endpoint you've tried to access does not exist. Check your URL

It only works while updating SMTP password via API, any other mailgun API requests work fine... Don't know what I am missing?

Doing this:
$mgClient = new Mailgun($api_key);
$result = $mgClient->put(
"/domains/$domain/credentials/$login",
array('password' => $password)
);

**Comment by DavidGarciaCat** [comment]
Hey @xfechx 

You've posted your message twice [here](https://github.com/mailgun/mailgun-php/pull/373#issuecomment-513399960), please keep just one thread.

Thanks,

**Comment by xfechx** [comment]
Hey,

Using the new SDK doesn't work exactly as using the API mentioned in the Mailgun Docs. For instance, creating a route, doesn't return back the same data as before. I can't find any documentation of what these functions return. 

I need to obtain the route_id, and smtp_id, when creating both a route and a smtp. 

Thanks

**Comment by xfechx** [comment]
Hey,

Using the new SDK doesn't work exactly as using the API mentioned in the Mailgun Docs. For instance, creating a route, doesn't return back the same data as before. I can't find any documentation of what these functions return.

I need to obtain the route_id, and smtp_id, when creating both a route and a smtp.

Before, I was obtaining those like this:

    ```
$result_json = json_encode($result);
    $result_data = json_decode($result_json, true);
    $route_id = $result_data["http_response_body"]["route"]["id"];
    return $route_id;
```


Thanks

**Comment by DavidGarciaCat** [comment]
Hi @xfechx 

The problem that you're porting here regarding the potential missing IDs is not related to an Exception. Locking this thread now to avoid spamming other people.

As requested [here](https://github.com/mailgun/mailgun-php/pull/373#issuecomment-513562128), can you please open a new issue with the error so that we can track that case properly and apply an update if needed? On the other hand, you're free to send a PR if you're feeling comfortable with that.

Cheers,
