### ISSUE TITLE
How do you know the 'batch' results?

### ISSUE THREAD

**Issue by pouu69** [mailgun/mailgun-php#181]
After the mass mailing would like to know the number of successes.

**Comment by Nyholm** [comment]
That is a great idea. But Im not sure the API tells you that, does it?

**Comment by pouu69** [comment]
It includes API, which certainly offers not know.

can U make it ?

**Comment by Nyholm** [comment]
> It includes API, which certainly offers not know.

Im not too sure what you mean here. Can you please elaborate?

**Comment by pouu69** [comment]
mailgun api is not provided.
so, how can i make for results?

**Comment by Nyholm** [comment]
What do you mean that it is not provided? 
Have a look at the API reference: https://documentation.mailgun.com/api_reference.html

When you sending mass emails, what does the API server respond?
If it responds with the number of successes, we (the client) should support it. 

What does the documentation say?
