### ISSUE TITLE
Mailgun\Connection\RestClient is still using API v2 instead of v3

### ISSUE THREAD

**Issue by mstralka** [mailgun/mailgun-php#182]
It appears the PHP library is still using the older version of the API.  Is there a branch that uses v3?

The [Mailgun API documentation](https://documentation.mailgun.com/api-intro.html#base-url) shows the Base URL as `v3` of the API:
````
https://api.mailgun.net/v3
````

However, the `RestClient` class is using v2, which means many of the available API calls, like [unsubscribes](https://documentation.mailgun.com/api-suppressions.html#unsubscribes), do not work.

If I manually edit `RestClient`, changing:
````
    /**
     * The version of the API to use.
     *
     * @var string
     */
    protected $apiVersion = 'v2';
````
to:
````
    /**
     * The version of the API to use.
     *
     * @var string
     */
    protected $apiVersion = 'v3';
````

My call to retrieve the unsubscribes will work:
````
GET /<domain>/unsubscribes`
````

I'm using Composer to pull `mailgun-php` in so this isn't a practical workaround.

Thanks

**Comment by mstralka** [comment]
Never mind, I see that the `Mailgun` class has a `setApiVersion()` method I can use.

**Comment by Nyholm** [comment]
Thank you. We should consider updating to version 3. Ping @pirogoeth
