### ISSUE TITLE
Create Events API

### ISSUE THREAD

**Issue by pirogoeth** [mailgun/mailgun-php#188]
Includes request dispatcher and any request//response models necessary.

**Comment by Nyholm** [comment]
I have an idea how to make pagination awesome :) 
I want to try if it works.

**Comment by pirogoeth** [comment]
Absolutely! I'm excited to see what you've got!

**Comment by pbowyer** [comment]
Feedback from using: the pagination and API are excellent.

One task I wanted to do I cannot: that is to get the original JSON that created the Event, or serialize the Event. From reading the code this looks as if it'll be an issue with all the new classes.

One solution is to add a `toArray` trait; is there anything implemented I've overlooked?

**Comment by Nyholm** [comment]
If you do not want to use all these new classes you can pass a different serializer to the Client's constructor. Using the JsonSerializer will allow you to get the Json response back.

**Comment by pbowyer** [comment]
Ah but I do want to use the new classes, they are much easier to work with 😄 My use-case is that I want to store all the data for future re-processing, and there's no way to get to it. `json_encode($event)` doesn't work, nor does `json_encode(get_object_vars($event))` (rightly so).

Is that clearer? I've got:

```
$events = $mg->events()->get($this->getContainer()->getParameter('mailgun_domain'), [
    'begin' => $begin->format(\DateTime::RFC2822),
    'ascending' => true,
    'event' => 'NOT stored'
]);

while (count($events->getItems()) > 0) {
    foreach ($events->getItems() as $event) {
        // ... process each event
        // Save to log server
        // @TODO Save all data that's in $event (imagine passing to Monolog in the data parameter)
    }
} 
```

**Comment by Nyholm** [comment]
That is a fair use caste. Thank you. I've created a new ticket for that. See #267
