### ISSUE TITLE
Investigate in shared components for API responses

### ISSUE THREAD

**Issue by Nyholm** [mailgun/mailgun-php#193]
We should have a look at the [API reference](https://documentation.mailgun.com/api_reference.html). What shared format is there in the responses? Could we make something smart with class inheritance to reduce the code duplication?

**Comment by Nyholm** [comment]
After some research: Nothing. Nothing (or very little) can be shared. We should go with a clean approach to increase readability. Ie, We should not try to share anything between APIs or API requests.

**Comment by DavidGarciaCat** [comment]
I'm sorry to hear that

**Comment by Nyholm** [comment]
So am I. But that's how it is.. =)
