### ISSUE TITLE
if you send the same email domain, not convert %recipient.email%

### ISSUE THREAD

**Issue by pouu69** [mailgun/mailgun-php#197]
ex)
```
$emails = [
 'test@test.com' => ['email' => 'abc@test.com]
]

// email.blade.php (email form)
<h1>mailgun.com/%recipient.email%</h1> // mailgun.com/%recipient.email%
```
if you send the same email domain, not convert %recipient.email%

do you know why ?

**Comment by Nyholm** [comment]
I do not really understand the question or your code example. Could you please elaborate?

**Comment by DavidGarciaCat** [comment]
I think what @pouu69 says is that emails from/to the same domain are causing a conflict.
My doubt here is if @pouu69 is setting that value properly.

@pouu69 as @Nyholm said, can you elaborate please? Maybe a "real" example?

**Comment by Nyholm** [comment]
Closing due inactivity.
