### ISSUE TITLE
Is "deserialization" the correct name?

### ISSUE THREAD

**Issue by Nyholm** [mailgun/mailgun-php#201]
As Mark pointed out in https://github.com/mailgun/mailgun-php/issues/186#issuecomment-255882949 "deserialization" might not be the correct name. 

Serialization or marshalling is when you turn an object into a format that can be stored. ([source](https://en.m.wikipedia.org/wiki/Serialization)). The reverse process is deserialization or unmarshalling. 

An other concept is "normalization" that we might find more suitable to use here. 

Any thoughts?

**Comment by Nyholm** [comment]
I think "deserialization" is the correct name.

**Comment by pirogoeth** [comment]
Agreed. I had changed this in my alternative API pull request. I think I will get out a PR to fix this issue soon.
