### ISSUE TITLE
The serializer concept

### ISSUE THREAD

**Issue by Nyholm** [mailgun/mailgun-php#206]
From https://github.com/mailgun/mailgun-php/issues/186#issuecomment-255882949

> I really like this solution, it's actually very clever and flexible. However, my fear is that too much things are put into configuration and it might become hard to rely on the actual API. So my idea would be to somehow make this part of the API of the code: maybe have multiple resource implementations, each of them return the specific type of answer (eg. domain model or array). This could rely on the current code foundation, could even be generated. The point is that when using it in actual code it does not depend on the documentation what kind of answer we receive, because it's a little bit leaky. (I admit, it doesn't sound as good as I felt in my head 😄 )

**Comment by Nyholm** [comment]
I like this solution. I believe that the "correct" way of doing it would be to remove the deserialzer form the `AbstractApi`: 

```php
$psr7Response = $mailgun->domains()->index();
$indexResponse = $deserializer->deserialize($psr7Response, IndexResponse::class);
```

But the code above is not really DX. I suggest "no change" and keep what currently in master. 

Do we have any other input?

**Comment by pirogoeth** [comment]
I think what we've got in master works fine. It makes sense and keeps the request process concise.

**Comment by Nyholm** [comment]
Good good. Im closing this issue then.

**Comment by Nyholm** [comment]
I want to reopen this issue. In the [FriendsOfAPI boilerplate](https://github.com/FriendsOfApi/boilerplate) we renamed the deserializers to "hydrator". We should do the same thing here.
