### ISSUE TITLE
Could not find package php-http/guzzle6-adapter at any version matching your PHP version 5.3.3.0 

### ISSUE THREAD

**Issue by omaismbakop** [mailgun/mailgun-php#207]
HI, 
While running this command 
`php composer.phar require mailgun/mailgun-php php-http/curl-client guzzlehttp/psr7`
i am getting this error on server

> Could not find package php-http/guzzle6-adapter at any version matching your PHP version 5.3.3.0

**Comment by Nyholm** [comment]
It seams like you have `php-http/guzzle6-adapter` in your composer.json from before. Try removing that. 

(and also, update your PHP version. There are children going to school that were not born at the time of that PHP version was released 😄  )

**Comment by DavidGarciaCat** [comment]
@Nyholm
Crystal clear 👍

@omaismbakop
Please have a look to Mailgun PHP required version `php: ^5.5|^7.0` (PHP 5.3 is not supported)
https://packagist.org/packages/mailgun/mailgun-php

**Comment by omaismbakop** [comment]
I've updated to php 5.5  , but still have this error

**Comment by DavidGarciaCat** [comment]
@omaismbakop I can see that you have tried to install `dev-master`, but it is currently hosting a major update, and is not a good idea to use this version. Please consider to use a stable version.

Last stable release is 2.1.2 https://packagist.org/packages/mailgun/mailgun-php

**Comment by omaismbakop** [comment]
@DavidGarciaCat  i followed these instructions. But had issue with that, now i set this
`{
	"require":{
	"mailgun/mailgun-php": "dev-master"
	} 
}`
in composer.json and have above problem. For stable release, what i need to set in composer.json?

**Comment by DavidGarciaCat** [comment]
@omaismbakop instead of `dev-master` just type the version - this is an example:
```
{
    "require": {
        "mailgun/mailgun-php": "^2.1"
    }
}
```
Then update your composer package with `composer update mailgun/mailgun-php`

Another option is:
1. remove the current `mailgun` package from your `composer.json` file; then
2. run `composer require mailgun/mailgun-php` and composer will set the version for you

Please read `composer` docs if you need more details about how to set a specific version, and the use of tildes or carets (for example):
https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators

**Comment by DavidGarciaCat** [comment]
@omaismbakop please double check your PHP version running this command `php -v`

Given the picture that you posted on that link, you're still using PHP 5.3.3:

![image](https://cloud.githubusercontent.com/assets/7809429/19789612/0022285a-9ca9-11e6-95dd-eb07354845c6.png)

**Comment by omaismbakop** [comment]
Worked now, receiving email. Thanks All.

**Comment by Nyholm** [comment]
I'm glad it worked for you. 

Great support David!

**Comment by DavidGarciaCat** [comment]
Anytime!
