### ISSUE TITLE
Way to set attachment name?

### ISSUE THREAD

**Issue by taylorotwell** [mailgun/mailgun-php#21]
Currently you add an attachment by file path. Is there a way to set a custom name for the attachment that is distinct from the path?

**Comment by gorgano** [comment]
I wasn't able to find any specification in the documentation on how to do this.  In case anyone was looking to do this, it appears you can just pass an array of attachments with the appropriate name fields to get named attachments:

           $attachments[] = [
                'remoteName' => 'nameofthefile.ext', 
                'filePath' => '/path/to/the/file'
            ];

**Comment by DevNIX** [comment]
This feature should be documented

**Comment by Nyholm** [comment]
Thank you @DevNIX. I've created an issue for that. If you want, you are free to create a PR for this.

**Comment by goaiworld** [comment]
> I wasn't able to find any specification in the documentation on how to do this. In case anyone was looking to do this, it appears you can just pass an array of attachments with the appropriate name fields to get named attachments:
> 
> ```
>        $attachments[] = [
>             'remoteName' => 'nameofthefile.ext', 
>             'filePath' => '/path/to/the/file'
>         ];
> ```

It's filename, instead of remoteName in sdk version 3.x
