### ISSUE TITLE
MissingEndpoint Error

### ISSUE THREAD

**Issue by ThatBenderGuy** [mailgun/mailgun-php#210]
I am attempting to use this to send an email to a user when they register but I get this error

> Details
>
> Type: Mailgun\Connection\Exceptions\MissingEndpoint
> Message: The endpoint you've tried to access does not exist. Check your URL.
> File: E:\xampp\htdocs\biosys\vendor\mailgun\mailgun-php\src\Mailgun\Connection\RestClient.php
> Line: 230
> Trace
> 
> #0 E:\xampp\htdocs\biosys\vendor\mailgun\mailgun-php\src\Mailgun\Connection\RestClient.php(99): Mailgun\Connection\RestClient->responseHandler(Object(GuzzleHttp\Psr7\Response))
> #1 E:\xampp\htdocs\biosys\vendor\mailgun\mailgun-php\src\Mailgun\Connection\RestClient.php(151): Mailgun\Connection\RestClient->send('POST', 'sandbox3d482f75...', Array, Array)
> #2 E:\xampp\htdocs\biosys\vendor\mailgun\mailgun-php\src\Mailgun\Mailgun.php(118): Mailgun\Connection\RestClient->post('sandbox3d482f75...', Array, Array)
> #3 E:\xampp\htdocs\biosys\app\BiosystemStudios\Mail\Mailer.php(35): Mailgun\Mailgun->post('sandbox3d482f75...', Array)
> #4 E:\xampp\htdocs\biosys\app\routes\auth\register.php(43): BiosystemStudios\Mail\Mailer->send('email/auth/regi...', Array, Object(Closure))
> #5 [internal function]: {closure}()
> #6 E:\xampp\htdocs\biosys\vendor\slim\slim\Slim\Route.php(468): call_user_func_array(Object(Closure), Array)
> #7 E:\xampp\htdocs\biosys\vendor\slim\slim\Slim\Slim.php(1357): Slim\Route->dispatch()
> #8 E:\xampp\htdocs\biosys\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
> #9 E:\xampp\htdocs\biosys\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
> #10 E:\xampp\htdocs\biosys\app\BiosystemStudios\Middleware\BeforeMiddleware.php(14): Slim\Middleware\MethodOverride->call()
> #11 E:\xampp\htdocs\biosys\app\BiosystemStudios\Middleware\CsrfMiddleware.php(19): BiosystemStudios\Middleware\BeforeMiddleware->call()
> #12 E:\xampp\htdocs\biosys\vendor\slim\slim\Slim\Middleware\PrettyExceptions.php(67): BiosystemStudios\Middleware\CsrfMiddleware->call()
> #13 E:\xampp\htdocs\biosys\vendor\slim\slim\Slim\Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
> #14 E:\xampp\htdocs\biosys\public\index.php(5): Slim\Slim->run()
> #15 {main}

this is the code in my start.php file
```php
$app->container->singleton('mail', function() use ($app){
    $mailer = new Mailgun($app->config->get('mail.secret'));
    $mailer->setSslEnabled(false);
    return new Mailer($app->view, $app->config, $mailer);
});
```
my mailer class
```php
<?php

namespace BiosystemStudios\Mail;

class Mailer
{
    protected $view;
    
    protected $config;
    
    protected $mailer;
    
    public function __construct($view, $config, $mailer)
    {
        $this->view = $view;
        $this->config = $config;
        $this->mailer = $mailer;
    }
    
    public function send($template, $data, $callback)
    {
        $builder = $this->mailer->MessageBuilder();
        $builder->setFromAddress($this->config->get('mail.from'));
        
        $message = new Message($builder);
        $message->from($this->config->get('mail.from'));
        
        $this->view->appendData($data);
        
        $message->body($this->view->render($template));
        
        call_user_func($callback, $message);
        
        $domain = $this->config->get('mail.domain');
        $this->mailer->post("{$domain}/messages", $builder->getMessage());
    }
}
```
and my Message class
```php
<?php

namespace BiosystemStudios\Mail;

class Message
{
    
    protected $mailer;
    
    public function __construct($mailer)
    {
        $this->mailer = $mailer;
    }
    
    public function to($address)
    {
        $this->mailer->addToRecipient($address);
    }
    
    public function subject($subject)
    {
        $this->mailer->setSubject($subject);
    }
    
    public function body($body)
    {
        $this->mailer->setHtmlBody($body);
    }
    
    public function from($address)
    {
        $this->mailer->setFromAddress($address);
    }
}
```

and lastly the snippet that's throwing the error
```php
        $app->mail->send('email/auth/registered.php', ['user' => $user, 'identifier' => $identifier], function($message) use ($user) {
            $message->to($user->email);
            $message->subject('Thanks for registering!');
        });
```
I have not added any extra classes/plugins/extensions/etc.. to Mailgun and am running vanilla Mailgun. I am trying to use a sandbox domain on mailgun on my local machine so that's why I had the `$mailer->setSslEnabled(false);` line of code. I am not sure what I am doing wrong. And just to help with more information, my dependencies (composer.json)

```json
{
    "autoload": {
        "psr-4": {
            "BiosystemStudios\\": "app/BiosystemStudios"
        }
    },
    "require": {
        "slim/slim": "^2.6",
        "slim/views": "0.1.*",
        "twig/twig": "~1.0",
        "hassankhan/config": "0.10.*",
        "illuminate/database": "~5.0",
        "alexgarrett/violin": "2.*",
        "ircmaxell/random-lib": "~1.2",
        "mailgun/mailgun-php": "^2.1",
        "php-http/curl-client": "^1.6",
        "guzzlehttp/psr7": "^1.3"
    }
}
```

**Comment by Nyholm** [comment]
The API does not exist at http://api.mailgun.net. It only exist at https://api.mailgun.net. The `setSslEnabled` is deprecated and should not be used. 


Btw, I see that you are using the Slim framework. The latest version of Httplug discovery and message supports slims PSR7 implementation so there is no need for Guzzlehttp/PSR7.
