### ISSUE TITLE
It is not possible to deliver mails to an address with german umlauts.

### ISSUE THREAD

**Issue by kevkrei** [mailgun/mailgun-php#211]
If I try to send a mail to an address like "exämple@test.de" with the mailgun-php api, the response is:

**The parameters passed to the API were invalid. Check your inputs! 'to' parameter is not a valid address. please check documentation**

I use mailgun-php version 2.1.2

**Comment by Nyholm** [comment]
That seams to be correct. That address violates RFC5322. See section 3.23: https://tools.ietf.org/html/rfc5322#section-3.2.3
