### ISSUE TITLE
Use PSR-4

### ISSUE THREAD

**Issue by Nyholm** [mailgun/mailgun-php#219]
Instead of PSR-0, we should use PSR-4. 
This change is considered as BC breaking so we should not do it until we are ready for 3.0.

**Comment by DavidGarciaCat** [comment]
@Nyholm What is the major BC breaking that we can find here? What is the main reason to wait?

According to www.php-fig.org and specially on [PSR-4: Autoloader](http://www.php-fig.org/psr/psr-4/) page "This PSR describes a specification for autoloading classes from file paths. It is fully interoperable, and can be used in addition to any other autoloading specification, including PSR-0. This PSR also describes where to place files that will be autoloaded according to the specification."

Given PSR-4 is - let's say - an improvement for PSR-0 (that has been flagged as deprecated), and given both are managing the autoloader, I don't see the problem to set the new configuration now.

**Comment by Nyholm** [comment]
If someone for some weird reson have written something like this in their code, it wont work: 
```php
$mailgunContent = file_get_contents('vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php');
```

The new path would be. `vendor/mailgun/mailgun-php/src/Mailgun.php`

**Comment by DavidGarciaCat** [comment]
I never did something like this, but - in the end - this "someone" will get the same error after apply the PSR-4. By other side, stable releases are still using PSR-0 so as far the user don't download the `dev-master` branch all should work as expected.
