### ISSUE TITLE
Set headers

### ISSUE THREAD

**Issue by krystalcode** [mailgun/mailgun-php#221]
Hello,

I need to set the Accept header for retrieving the full raw mime message (https://documentation.mailgun.com/api-sending.html#retrieving-stored-messages). This is currently not possible with the Mailgun client, I would have to build a request with Guzzle or similar.

A solution could be to add an $options array as a last argument to the get/post etc. methods where I could pass $options['headers'] = ['Accept' => 'message/rfc2822']. The headers would then be passed to the Connection object.

**Comment by DavidGarciaCat** [comment]
@Nyholm what do you think? can we add a new feature to set custom headers as part of the new SDK update? Cheers,

**Comment by Nyholm** [comment]
Yes, We should definitely support this. I'll add the milestone "Better API" to this issue.

**Comment by Nyholm** [comment]
Have a look at the new [MessageApi](https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Api/Message.php#L82)

It is now supported to fetch the complete message.
