### ISSUE TITLE
Puli factory is not available

### ISSUE THREAD

**Issue by inorganik** [mailgun/mailgun-php#222]
Hi, I'm trying to use the method which adds a member to a mailing list:

    $result = $mgClient->post("lists/$listAddress/members", array( ... ));

However it's throwing this:

> Fatal error: Uncaught exception 'Http\Discovery\Exception\PuliUnavailableException' with message 'Puli Factory is not available' in /var/www/html/tung-staging/vendor/php-http/discovery/src/Strategy/PuliBetaStrategy.php:39 Stack trace: #0 /var/www/html/tung-staging/vendor/php-http/discovery/src/Strategy/PuliBetaStrategy.php(64): Http\Discovery\Strategy\PuliBetaStrategy::getPuliFactory() #1 /var/www/html/tung-staging/vendor/php-http/discovery/src/Strategy/PuliBetaStrategy.php(79): Http\Discovery\Strategy\PuliBetaStrategy::getPuliDiscovery() #2 [internal function]: Http\Discovery\Strategy\PuliBetaStrategy::getCandidates('Http\Message\St...') #3 /var/www/html/tung-staging/vendor/php-http/discovery/src/ClassDiscovery.php(54): call_user_func('Http\Discovery\...', 'Http\Message\St...') #4 /var/www/html/tung-staging/vendor/php-http/discovery/src/StreamFactoryDiscovery.php(25): Http\Discovery\ClassDiscovery::findOneByType('Http\Message\St...') #5 /var/www/html/tung-staging/vendor/php-http/multipart-stream-builder/src/MultipartStre in /var/www/html/tung-staging/vendor/php-http/discovery/src/StreamFactoryDiscovery.php on line 27

I tried wiping the composer and vendor files, and reinstalling them to no avail. Is there a fix for this? Thanks.

**Comment by DavidGarciaCat** [comment]
Hello @inorganik

Gould you please tell us what PHP version you're using?
Also the Mailgun SDK version that you have installed through composer?

Thanks,

**Comment by inorganik** [comment]
Sure, I'm using php v5.5.9.
Mailgun v2.1.2

**Comment by Nyholm** [comment]
What version of php-http/discovery are you using?
Do you have puli installed?

**Comment by inorganik** [comment]
The [Mailgun docs](https://documentation.mailgun.com/libraries.html#php) say to do these 2 steps - that's what I did.

    curl -sS https://getcomposer.org/installer | php
    php composer.phar require mailgun/mailgun-php:~x.x

**Comment by Nyholm** [comment]
Have a look at the docs here: https://github.com/mailgun/mailgun-php/tree/v2.1.2
I have an [open pull request](https://github.com/mailgun/documentation/pull/187) to change those docs. (Maybe @pirogoeth can help?)

What you miss is a http client, message factories and a PSR-7 implementation. 

According to the updated docs you should run: 

```bash
curl -sS https://getcomposer.org/installer | php
php composer.phar require mailgun/mailgun-php php-http/curl-client guzzlehttp/psr7 php-http/message
```

**Comment by inorganik** [comment]
Thank you, that worked.

Btw, that's a crazy amount of dependencies for making a curl request.

**Comment by Nyholm** [comment]
Okey, great. 

Yes, it is. But all of them are very small, stable and SOLID. We do not want to be opinionated what HTTPclient or what PSR-7 implementation you should use.
