### ISSUE TITLE
Argument validation on API results

### ISSUE THREAD

**Issue by Nyholm** [mailgun/mailgun-php#225]
When the API answers with something unexpected we throw an `InvalidArgumentException` on the user. Which means that the user should retry the API call with different parameters. That is wrong. The user did not do anything wrong. It was either the API or our API client that has made some misstakes. 

In my opinion there is two possible solutions: 
 1. Throw an `ServerAnsweredSomethingUnexpectedException`
 2. Return the result as good as we can.

I would prefer 2 which means we remove all assertions of the server response.

**Comment by pirogoeth** [comment]
I also agree with 2. I think that if we just have to return the "best guess" response, we should log it / throw a warning noting that the user should probably file an issue here because `x`, `y`, or `z` is broken.

**Comment by Nyholm** [comment]
Agreed!

**Comment by Nyholm** [comment]
Closed by #230
