### ISSUE TITLE
Enable Scrutinizer

### ISSUE THREAD

**Issue by Nyholm** [mailgun/mailgun-php#232]
We can get nice code coverage and code quality score. 

https://scrutinizer-ci.com/

Create a user and then create a Mailgun organisation. Then you only need to add this repo, select PHP language and we are done. (We should not run tests)

**Comment by pirogoeth** [comment]
Great idea! Done!

https://scrutinizer-ci.com/g/mailgun/mailgun-php/

**Comment by Nyholm** [comment]
Awesome!

**Comment by DavidGarciaCat** [comment]
Don't forget to add the Scrutinizer CI config file to set the expected inspection behaviour and get the code coverage too 😄

**Comment by Nyholm** [comment]
Config is added in master. Coverage will show as soon as the build is green in master.
