### ISSUE TITLE
Adding custom header - add a non-array value

### ISSUE THREAD

**Issue by jameskraus** [mailgun/mailgun-php#254]
Right now adding a custom header adds the value as an array:

```
    public function addCustomHeader($headerName, $headerData)
    {
        if (!preg_match('/^h:/i', $headerName)) {
            $headerName = 'h:'.$headerName;
        }
        $this->message[$headerName] = [$headerData];

        return $this->message[$headerName];
    }
```

Why isn't it just:

`$this->message[$headerName] = $headerData;`

Because right now I get weird headers like this:

`X-Auto-Response-Suppress[0]: All`

When I call it like this:

`$thing->addCustomHeader('X-Auto-Response-Suppress', 'All');`

**Comment by ivanjaros** [comment]
Just encountered this issue myself. Yeah, that should be string since docs expect string, not array: https://documentation.mailgun.com/api-sending.html#sending

**Comment by jameskraus** [comment]
PR was merged.
