### ISSUE TITLE
Line breaks ignored

### ISSUE THREAD

**Issue by ivanjaros** [mailgun/mailgun-php#259]
Hi,
I am sending email(s) to gmail and all break lines are missing. I am using the message builder. I have tried to set only html version, I have tried to replace `\n` with `<br>` but nothing helps.

I think this might have something to do with forced header `Content-Transfer-Encoding: quoted-printable` that cannot be overridden. I also have `format=flowed` in Content-Type header which is stripped by Mailgun. So maybe there's the issue.

also, strangely, when looking at the "original message" in gmail, the message has proper break lines.

**Comment by Nyholm** [comment]
Can it be that Gmail intrepid the message as HTML which means that line breaks does not matter. 

Try sending messages with a mime file and use HTML in that file.

**Comment by ivanjaros** [comment]
Ok, so what worked in the end is using only the `\Mailgun\Messages\MessageBuilder::setHtmlBody` without `\Mailgun\Messages\MessageBuilder::setTextBody` and replacing `\n` with `<br>`.

**Comment by DavidGarciaCat** [comment]
Hello @ivanjaros 

Although is a good practice provide both contents (html & plain text), all major webmail and desktop clients are allowing nowadays HTML content (even those that have been built by Microsoft), so I believe you can ignore the plain text context, specially if the problem appears just on Gmail.

Also, usually, when an email client cannot read HTML content, the content is displayed as plain text by default (so you can see some things like `link<link>` or `<image>`) but the email should be delivered, as usual.

Cheers,

**Comment by Nyholm** [comment]
Closing due inactivity.

**Comment by quyettv95** [comment]
Using PHP_EOL solve the problem
