### ISSUE TITLE
Wrong content when retrieving an attachment.

### ISSUE THREAD

**Issue by Savageman** [mailgun/mailgun-php#262]
Hello,

The response handler always automatically try to decode the content body with `json_decode()`. This has a side effect when retriving an attachment whose content starts with digits.

I have an email attachment which looks like this: `2.500#tons#more#of#binary#data` and the result I get with `$mailgun->get($attachment_url)` is a `(float) 2.5` rather than the whole `(string) "2.500#tons#more#of#binary#data"`.

**Comment by shakaran** [comment]
@Nyholm maybe append a empty string and concatenate to the attachment before to json_decode() could force to avoid the float or integer casting? Or just casting with strval() php native function or (string) $variable casting?

**Comment by Nyholm** [comment]
Closing due inactivity.
