### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by pbowyer** [mailgun/mailgun-php#263]
There's been some fantastic changes since 2.1.2 was released in August 2016 (e.g. the Events API, which I'm excited about!).

For us using Composer, can we have a new tagged release soon, so we can avoid using `dev-master`? Thanks.

**Comment by Nyholm** [comment]
Thank you. 
There are a few issues that should be taken care of first. See https://github.com/mailgun/mailgun-php/milestone/1

We aslo have to make sure we are happy with the current structure and the new classes we introduced. Me and Mark has been working hard on a side project to display "what is the optimal http client". We might want to take a few concepts from there before we tagg a release. See https://github.com/FriendsOfApi/boilerplate

FYI: Tagging next release should be a minor version.

**Comment by Nyholm** [comment]
We will tag a new release this weekend.
