### ISSUE TITLE
Make it possible to get the raw response

### ISSUE THREAD

**Issue by Nyholm** [mailgun/mailgun-php#267]
From: @pbowyer

My use-case is that I want to store all the data for future re-processing, and there's no way to get to it. `json_encode($event)` doesn't work, nor does `json_encode(get_object_vars($event))` (rightly so).

Is that clearer? I've got:

```
$events = $mg->events()->get($this->getContainer()->getParameter('mailgun_domain'), [
    'begin' => $begin->format(\DateTime::RFC2822),
    'ascending' => true,
    'event' => 'NOT stored'
]);

while (count($events->getItems()) > 0) {
    foreach ($events->getItems() as $event) {
        // ... process each event
        // Save to log server
        // @TODO Save all data that's in $event (imagine passing to Monolog in the data parameter)
    }
} 
```

Related to https://github.com/mailgun/mailgun-php/issues/188#issuecomment-273792159

**Comment by Nyholm** [comment]
The KnpGithub API has a function like `GitHub::getLatestResponse`. We could use a plugin like that to fix this issue.

**Comment by DavidGarciaCat** [comment]
@Nyholm I can see you're "everywhere" 😄
Definitively that could be an inspiration for this issue.
