### ISSUE TITLE
Can't install Mailgun library

### ISSUE THREAD

**Issue by streetcoder** [mailgun/mailgun-php#27]
Dear Support team,

I have been trying to install mailgun library in my localhost using composer. I wrote in the command prompt the following commands:
- php composer require mailgun/mailgun-php:~1.3
  it gives me error as:

c:\mailgun-php>php composer.phar require mailgun/mailgun-php:~1.3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package mailgun/mailgun-php 1.0.0 could not be found.
  Problem 2
    - guzzle/guzzle v3.7.4 requires ext-curl \* -> the requested PHP extension cu
rl is missing from your system.
    - guzzle/guzzle v3.7.3 requires ext-curl \* -> the requested PHP extension cu
rl is missing from your system.
    - guzzle/guzzle v3.7.2 requires ext-curl \* -> the requested PHP extension cu
rl is missing from your system.
    - guzzle/guzzle v3.7.1 requires ext-curl \* -> the requested PHP extension cu
rl is missing from your system.
    - guzzle/guzzle v3.7.0 requires ext-curl \* -> the requested PHP extension cu
rl is missing from your system.
    - Installation request for guzzle/guzzle 3.7.\* -> satisfiable by guzzle/guzz
le[v3.7.0, v3.7.1, v3.7.2, v3.7.3, v3.7.4].

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion f
  or more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common
 problems.

Installation failed, reverting ./composer.json to its original content.

Please help me how to resolve it.

**Comment by teamu** [comment]
The requested package mailgun/mailgun-php No version set (parsed as 1.0.0) is satisfiable by mailgun/mailgun-php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

**Comment by Nyholm** [comment]
Hey. You should create a new issue so we do not bother more people than necessary. In that new issue, please provide a peace of your composer.json.

**Comment by teamu** [comment]
sure
