### ISSUE TITLE
Double quotes in from address

### ISSUE THREAD

**Issue by coldlamper** [mailgun/mailgun-php#270]
If I set the from address like
```
$message_builder->setFromAddress('test@test.net', ['full_name' => 'Bob "The Killer" Johnson']);
```
or
```
$name = addslashes('Bob "The Killer" Johnson');
$message_builder->setFromAddress('test@test.net', ['full_name' => $name]);
```
I get and API response message from mailgun like

> The parameters passed to the API were invalid. Check your inputs! 'from' parameter is not a valid address. please check documentation

If I use 
```
$message_builder->setFromAddress('"' . addslashes('Bob "The Killer" Johnson') . '" <' . 'test@test.net' . '>');
```
It works fine.

Maybe the code here https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Messages/MessageBuilder.php#L105 
```
protected function parseAddress($address, $variables)
    {
        if (!is_array($variables)) {
            return $address;
        }
        $fullName = $this->getFullName($variables);
        if ($fullName != null) {
            return "'$fullName' <$address>";
        }
        return $address;
    }

```
should use double quotes around the full name instead of single quotes. Maybe there is a reason not to do that?

**Comment by DavidGarciaCat** [comment]
Hello @coldlamper

Due you have found a solution, do you mind please to add a PR + PHPUnit tests to fix it?

Thanks,

**Comment by mreiden** [comment]
So #274 does not pass tests, but it works a lot better for me.  Needs more testing as I just started using MailGun this week and this is one of my first attempts using BatchMessage.  I haven't tested it without using BatchMessage, but thought it might help solve your problem if it works.

**Comment by DavidGarciaCat** [comment]
Hey there,

@coldlamper & @mreiden what's the current status on this issue? I can see there are 2 PRs related with this one, so I would like to know if they're solving your issue or if we still need to add another update:
- https://github.com/mailgun/mailgun-php/pull/274 (closed)
- https://github.com/mailgun/mailgun-php/pull/349 (merged)

Cheers,

**Comment by Nyholm** [comment]
Closing due inactivity.
