### ISSUE TITLE
Getting attachment doesn't work

### ISSUE THREAD

**Issue by s22su** [mailgun/mailgun-php#276]
Currently Mailgun API provides attachments as an array with full attachment URL.

Example:

`
[
  {
    "url": "https://se.api.mailgun.net/v3/domains/XXX/messages/XXX/attachments/0",
    "content-type": "image/jpeg",
    "name": "IMG_123.jpg",
    "size": 1545628
  }
]
`

It is not possible to get attachment using current RestClient::get method as it adds API URL (api.mailgun.net) and API version to the URL so it becomes:
https://api.mailgun.net/v2/https://se.api.mailgun.net/v3/domains/XXX/messages/XXX/attachments/0

Possible fixes:

1. change RestClient::get method
2. create a new method for getting an attachment

Fix: #277

**Comment by s22su** [comment]
Closed. See #277 for information.

**Comment by Nyholm** [comment]
Closed by #277 

Thank you @s22su
