### ISSUE TITLE
Make sure all models are final

### ISSUE THREAD

**Issue by Nyholm** [mailgun/mailgun-php#288]

**Comment by MichalHanajik** [comment]
Any tips which models are pretty sure extendable?
Marking all of them makes all [tests pass](https://travis-ci.org/MichalHanajik/mailgun-php/builds/203978868) 😄

**Comment by Nyholm** [comment]
Hm... Then it is okey =)

**Comment by MichalHanajik** [comment]
I'll send it as PR and then we will see if there will be some updates :)
