### ISSUE TITLE
Allow to send emails with empty body

### ISSUE THREAD

**Issue by yosmanyga** [mailgun/mailgun-php#290]
Currently if I send an email with `text = ''` if get the error ` The parameters passed to the API were invalid. Check your inputs! Need at least one of 'text' or 'html' parameters specified`.

If think that the system should allow to send emails with empty body.

**Comment by DavidGarciaCat** [comment]
Hi @yosmanyga 

Maybe I misunderstand your purpose, but I don't think this is right for 2 reasons:

1. As you said, the error says `The parameters passed to the API...` and this PHP code is the Mailgun SDK - not the Mailgun API - so even if we check/review/update the code of this SDK (in case there is a problem here, and I think this is not the case based on your comment) then Mailgun API will throw an error anyway, due the API checks and validates the data and parameters that have been sent via this SDK (or by another code that you can develop).

2. Mailgun provides a service to send emails like newsletters or system alerts (just a couple of examples), ideally - but not necessary - to a list of people that accepts to get these emails. Mailgun is not designed to manage multiple accounts, each one with its own inbox (and other folders), so I believe you are misunderstanding the purpose of the service provided by Mailgun, and you are expecting to get just a mail service where you can decide to send an email without body (that - in my oppinion - is useless and flagged as SPAM by some mail providers).

Given these 2 reasons, I believe you need to use a mail service provider like Google Apps (or another service offered by a hosting provider) but not Mailgun due obviously this is not the goal of this service.

I'm sorry...

**Comment by yosmanyga** [comment]
Hi @DavidGarciaCat , thanks for your quick answer.

That's correct. The error comes from the API. So this ticket can be closed. But, I suggest that the error message should be different. Something like: `The parameters passed to the API were invalid. Check your inputs! Empty 'text' or 'html' parameters are not allowed`.

Ok, I will follow your advice about SPAM flagging, so the body will never be empty. But my system is not SPAM. I just used the subject to send the information to my clients.

**Comment by DavidGarciaCat** [comment]
Hi @yosmanyga 

No problem. Feel free to close the ticket yourself, if you think is now solved. 😄

Ping @Nyholm and @pirogoeth 

Any thoughts about these error messages? If they're provided by the API then I am not sure how easy will be to manage or customise them...

**Comment by Nyholm** [comment]
As you say, the error message is from the API server. There is nothing we can do about it. :/
