### ISSUE TITLE
multiple fopen, which are never closed

### ISSUE THREAD

**Issue by cklm** [mailgun/mailgun-php#298]
Hi, in src/Mailgun/Connection/RestClient.php are two `fopen`-functions, which are not closed. Sending over 1.000 mails in serial line leads to the following error:
`[Http\Client\Exception\NetworkException]
error:02001018:system library:fopen:Too many open files`

Is it possible to safely close the two fopens, or are they needed in another place?

**Comment by Nyholm** [comment]
I believe it is safe to close it. Can you send a PR?

**Comment by Nyholm** [comment]
Closing due inactivity.
