### ISSUE TITLE
function 'addToRecipient' is not working like described

### ISSUE THREAD

**Issue by schlesie** [mailgun/mailgun-php#301]
Hi

on your mailgun messages page you list the possible functions and show an example how to use them. In the example "Usage - Batch Message" there is a multiple function call "addToRecipient". 

```
$batchMsg->addToRecipient("john.doe@example.com", array("first" => "John", "last" => "Doe"));
$batchMsg->addToRecipient("sally.doe@example.com", array("first" => "Sally", "last" => "Doe"));
$batchMsg->addToRecipient("mike.jones@example.com", array("first" => "Mike", "last" => "Jones"));
```

So I have done somethin similar, just don't using the attributes array.

```
$addresses = array('foo@bar.com', 'bar@foo.com');
foreach ($addresses as $recipient) {
    $messageBldr->addToRecipient($recipient);
}
```

BUT, this won't work. Only the second e-mail address is sent to mailgun. But if I just call the function once with a comma separated list, it will work

```
$addresses = array('foo@bar.com', 'bar@foo.com');
$messageBldr->addToRecipient(implode(',', $addresses ));
```

So why would the first version which is described in your example won't  work?

Regards
Dirk

**Comment by uavn** [comment]
The following code works just fine:

```
$mg = Mailgun::create($key);
$batch = $mg->messages()->getBatchMessage($domain);

$addresses = ['artbonvic@gmail.com', 'artbon.vic@gmail.com'];
foreach ($addresses as $email) {
    $batch->addToRecipient($email);
}
$batch->setFromAddress('mailgun@uartema.com');
$batch->setSubject('Test');
$batch->setTextBody('Hello');

$batch->finalize();
```

both emails received:
![mailgun-test](https://user-images.githubusercontent.com/315338/94288661-54a0f780-ff60-11ea-9a1f-259cf1c82a2c.jpg)

**Comment by DavidGarciaCat** [comment]
I would actually suggest @schlesie if it's possible to include a fully functional code where we can see the problem, as the solution provided by @uavn seems to be working (as per the screenshots). Maybe there's a problem with one of the mailbox addresses?

**Comment by schlesie** [comment]
Hi,
thanks to your comments.
The issue is from 2017 and I think we have found a workaround.
