### ISSUE TITLE
Using IIS server works fine in local but error on server : cURL error 77

### ISSUE THREAD

**Issue by csmtcy** [mailgun/mailgun-php#302]
The library is completely fine in local development but failed on server. 
I can't do any changes on server, may i know how to fix this ? Thanks.

```
cURL error 77: error setting certificate verify locations:
CAfile: C:\Program Files (x86)\Parallels\Plesk\Additional\PHPSettings\cacert.pem
CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

**Comment by Nyholm** [comment]
That is a common error on Windows. You have to download a new certificate and att it to php.ini. 

The error is not related to Mailgun but to curl. Read more about it on the link in the error message or if you google "curl error 77 windows"
