### ISSUE TITLE
Reading error messages programmatically

### ISSUE THREAD

**Issue by z38** [mailgun/mailgun-php#311]
During rebasing my PR #294, I noticed that after applying [#307 Improving safe hydrate](https://github.com/mailgun/mailgun-php/pull/307) it's no longer possible to get the exact error message the server returned. The exception thrown only contains a generic HTTP response object.

Should these messages made available again for everyone or should we just decode them in our integration testsuite for ourselves?

**Comment by Nyholm** [comment]
Thank you for making this issue. 

If you get an error we throw an exception. The exception has the PSR7 response. You could always do the following ot get the response from Mailgun. 

```php
try {
  // Make API call
} catch (\Mailgun\Exception $e) {
    echo $e->getReponse()->getBody(); 
}
```

Tell me more about your use case. Why are you interested in the response from the server? How do you use it?

**Comment by z38** [comment]
The [integration testsuite](https://github.com/mailgun/mailgun-php/tree/master/tests/Integration) of this library used it to check whether the error message from the server was the one we expected. 

On second thought, it might be sufficient to just verify that the correct exception is thrown at all.

**Comment by z38** [comment]
So, as we don't need to this internally ([comment in #294](https://github.com/mailgun/mailgun-php/pull/294#issuecomment-289288448), I think we can close this issue for now.

@Nyholm I leave it up to you if you want to merge or close #312.

**Comment by Nyholm** [comment]
I think it is a use for #312 because it may contain some details. Ie on 400: which parameter is invalid etc.
