### ISSUE TITLE
issue with webhooks

### ISSUE THREAD

**Issue by gaurav16694** [mailgun/mailgun-php#320]
hi i am facing issue while using the webhooks for the events..as i am getting the message-id response in webhook for event like delivery but i am not getting message_id response in webhook for the open and clicks event..please look into the issue.

**Comment by Nyholm** [comment]
Have you tried the new API in dev-master?

**Comment by z38** [comment]
@gaurav16694 Getting the message ID from events such as open, clicks, ... is currently not documented. However, as of today there is a field `message-id` (note: lowercase) which includes the message ID without brackets. As it's not documented, this feature might disappear in the future.
