### ISSUE TITLE
Unable to verify/handle webhooks with the new API

### ISSUE THREAD

**Issue by z38** [mailgun/mailgun-php#321]
`Mailgun::verifyWebhookSignature()` is deprecated and will be removed in 3.0. `Mailgun\Api\Webhook` does not offer this functionality yet. It might be worth investigating if the received events should be parsed and wrapped in models too.

**Comment by DavidGarciaCat** [comment]
Thanks @z38 - We will try to keep this in mind before the new release is tagged officially.

**Comment by Nyholm** [comment]
Agreed. Lets create a function in the new API for verify webhook signature.
