### ISSUE TITLE
outdated multipart-stream-builder

### ISSUE THREAD

**Issue by neokio** [mailgun/mailgun-php#324]
This isn't an issue so much as a reminder (and soothing my "must have the latest version of everything" OCD).

```
% composer outdated
php-http/multipart-stream-builder    0.1.6   0.2.0   A builder class that help you create a multipart stream

% composer depends php-http/multipart-stream-builder
mailgun/mailgun-php  v2.1.2  requires  php-http/multipart-stream-builder (^0.1)
```

**Comment by Nyholm** [comment]
Thank you. This is fixed in master. We allow both 0.1.0 and 0.2.0. 

FYI: I will tag a stable version of `php-http/multipart-stream-builder` before the summer (if no major issues comes up).
