### ISSUE TITLE
inline image php error

### ISSUE THREAD

**Issue by abrantw73** [mailgun/mailgun-php#34]
Getting the following warning when trying to add an inline image to a message via mailgun php.  Email is sent, but there is no inline image

Warning: Invalid argument supplied for foreach() in /var/www/html/blahblahblah.com/public/php/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php on line 65

using mailgun 1.7 and using the following sample code as a guide:
# Include the Autoloader (see "Libraries" for install instructions)

require 'vendor/autoload.php';
use Mailgun\Mailgun;
# Instantiate the client.

$mgClient = new Mailgun('key-3ax6xnjp29jd6fds4gc373sgvjxteol0');
$domain = "samples.mailgun.org";
# Make the call to the client.

$result = $mgClient->sendMessage("$domain",
           array('from'    => 'Excited User me@samples.mailgun.org',
                 'to'      => 'foo@example.com',
                 'cc'      => 'baz@example.com',
                 'bcc'     => 'bar@example.com',
                 'subject' => 'Hello',
                 'text'    => 'Testing some Mailgun awesomness!',
                 'html'    => '<html>Inline image: <img src="cid:test.jpg"></html>'),
           array('inline' => '@/path/to/test.jpg'));

**Comment by alexandrubau** [comment]
I really think that this should be in the readme. I spent a lot of time trying to figure this out.

Thanks @Tim-Machine
