### ISSUE TITLE
There is no endpoint while class instantiation

### ISSUE THREAD

**Issue by vanzay** [mailgun/mailgun-php#346]
Hi, the following code doesn't work
```
$mailgunClient = new Mailgun($apikey, $httpClient);
$mailgunClient->messages()->send($domain, array(
...
));
```
because httpClient tries to send message directly to '/v3/%s/messages' (without endpoint).
Instead of that I should use
```
$configurator = new HttpClientConfigurator();
$configurator->setApiKey($apikey);
$configurator->setHttpClient($httpClient);
$mailgunClient = Mailgun::configure($configurator);
```
It's confusing.

**Comment by Nyholm** [comment]
Correct. You should not use the Mailgun::__construct. See the readme: https://github.com/mailgun/mailgun-php#usage

**Comment by vanzay** [comment]
It would be useful to add this info to the readme. As well as example of using custom httpclient.

**Comment by Nyholm** [comment]
The readme is updated with info of how you create an instance of the Mailgun class. The code is also documented with `@deprecation` notices. I just added a PR to be more clear that the constructor is for internal use only. See #347

**Comment by DavidGarciaCat** [comment]
Hey @Nyholm - What about an update to make it a `private constructor` to be sure developers are using the named constructor we have?

**Comment by Nyholm** [comment]
Making it private would be a BC break. But otherwise it would be a good solution. See #347

**Comment by DavidGarciaCat** [comment]
I already added a review, I checked that PR after add a comment here. Thanks!
