### ISSUE TITLE
from name and email together not sending

### ISSUE THREAD

**Issue by jayeshm66** [mailgun/mailgun-php#348]
If i am sending from parameter like below
'from'    => 'name mailgun@domain.com',
its giving error : Uncaught exception 'Mailgun\\Connection\\Exceptions\\MissingEndpoint' with message 'The endpoint you've tried to access does not exist. Check your URL

but below is going fine
'from'    => 'mailgun@domain.com',

How can i send from name then

**Comment by Nyholm** [comment]
Are you using the factory method?
See example here: https://github.com/mailgun/mailgun-php#usage

**Comment by jayeshm66** [comment]
exactly as it is i am using,

But dont have '**name'** parameter

**Comment by jayeshm66** [comment]
It was going till 2 days ago perfectly, i think sendgrid updated API

**Comment by Nyholm** [comment]
Can you paste your code here?

`'from' => 'name <mailgun@domain.com>',`

**Comment by jayeshm66** [comment]
```
$mgClient = new Mailgun('key-XXX');
$domain = "domain.com";

# Make the call to the client.
$result = $mgClient->sendMessage($domain, array(
    'from'    => 'fromname mailgun@domain.com',
    'to'      => 'to@gmail.com',
    'subject' => 'Hello',
    'text'    => 'Testing some Mailgun awesomness!'
));

```
Ref: [](https://documentation.mailgun.com/quickstart-sending.html#send-via-api)

**Comment by z38** [comment]
The problem might be the `<>` brackets which are part of the syntax and not some kind of placeholder. So, if you want to send an email to `mailgun@domain.com`, the call should look like this:
```
$result = $mgClient->messages()->send($domain, array(
    'from' => 'fromname <mailgun@domain.com>'
    // ...
```

**Comment by jayeshm66** [comment]
Thanks @z38 
Got it, `<>` are little confusing
