### ISSUE TITLE
Mails get combined...

### ISSUE THREAD

**Issue by elonmir** [mailgun/mailgun-php#350]
I was migrating the old mailgun integration to the new api version, and stumbled upon an very interesting bug.

If I follow your demo code, it work's fine, for a single message.
```
        $mg = \Mailgun\Mailgun::create("key-xxx");
        $mg->messages()->send($this->domain, [
            'from' => 'bob@example.com',
            'to' => 'foo@bar.com',
            'subject' => 'The PHP SDK is awesome!',
            'text' => 'It is so simple to send a message.'
        ]);
```

So for sending another message that would mean...

```
        $mg = \Mailgun\Mailgun::create("key-xxx");
        $mg->messages()->send($this->domain, [
            'from' => 'bob@example.com',
            'to' => 'foo@bar.com',
            'subject' => 'The PHP SDK is awesome!',
            'text' => 'It is so simple to send a message.'
        ]);
       $mg->messages()->send($this->domain, [
            'from' => 'bob@example.com',
            'to' => 'foo@bar.com',
            'subject' => 'XYZThe PHP SDK is awesome!',
            'text' => 'It is so simple to send a message.'
        ]);
```

Well... the outcome is not as expected.

![image](https://cloud.githubusercontent.com/assets/1140767/25956249/7fd2c328-366b-11e7-9ad2-c32f41882dcc.png)

I don't know if that behavior is correct. If I would like to  succeed, I would have to initiate the SDK for a second time.

```
        $mg = \Mailgun\Mailgun::create("key-xxx");
        $mg->messages()->send($this->domain, [
            'from' => 'bob@example.com',
            'to' => 'foo@bar.com',
            'subject' => 'The PHP SDK is awesome!',
            'text' => 'It is so simple to send a message.'
        ]);
       $mg2 = \Mailgun\Mailgun::create("key-xxx");
       $mg2->messages()->send($this->domain, [
            'from' => 'bob@example.com',
            'to' => 'foo@bar.com',
            'subject' => 'XYZThe PHP SDK is awesome!',
            'text' => 'It is so simple to send a message.'
        ]);
```

So for sending another message that would mean. We use a symfony stack, and till now used the message builder, which gets deprecated, as a service. So only a single initialization and after that just fire away. 

Feedback would be appreciated.

**Comment by Nyholm** [comment]
Hm. That sure is an interesting bug. I cant understand why you getting only one email with double content. 

```php
$mg = \Mailgun\Mailgun::create("key-xxx");
$responseA = $mg->messages()->send($this->domain, [
            'from' => 'bob@example.com',
            'to' => 'foo@bar.com',
            'subject' => 'The PHP SDK is awesome!',
            'text' => 'It is so simple to send a message.'
        ]);

// You may pause here and investigate $responseA

$responseB = $mg->messages()->send($this->domain, [
            'from' => 'bob@example.com',
            'to' => 'foo@bar.com',
            'subject' => 'XYZThe PHP SDK is awesome!',
            'text' => 'It is so simple to send a message.'
        ]);
```
What happens if you check the response of A before you start sending next one?

**Comment by elonmir** [comment]
![image](https://cloud.githubusercontent.com/assets/1140767/25958193/526e63ce-3670-11e7-9d0e-a3db0ddcf6b5.png)

Same outcome...

**Comment by elonmir** [comment]
Same outcome...

![image](https://cloud.githubusercontent.com/assets/1140767/25958282/877eba0a-3670-11e7-8262-f5e3118ae731.png)

**Comment by Nyholm** [comment]
Is it different IDs?

**Comment by elonmir** [comment]
Yes... that was the first thing I checked. I assumed that the mix up happens in our service, but that wasn't the case.

**Comment by Nyholm** [comment]
Do you get two emails or one email?
What does the mailgun log on the dashboard say?

**Comment by Nyholm** [comment]
Oh, If the second email has both contents then it makes sense, is that the case?

**Comment by elonmir** [comment]
Sorry to disappoint you, I get to separate mails. The first one is ok, the second one gets concanated.

![image](https://cloud.githubusercontent.com/assets/1140767/25958537/2437dbe2-3671-11e7-8b34-3b200128cd6d.png)

Mailgun logs indicate to separate mails, with different content.

**Comment by Nyholm** [comment]
Can you try https://github.com/mailgun/mailgun-php/pull/351?

**Comment by elonmir** [comment]
Yes, works.

**Comment by Nyholm** [comment]
Awesome. 

Thank you for reporting this!

**Comment by elonmir** [comment]
Do you have a timeline for a new release? Otherwise I have to manually implement the fix.

**Comment by Nyholm** [comment]
I've tagged 2.3.1 now. 

We do not really have timelines. We try to group features for minor releases. There is no point in waiting to release patches like this one.
