### ISSUE TITLE
Unit tests enhancement

### ISSUE THREAD

**Issue by TemirkhanN** [mailgun/mailgun-php#357]
For some reason I am not agree with way unit tests been written.
Could you look for difference and tell your point of view?
[
https://github.com/TemirkhanN/mailgun-php/blob/tests-enhancement/tests/RequestBuilderTest.php](
https://github.com/TemirkhanN/mailgun-php/blob/tests-enhancement/tests/RequestBuilderTest.php)

**Comment by Nyholm** [comment]
You are correct. The current tests are more like functionality tests. They are testing that the output is correct. You are testing the input. 

Please send a PR.

**Comment by TemirkhanN** [comment]
There must be some way to divide unit, functional and integration tests.. For now directory structure(tests) makes namespace collision that prevents code-coverage rising.

**Comment by Nyholm** [comment]
Closed by #358
