### ISSUE TITLE
Debugging mode and hydrator

### ISSUE THREAD

**Issue by bupy7** [mailgun/mailgun-php#359]
Hi, everyone.
I enabled debugging mode with configuration:

```
$configurator->setEndpoint($options->getEndpoint());
$configurator->setDebug(true);
```

After every request I get `Mailgun\Exception\HydrationException` with the message `The ModelHydrator cannot hydrate response with Content-Type: text/html;charset=utf-8`. I think that endpoint cannot uses `application/json` header or there is sent `text/html` header ever. I didn't recognize yet.

Should I use `Mailgun\Hydrator\NoopHydrator`, shouldn’t I? But it's very bad idea.

**Comment by Nyholm** [comment]
Oh. That's right. I never thought about that before. Try using the PSR7ResponseHydrator. 

The readme about the debugging should be updated. 

//Tobias Nyholm

**Comment by bupy7** [comment]
@Nyholm I want be use `ModelHydrator` because only header have `text/html` Content-Type but response body is JSON.

**Comment by bupy7** [comment]
Body in debug mode:
```
{"message":"Post received. Thanks!"}
````

**Comment by Nyholm** [comment]
You should create your own Hydrator (just copy ModelHydrator) that ignores the Content-Type header.

**Comment by bupy7** [comment]
@Nyholm I so did. =)

**Comment by Nyholm** [comment]
Great!

**Comment by dustingraham** [comment]
This was helpful. Following the docs yielded this same error for me.
