### ISSUE TITLE
webhooks()->index() no longer working

### ISSUE THREAD

**Issue by dmagoo** [mailgun/mailgun-php#364]
The create method of /Model/Webhook/IndexResponse.php expects an array of webhook urls keyed by type. { 'bounce' => bounce_url, 'spam' => spam_url, etc }.  This data is being passed in, but it is wrapped in another array as follows: {'webhooks' => { 'bounce' => bounce_url, 'spam' => spam_url, etc }}.

**Comment by Nyholm** [comment]
Hm, that is no good. Did the server team change the response?... @pirogoeth 

Can you make a PR that works with the new response type

**Comment by nickolaich** [comment]
I've created PR
