### ISSUE TITLE
Cached values of DNS records

### ISSUE THREAD

**Issue by maximzasorin** [mailgun/mailgun-php#367]
For GET /domain/\<domain> and PUT /domain/\<domain>/verify endpoints API returns current values of DNS records, it stored in cached property, but it not represented in SDK.

**Comment by Nyholm** [comment]
I'm not sure what you mean by "cached properly". Would you mind to elaborate?

**Comment by maximzasorin** [comment]
@Nyholm for GET /domain/\<domain> I get this response:

```
{
    "domain": {
        ...
    }, 
    "message": "Domain has been updated", 
    "receiving_dns_records": [
        {
            "cached": [
                "10 mx.yandex.net"
            ], 
            "priority": "10", 
            "record_type": "MX", 
            "valid": "unknown", 
            "value": "mxa.mailgun.org"
        }, 
        {
            "cached": [
                "10 mx.yandex.net"
            ], 
            "priority": "10", 
            "record_type": "MX", 
            "valid": "unknown", 
            "value": "mxb.mailgun.org"
        }
    ],
    ...
}
```

In issue I mean `cached` with current values of DNS records.

**Comment by Nyholm** [comment]
Ah. I see. I have not seen that before. Could you make a PR? I would be happy to review it.

**Comment by maximzasorin** [comment]
Maybe it is undocumented feature and not need in SDK, how you think?

**Comment by Nyholm** [comment]
I think it is new and "soon to be documented". Maybe @pirogoeth can confirm?

I think we should support it.
