### ISSUE TITLE
 The parameters passed to the API were invalid. Check your inputs! : When sending mail to a mailing list

### ISSUE THREAD

**Issue by AdnanHussainTurki** [mailgun/mailgun-php#369]
I am trying to send a message to a mailing list.

My code is 
`# First, instantiate the SDK with your API credentials
$mailgun = Mailgun::create(<--MYAPIKEY---->);

# Now, compose and send your message.
$mailgun->messages()->send("sandboxc----------------614.mailgun.org", [
  'from'    => 'adnan@myphpnotes.tk', 
  'to'      => 'mylist@sandb----------614.mailgun.org', 
  'subject' => 'The PHP SDK is awesome!', 
  'text'    => 'It is so simple to send a message.'
]);`

The code works fine when I send to any individual recipient.

**Comment by Nyholm** [comment]
What code do you use when sending to mailing list?

//Tobias Nyholm

Skickat på språng

**Comment by AdnanHussainTurki** [comment]
@Nyholm same code.
I am just changing to parameter to mailing list as shown.

**Comment by Nyholm** [comment]
Are you using your production key or a sandbox key?

**Comment by AdnanHussainTurki** [comment]
Sandbox key.

**Comment by Nyholm** [comment]
That's my be why

**Comment by AdnanHussainTurki** [comment]
Okay, I changed it to live domain and in the logs, I got my issue.

It says I need to upgrade my account to use the mailing list, for free members only authorised recipients will work.


Thanks for your help.

**Comment by anshu300** [comment]
read this

https://help.mailgun.com/hc/en-us/articles/217531258-Authorized-Recipients

problem solve
