### ISSUE TITLE
How send email with subscription url?

### ISSUE THREAD

**Issue by Radzhab** [mailgun/mailgun-php#376]
How send email with subscription url? I not found api method

**Comment by DavidGarciaCat** [comment]
Hi @Radzhab 

Can you please describe what's your goal?

A subscription URL can be added as part of your email's body (so you need your own business logic to deal with this request) or maybe you mean another Mailgun's feature that I don't understand.

By other side, if you can specify what you want to do (pointing the expected API reference here https://mailgun-documentation.readthedocs.io/en/latest/api_reference.html) will be easier to tell you if there's a problem, if we forgot something when we were building the current code, or if you're trying to do something that was not expected.

Cheers,

**Comment by ghaskell** [comment]
Probably can close this one, eh?

**Comment by DavidGarciaCat** [comment]
@ghaskell yep, 1 year without activity - closing

Thanks!
