### ISSUE TITLE
The Events API cannot be used for pagination

### ISSUE THREAD

**Issue by michbr** [mailgun/mailgun-php#380]
From Api/Event.php:

`$response = $this->httpGet(sprintf('/v3/%s/events', $domain), $params);`

Where a URL for a particular page takes the form:

https://<host>/v3/<domain>/events/<large_hash>

There is currently no way to from this request.

**Comment by DavidGarciaCat** [comment]
Hi @michbr 

Currently the `Mailgun\Api\Event` object already is using the `trait  Pagination` object here:
https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Api/Event.php#L22

And `Pagination` has some methods to get some pages as you can see here:
https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Api/Pagination.php#L25-L63

Maybe I didn't understand what you mean, so if you can provide an example, will be great.

Many thanks,

**Comment by michbr** [comment]
Looks like I misunderstood the API. Thanks!
