### ISSUE TITLE
Custom recipient variables do not work

### ISSUE THREAD

**Issue by vercotux** [mailgun/mailgun-php#385]
If I add recipients this way:

    $messageBuilder->addToRecipient($email, [
        'testvar' => 'some_var',
        'full_name' => 'some1',
    ]);

And then render the message body as

    Hello %recipient_name%, your var is: %recipient.testvar%.

The email delivered is:

    Hello some1, your var is: %recipient.testvar%.

Whis is this not working? The API documentation clearly [says](http://mg-documentation.readthedocs.io/en/latest/user_manual.html#mailing-lists) that we are able to do that:

>%recipient.yourvar% | Accessing a custom datavalue. (see Attaching Data to Messages)

**Comment by ksaitor** [comment]
hey @vercotux  so what was your solution to this? I'm running into the same problems (with Nodejs tho)
