### ISSUE TITLE
Cannot call domains()->create() with empty smtp/spam/wildcard

### ISSUE THREAD

**Issue by Savageman** [mailgun/mailgun-php#397]
Hi.

The `POST /domains` end-point can definitely be called without `smtp_password`, `spam_action` and `wildcard`, but the PHP API doesn't allow it since it checks for `Assert::stringNotEmpty()` for all 3 params.

Should I send a PR?

**Comment by DavidGarciaCat** [comment]
Hello @Savageman 

I would say "feel free to send the PR"; just please don't forget to provide updated PHP Unit tests too, we need to make sure we accept valid values and the tests are returning thumbs up.

/cc @Nyholm @pirogoeth

**Comment by Nyholm** [comment]
:+1:

**Comment by shakaran** [comment]
@DavidGarciaCat @Nyholm @pirogoeth [I did the PR ](https://github.com/shakaran/mailgun-php/commit/c5da35073ad01c2a0b74286c67d3559976fce41b) I don't found any test for POST domain in folder test, so it should work properly, let me know if there are something more needed

**Comment by DavidGarciaCat** [comment]
I would say to add new PHPUnit tests, even if they don't exist yet. What do
you think? Can you add them too?

D

**Comment by shakaran** [comment]
@DavidGarciaCat yes sure, I just need a bit of free time to it, I will try to send another PR separated with the tests

**Comment by DavidGarciaCat** [comment]
PR https://github.com/mailgun/mailgun-php/pull/399 has been merged
