### ISSUE TITLE
[v2] How-to retrieve an attachment without using a deprecated function?

### ISSUE THREAD

**Issue by Savageman** [mailgun/mailgun-php#398]
Hi.

Both `get()` and `getAttachment()` are deprecated in 2.x so it seems there is no public v2 API to retrieve an attachment.

What would be the best way to achieve it? Would exposing the httpClient be an option?

Some other API may not be available yet and exposing the httpClient directly would allow everyting not anticipated to be possible.
For example `domains()->verify()` was added recently but since it's not available in any tagged version yet, this is not usable. Could other API methods could be in the same situation?

**Comment by Nyholm** [comment]
This is fixed in 2.7.0 and in PR #476
