### ISSUE TITLE
How to add recipient variables in batch email ? 

### ISSUE THREAD

**Issue by iit2011081** [mailgun/mailgun-php#400]
I tried to add recipient variables but it is not working. I tried in this way 
```
$batchSender->addCustomData('user', [
                    'fullName' => '%recipient.fullName%'
                ]);

// Fetch recipients, and then loop over
foreach (...) {
    $batchSender->addToRecipient(
        $row2['email'],
        [
            'first' => $row2['first_name'],
            'last' => $row2['last_name'],
            'fullName' => $row['fullName']
        ]
    );
}
```
When I used %fullName% in subject it is displaying as it is. I also tried in some other way but all are not working. Can anyone guide me the correct way ?

**Comment by Nyholm** [comment]
Sorry for a late response. For the record:
Here is the code: https://github.com/mailgun/mailgun-php/blob/v2.4.0/src/Mailgun/Messages/MessageBuilder.php#L89

It suggest to use `full_name` .
