### ISSUE TITLE
'Reply-To' header parameter does not work when sending attachments

### ISSUE THREAD

**Issue by DCDiaz** [mailgun/mailgun-php#402]
I am able to get the "addCustomHeader('Reply-To', 'me@mydomain.com')" parameter to work perfectly fine, as long as I'm not sending an attachment.  However, whenever I add an "addAttachment" parameter to the call, the "addCustomHeader('Reply-To', 'me@mydomain.com')" parameter no longer seems to be applied to the message.  Instead, the address defined in my "setFromAddress" parameter is what's used as the "Reply-To"' address, but that's different than what I want to actually use as my "Reply-To" address.  For whatever it's worth, the attachments send perfectly fine, aside from seemingly interfering with the "Reply-To" address parameter.  Is there a solution to this problem?

**Comment by tuancaraballo** [comment]
Hi @DCDiaz do you have any updates on this?

**Comment by umbbberto** [comment]
Hi, no sorry

**Comment by tuancaraballo** [comment]
Thanks everyone!
