### ISSUE TITLE
Incorrect information in doc/attachments.md

### ISSUE THREAD

**Issue by tfrajt** [mailgun/mailgun-php#404]
Hi.

In my opinion there's mistake in example described in file "doc/attachments.md". In section "From file path" it is currently described that "filename" array record Id should be used for readable name of attached file, however in file "/src/Mailgun/Connection/RestClient.php", specifically in method "prepareFile" where processing of attachments is in fact implemented, is "filename" information in this case read out from the array record with id "remoteName".

So, according on above explanation I would suggest to:

-  either change in "doc/attachments.md" line n. "13" from "['filePath'=>'/tmp/foo.jpg', 'filename'=>'test.jpg']" to "['filePath'=>'/tmp/foo.jpg', 'remoteName'=>'test.jpg']" (in my opinion confusing - why it should differ from "in memory" attitude) 
- or in "/src/Mailgun/Connection/RestClient.php" change line n. "301" from "$filename = $filePath['remoteName'];" to "$filename = $filePath['filename'];" (in my opinion better solution).

cheers,
Tomas.

**Comment by DavidGarciaCat** [comment]
Hi @tfrajt 

Please feel free to send a Pull Request and we can review it later.

Cheers,

**Comment by tfrajt** [comment]
Great, I'm going on. Still, what type of correction would you prefer?
T.

**Comment by DavidGarciaCat** [comment]
@Nyholm do you have any preference on this?

**Comment by tfrajt** [comment]
Yes, second one, I already made an pull request with proposed modification. Thanks for guidance. 
T.
