### ISSUE TITLE
Mailgun Bounce API returning only recent 5 results

### ISSUE THREAD

**Issue by jiyanibharat303** [mailgun/mailgun-php#407]
Hello Sir/Mam,
Please help on this, I am trying to fetch the bounced email list,
I have used -
$result = $mgClient->get("$domain/bounces"); 
This is only returning recent 5 bounced emails, I have tried with limit parameter but still get the 5 only.
On documentation it says default is 100 so please let know what is missed.

                  try {
			$mgClient = new Mailgun('Private Key');
		        $domain = "domain";
			$result = $mgClient->get("$domain/bounces");
		    } catch (Exception $e) {
			echo 'Caught exception: ',  $e->getMessage(), "\n";
		    }

stdClass Object
(
    [http_response_body] => stdClass Object
        (
            [total_count] => 5
            [items] => Array

**Comment by Nyholm** [comment]
It returns whatever the server returns
