### ISSUE TITLE
Please release 2.3.5 with domain verification

### ISSUE THREAD

**Issue by slaFFik** [mailgun/mailgun-php#412]
It's in master for months already and is quite handy functionality.

**Comment by Eugst** [comment]
+1

**Comment by rjdavidson** [comment]
👍

**Comment by singhanee** [comment]
Can we have a new release 2.3.5 with all latest changes in master?

**Comment by Nyholm** [comment]
I agree. Lets release a new version. But it has to be 2.4.0 because we introduced some new features.

**Comment by Eugst** [comment]
#416 fixed, could be merged and new release created 🐙

**Comment by Nyholm** [comment]
Great. I've reviewed the diff. We do only miss some changelog before 2.4.0 can be released.

**Comment by DavidGarciaCat** [comment]
@Nyholm do you want to take care of the ChangeLog and the new tag?

**Comment by Nyholm** [comment]
Yes. Doing it now
