### ISSUE TITLE
Code should not be duplicated

### ISSUE THREAD

**Issue by DavidGarciaCat** [mailgun/mailgun-php#416]
To me, these 2 files are duplicated code:
- `src/Mailgun/Model/Domain/CreateResponse.php`
- `src/Mailgun/Model/Domain/VerifyResponse.php`

We should not duplicate code 😄

I would suggest to deprecate `VerifyResponse` unless we really need it, however due it looks duplicated to me. We could - potentially - reuse the `CreateResponse` object or maybe one of them could extend the other one, if we need to keep both files.

@Nyholm @pirogoeth thoughts?

**Comment by Eugst** [comment]
https://github.com/mailgun/mailgun-php/pull/420

**Comment by Nyholm** [comment]
Hm, duplicated code is not necessarily a bad thing. We are talking about domain events here...

It would be super weird to reuse the `CreateResponse` when you are requesting `->verify()`...

Could a Trait be a better solution here? Or maybe create a `BaseDomainResponse`? (But maybe better naming)

**Comment by DavidGarciaCat** [comment]
Hey @Nyholm 

> Hm, duplicated code is not necessarily a bad thing. We are talking about domain events here...
>
> It would be super weird to reuse the `CreateResponse` when you are requesting `->verify()`...

I agree, reuse `Create` when we need to `Verify` looks wrong, but keep 2 files with the same code inside means:

- we are increasing the maintenance cost due any potential update will need to be applied twice
- and at the same time we might need to release 2 new updates in case we don't pay enough attention to the update

Also, one of the benefits to reuse code is that we can deal with the requirements and develop just once (so we return to my previous points).

> Could a Trait be a better solution here? Or maybe create a `BaseDomainResponse`? (But maybe better naming)

In fact, I don't think a `BaseDomainResponse` is maybe the best approach here, because we have the same code for `Create` and `Verify` but not for all other responses, so "by definition" is not a "Base Response" because they are not going to return the same content or format.

On the other hand, move this code to be a `Trait` sounds better to me.

@Eugst are you feeling comfortable updating the code to be a `Trait`?

**Comment by Eugst** [comment]
Hm...now I'm a bit confused...
`Create` and `Verify` are final classes. So I hope it was a reason for it?
`Trait` will bring an opportunity to extend functionality... more and more...
I'm more supportive for abstract class `BaseResponse`, but @DavidGarciaCat made a good point that it will be not `abstract` for all `Responses`
one more point from my side: Verbs in Class names, why?..

**Comment by DavidGarciaCat** [comment]
Hey @Eugst 

--

> `Create` and `Verify` are final classes. So I hope it was a reason for it?

Given the API has an endpoint for these actions then the response we get won't change. That's the most important reason to make them `final`.

Also, there's no sense on extend them due any potential change could break the current behaviour as well as include changes that are not managed by the SDK.

We believe is better to send a PR with a new suggestion - as far as it can be used by everybody and not just for a single case. The SDK must be useful for everybody.

> `Trait` will bring an opportunity to extend functionality... more and more...

If you mean `functionality... more and more...` could be a potential problem, then please refer to my previous point.

Also, given the `Response` classes are final and the `Trait` will be part of the SDK then we won't have a problem, because even if I extend the Trait it won't be called by the SDK because the one from the SDK will be called.

If you think `Trait` should be avoided in favour of an `abstract class BaseResponse`, please refer to my next comment.

> I'm more supportive for abstract class `BaseResponse`, but @DavidGarciaCat made a good point that it will be not `abstract` for all `Responses`

And that's the point. It won't be an abstract object to be used neither by all Domain responses (`BaseDomainResponse`) nor by all responses (`BaseResponse`) across the whole SDK. That's my point to say that a `BaseResponse` or a `BaseDomainResponse` might be useless here, but I am open to consider it as a potential update if we cannot find a more suitable solution.

> one more point from my side: Verbs in Class names, why?.. 

Do you mean `Create` or `Verify`? These are defined by the API, the SDK tries to match with the API as much as possible.

--

Please let me know your thoughts, I really want to make this easy to maintain and I think this is a good opportunity to avoid more problems in the future.

Cheers,

**Comment by DavidGarciaCat** [comment]
I have been thinking... Given these 2 files have the same code:

- `src/Mailgun/Model/Domain/CreateResponse.php`
- `src/Mailgun/Model/Domain/VerifyResponse.php`

Then we could add a new one, like:

- `src/Mailgun/Model/Domain/AbstractDomainResponse.php`

That will be

```php
abstract class AbstractDomainResponse
{
    // And it will have the same content we currently have on the other 2 files
}
```

Please note **this is not** a `BaseDomain` response, this is just a `Domain` response

So then, we can keep the 2 existing files, extending the new abstract class, so:

```php
// src/Mailgun/Model/Domain/CreateResponse.php
final class CreateResponse extends AbstractDomainResponse
{
}

// src/Mailgun/Model/Domain/VerifyResponse.php
final class VerifyResponse extends AbstractDomainResponse
{
}
```

Due the content is the same then there is no need to add content here, and - in this way - we can keep both responses, as discussed, to make sure we don't mix a `CreateResponse` when we run a `Verify` action.

Thoughts?

**Comment by Eugst** [comment]
@DavidGarciaCat 
abstract class, that's what I meant 👍 
And name also good for me.
If everybody agree,  I will make changes in PR

**Comment by Eugst** [comment]
just.. one addition... Abstract*Domain*Response.... in Domain namespace... tautology?

**Comment by DavidGarciaCat** [comment]
It was just to be "crystal clear" that it's not a "Base" response

**Comment by Nyholm** [comment]
Great! Lets introduce that abstract class

**Comment by Eugst** [comment]
updated, builders build and check

**Comment by DavidGarciaCat** [comment]
PR looks ok to me, and @Nyholm approved it too, so merging

Thanks @Eugst for your time on this!
