### ISSUE TITLE
Interfaces names should end with "Interface"

### ISSUE THREAD

**Issue by DavidGarciaCat** [mailgun/mailgun-php#417]
IMHO any `Interface` file should end with `Interface` for better clarity.

We have currently 3 interfaces that are not ending with it:
- `src/Mailgun/Hydrator/Hydrator.php`
- `src/Mailgun/Model/ApiResponse.php`
- `src/Mailgun/Model/PagingProvider.php`

I would suggest to rename them - both files and code - to include `Interface`, then update all those files that are implementing these interfaces to make sure they are matching with the new names.

**Comment by Nyholm** [comment]
Should we close this?

**Comment by DavidGarciaCat** [comment]
Well... as discussed this is more a Symfony standard than PHP standard, so I guess that we can close it
