### ISSUE TITLE
Sending email with integer campaign ID causes exception

### ISSUE THREAD

**Issue by justpusher** [mailgun/mailgun-php#421]
```
InvalidArgumentException: "Invalid resource type: integer" in
/files/vendor/guzzlehttp/psr7/src/functions.php:113  
```

I'm using mailgun version 2.3.4.

`MessageBuilder::addCampaignId` supports integer campain ids, according to phpdoc, but the ids are not being cast to string, but integers are not supported when converting to resources in stream_for.

**Comment by DavidGarciaCat** [comment]
Hello @justpusher 

I can't see - quick look - a specific reference on the API docs to manage `integer` or `string` values, so I guess both should work.

Based on the method that you reported, it should be enough casting the value on this method:
https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Messages/MessageBuilder.php#L367-L381

If you have some time to create a Pull Request, then we can review and merge it. Please don't forget to confirm the PHP Unit tests are up to date too once the update is applied.
