### ISSUE TITLE
Issue: Fatal error handle

### ISSUE THREAD

**Issue by bradyuen** [mailgun/mailgun-php#430]
Is it possible stop Fatal error and just output error message if something goes wrong?
If not it's not really can used mailgun in large shopping website.
Something like if I need to send email to customer when they complete payment. However your API just output Fatal Error when my credit card was expired and forgot to update my card detail or Mailgun server stop response.

**Comment by DavidGarciaCat** [comment]
Hi,

The SDK needs to throw an error when something goes wrong, display a
message is not the best approach. Maybe you just need a message but other
projects may need to stop if they are not able to send a financial report
(just an example).

May I suggest you to add your Mailgun calls inside a `try ... catch ...` so
you can handle the error in the way you want?

Please let me know if it works for you.

Cheers,

**Comment by Nyholm** [comment]
Correction: Since we are not PHP 7 only. "Errors" are never "thrown". "Exceptions" are thrown. 

Throwing exception is the correct way of handling... exceptions.

**Comment by DavidGarciaCat** [comment]
True, wrong word ;-)
