### ISSUE TITLE
Suppression Api

### ISSUE THREAD

**Issue by qpautrat** [mailgun/mailgun-php#431]
Hello,

I'm trying to get a list of unsubscribes by using `Mailgun::suppressions()` method.
Unfortunately as this method uses `$this->httpClient` which is not configured by default (no `Authorization` header and no `base uri`) it causes an error `curl`. 
The only way I found to make it work is to initialize a client guzzle and inject it through `Mailgun::__construct()`:

```php
$guzzleClient = new \GuzzleHttp\Client([
    'base_uri' => 'https://api.mailgun.net',
    'headers' => [
        'Authorization' => 'Basic '.base64_encode(sprintf('%s:%s', 'api', API_KEY))
    ]
]);
$httpClient = new \Http\Adapter\Guzzle6\Client($guzzleClient);
$mailgun = new Mailgun(API_KEY, $httpClient);
```
It seems a little bit too tricky to me.

Another solution would be to implement a new customized `RequestBuilder` to inject in `Mailgun` which is not an elegant idea either.

Do I missed something ?

Thanks for your help.

**Comment by DavidGarciaCat** [comment]
Hey @qpautrat

I just want to confirm that you have been trying to use these calls:

```php
// Create new Mailgin client
$mailgun = Mailgun::create('key-example');

// View all unsubscribes
// 2nd parameter is the number of records to return (optional, default: 100, max: 10000)
$all = $mailgun->suppressions()->unsubscribes()->index('domain');

// View a single unsubscribe
$single = $mailgun->suppressions()->unsubscribes()->show('domain', 'address');
```

If you are running this code, that's the output that you get? I can see the `Unsubscribe` object extends the HTTP Client so all calls should be processed as expected.

**Comment by qpautrat** [comment]
Hey David,

Thank you for your reply.
I completely missed this factory method (which is younger than the code I am working on).
It should do the job. I will confirm that tomorrow.
Thank you for your assistance.

**Comment by qpautrat** [comment]
It works, sorry for the inconvenience.

**Comment by DavidGarciaCat** [comment]
No problem, glad to know it worked
