### ISSUE TITLE
What is new method for Mailgun\Mailgun::get

### ISSUE THREAD

**Issue by scapital** [mailgun/mailgun-php#436]
Hi,

I've noticed what Mailgun\Mailgun::get was marked as deprecated
https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Mailgun.php#L213-L215

What should I use instead of that to have less problem during update?

Thanks!

**Comment by DavidGarciaCat** [comment]
Hi @scapital 

There are new calls for each feature. As described on [Usage](https://github.com/mailgun/mailgun-php#usage) you can call `->messages()` or any other like like `->routes()` or `->suppressions()` or...

Hope this helps,

**Comment by dwjorgeb** [comment]
@DavidGarciaCat I have the same issue, I want to post members to mailing lists, using this API call: https://documentation.mailgun.com/en/latest/api-mailinglists.html#mailing-lists
but there doesn't seem to be calls for mailing lists and ->post() is deprecated.

**Comment by DavidGarciaCat** [comment]
Hi @dwjorgeb 

I think the new calls for the mailing lists have not been pushed yet, so feel free to use the `->post()` call due it will be removed on `v3`, so as far as you're using an `v2` version then you shouldn't have any problem.

Anyway, thanks for pointing it, we can review the list of remaining endpoints to be developed.

Cheers,

**Comment by DavidGarciaCat** [comment]
https://github.com/mailgun/mailgun-php/issues/442

**Comment by samuelgfeller** [comment]
The documentation ist still not up to date? One year later?
https://documentation.mailgun.com/en/latest/api-suppressions.html?highlight=suppressions#view-a-single-bounce

**Comment by DavidGarciaCat** [comment]
Hi @samuelgfeller 

Please refer to this issue https://github.com/mailgun/documentation/issues/274 and our Roadmap https://github.com/mailgun/mailgun-php/issues/442 for further details.

Sorry if this is causing you an inconvenience but this kind of things might take some time when collaborators for each project are not the same.

Thanks for your understanding,

**Comment by samuelgfeller** [comment]
Thank you for the explanation @DavidGarciaCat I can unterstand that.

**Comment by jgy3183** [comment]
Not sure if this is also going to be accounted for in v3 - but the email validator call ref: https://documentation.mailgun.com/en/latest/api-email-validation.html#example also relies on the get function

**Comment by DavidGarciaCat** [comment]
Hi @jgy3183 

Just to summarise:
- The `get` method no longer exists on the SDK v3
- The issue regarding the email validation is an open issue https://github.com/mailgun/mailgun-php/issues/619
- The API docs (still) need to be updated; I started to do that but I didn't finish yet

Cheers,
