### ISSUE TITLE
Guzzle\Http\Exception\CurlException

### ISSUE THREAD

**Issue by feyzprod** [mailgun/mailgun-php#437]
Since yesterday, I am not able to send a mail
exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 60:  [url] https://api.mailgun.net/v3/*******.com/messages' in /var/www/html/ui/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:359

I was using this API url https://api.mailgun.net/v2 I changed it to https://api.mailgun.net/v3

**Comment by feyzprod** [comment]
Fixed my issue by disabling ssl

/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php

$this->mgClient->setDefaultOption('verify', false);

**Comment by izazueta** [comment]
Same issue here

**Comment by DavidGarciaCat** [comment]
Hi all,

If it was working fine until yesterday and you have not updated your vendors then it looks like a downtime on Mailgun API, not related with the SDK.

Given your comment regarding the SSL verification, it looks like there was a problem with the SSL connection.

Closing this issue for now due, unless we get more details, looks like is not related with the SDK.

Cheers,

**Comment by izazueta** [comment]
Our legacy application uses the version 1.7 of this package, in my case, updating the certificate bundled in the Guzzle resources directory fix the issue.

See here: https://twitter.com/joshcarcione/status/955926129893888000

**Comment by DavidGarciaCat** [comment]
Hello @izazueta

Thanks for sharing your fix.

Cheers
