### ISSUE TITLE
Sending ics calendar invite

### ISSUE THREAD

**Issue by mayurika** [mailgun/mailgun-php#445]
How to send an email Ics calendar invite with mailgun and PHP? Any example code ?

I found this --https://gist.github.com/travelton/7680617.

Is there any alternative ?

**Comment by DavidGarciaCat** [comment]
Hi @mayurika 

You can choose whatever you want to create your `*.ics` files, no matter if you write them as plain text or if you want to use another vendor to generate them through their own methods.

In the end an `ics` file is just a file, so you just need to attach it to the email. I wrote this example about half a month ago: https://github.com/mailgun/mailgun-php/issues/429#issuecomment-358316771

Closing this issue due this is not an error related with Mailgun PHP SDK, and the way to proceed was already answered on another issue.

Cheers,
