### ISSUE TITLE
 'Error (4) when trying to json_decode response'

### ISSUE THREAD

**Issue by elshanakberov** [mailgun/mailgun-php#446]
I'm trying to use Mailgun API from localhost. at the beginning it threw a lot of errors related to SSL Cert. Somehow i managed to solve them. I changed some configuration in php.ini. I enabled` mod_sll` and `php_openssl.dll`  And i inserted these lines to php.ini 
```
curl.cainfo="C:/xampp/cacert.pem"
openssl.cafile="C:/xampp/cacert.pem" 
```
After all these i got rid of all the SSL Cert Error. But now it threw me `json_decode` error response. Anybody have ever faced with that kind of problem?

**Comment by elshanakberov** [comment]
Mail Class that i'm working on

```
class Mail
{

    /**
     * Send a message
     *
     * @param string $to Receipt
     * @param string $subject Subject
     * @param string $text Text-only content of the message
     * @param string $html HTML content of message
    */

    public static function send($to,$subject,$text,$html = null){

        $mg = Mailgun::create(Config::SECRET_KEY);

        # Now, compose and send your message.
        # $mg->messages()->send($domain, $params);
        $mg->messages()->send(config::MAILGUN_DOMAIN, [
            "from"    => "eakberov14@gmail.com",
            "to"      => $to,
            "subject" => $subject,
            "text"    => $text
        ]);


    }

}
```

**Comment by DavidGarciaCat** [comment]
Hi @elshanakberov

That call to send the email through Mailgun makes sense, so:
1. Did you install all `composer` packages?
2. What is the error thrown?
3. Please note the `$html` variable is useless due you don't include it in your call

Cheers,

**Comment by DavidGarciaCat** [comment]
Is `Error (4) when trying to json_decode respons` the error thrown? What exception is throwing it?

**Comment by dbk91** [comment]
I had a similar issue. My development environment was working but my production was broken. I found the `Error (4) when trying to json_decode response` was being thrown in [here](https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Hydrator/ModelHydrator.php#L39). After a long time of trying to debug, I found out that I had put the full API domain instead of just the domain itself (silly mistake). Either way, if you print out the body, you can see what the Mailgun servers are returning. Usually it's something like `Magnificent Mailgun API` or `Forbidden` if your credentials aren't correct. Hope this helps find your issue.

**Comment by schoolvillephilip** [comment]
I had the same issue, but got it fixed by using just the domain name.

**Comment by musaib-technyx** [comment]
i have same issue. return this error 

>Mailgun\Exception\HydrationException: Error (4) when trying to json_decode response

**Comment by DavidGarciaCat** [comment]
Hey @musaib-technyx 

Would you mind please providing the code that you're using?

Can you also check if your Mailgun domain and the API key are matching?

Finally, did you give them your card details, even if you're not reaching the 10k threshold?

Thanks,

**Comment by Orange-Men** [comment]
@DavidGarciaCat Hi
The same issue
1.
```
$mg = Mailgun::create('MY-SANDBOX-API-KEY');

$mg->messages()->send('MY-SANDBOX-API-BASE-URL', [
    'from'    => 'postmaster@sandboxKEY-FROM-URL.mailgun.org',
    'to'      => 'MY-EMAIL',
    'subject' => 'Hello',
    'text'    => 'Testing some Mailgun awesomness!'
]);
```
2. Mailgun domain and the API key are matching 100%
3. Yes, I've give them card details.

**Comment by Orange-Men** [comment]
Jesus Christ, in the domain need:
sandbox-KEY-.mailgun.org
instead
https://api.mailgun.net/v3/sandbox-KEY-.mailgun.org
