### ISSUE TITLE
how to resolve ssl certificate problem while working with localhost 

### ISSUE THREAD

**Issue by mrfuad2007** [mailgun/mailgun-php#447]
Http\Client\Exception\RequestException: SSL certificate problem: unable to get local issuer certificate in G:\wamp\www\mailgun1\vendor\php-http\curl-client\src\Client.php on line 136

this is my api file code 

# Include the Autoloader (see "Libraries" for install instructions)
require 'vendor/autoload.php';
use Mailgun\Mailgun;

$mgClient = new Mailgun('pubkey-asdfadsfadsfadsfadsfadsfadsf');

$validateAddress = 'exampleemail@gmail.com';

# Issue the call to the client.
$result = $mgClient->get("address/validate", array('address' => $validateAddress));
# is_valid is 0 or 1
$isValid = $result->http_response_body->is_valid;

**Comment by mrfuad2007** [comment]
i had seen one possible solution for this would be 
https://github.com/mailgun/mailgun-php/issues/130

$client = new \GuzzleHttp\Client([
    'verify' => false,
]);
$adapter = new \Http\Adapter\Guzzle6\Client($client);
$mailgun = new \Mailgun\Mailgun($mailgunApiKey, $adapter);

but it says guzzle class not found

**Comment by mrfuad2007** [comment]
@Nyholm  can you please help?

**Comment by vinayakumarnk** [comment]
I changed variable   $ssl=true  to  **$ssl=false** in Mailgun.php file and **It worked for me**.

    public function __construct($apiKey = null, $apiEndpoint = "api.mailgun.net", $apiVersion = "v2", **$ssl = false**){
        $this->apiKey = $apiKey;
        $this->restClient = new RestClient($apiKey, $apiEndpoint, $apiVersion, $ssl);
    }

**Comment by Nyholm** [comment]
Sorry for the super late response. 
The code you provided is correct. You need to configure your HTTP client. It has nothing to do with this library.
