### ISSUE TITLE
Adding custom header - add a non-array value

### ISSUE THREAD

**Issue by mayurika** [mailgun/mailgun-php#449]
`function addCustomHeader($headerName, $headerData)
>     {
>         if (!preg_match("/^h:/i", $headerName)) {
>             $headerName = "h:" . $headerName;
>         }
>         $this->message[$headerName] = array($headerData);
> 
>         return $this->message[$headerName];
>   }`

Why isn't it just:
`$this->message[$headerName] = $headerData;`

Because right now I get weird headers like this:

`["Return-Path[0]", "2121293085+mayurika.parmar=xxxxx.com"]`

When I call it like this:

`$thing->addCustomHeader('h:Return-Path', '2121293085+mayurika.parmar=xxxxx.com');`

**Comment by DavidGarciaCat** [comment]
We cannot assume that all developers will add the expected `h:` header prefix so the method must check if you have added it or not before to set the new header name with the new value(s).

The check that we perform is not weird and it should not give you unexpected content, due we're just running a regular expression to find out the `h:` prefix.

**Comment by mayurika** [comment]
I think the question is not understood properly.

What we need is header array is created, 
Using $this->message[$headerName] = array($headerData);

Instead it should give 2 options, where in we can either create array of heaeders or just use string value for a header

Present implementation : 
When I set header for return-path it sets the array as 
$this->message['Return-Path'] = array('Return path to be set');

What I want : 
$this->message['Return-Path'] = 'Return path to be set';

So when I read the headers the header is set as 'Return-Path[0]' : Return path to be set, instead of 'Return-path' : 'Return path to be set'

User should have option to set header - set as string or array.

In case you have difficulty in understanding question, please ask before closing.

**Comment by DavidGarciaCat** [comment]
Hey @mayurika 

First things first, I need to ask: are you targeting this file on your example? It's almost impossible to check anything unless you're telling where to find it.

https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Messages/MessageBuilder.php

If so, next question is what version of Mailgun SDK are you using? Looks like the latest version that was released has another content inside that method, not the one that you provided on your first message, so I must assume that you're using an old version that should be updated:

https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Messages/MessageBuilder.php#L246-L263

Even more: if I am not wrong, that piece of code should be flagged as deprecated, due the new SDK provides a new way to deal with the `Message` parameters, included the custom headers:

https://github.com/mailgun/mailgun-php#usage

Just an example with custom headers:

```php
$mg = Mailgun::create('key-example');

$mg->messages()->send(
    'example.com',
    [
        'from'                  => 'bob@example.com',
        'to'                    => 'sally@example.com',
        'subject'               => 'The PHP SDK is awesome!',
        'text'                  => 'It is so simple to send a message.',
        'x:My-Awesome-Header'   => 'MyAwesomeValue',
        'x:My-Awesome-Header-2' => ['MyAwesomeValue2', 'MyAwesomeValue3'],
    ]
);
```

Please let me know if it answers your question.

Cheers,
