### ISSUE TITLE
Case condition does not work

### ISSUE THREAD

**Issue by cpennycuick** [mailgun/mailgun-php#450]
https://github.com/mailgun/mailgun-php/blob/ef3dc6b8bf78b1f760da16b6860c4072c798d286/src/Mailgun/Api/HttpApi.php#L98

Emails returning with a HTTP Status of 413, which I have worked out corresponds to having a too big total attachment size, were not throwing the exception at this condition. The exception that was being thrown was the UnknownErrorException.

My recommended solution is to throw `throw HttpServerException::serverError($statusCode);` as the default instead. Otherwise all that is required is brackets around the condition.

See: https://stackoverflow.com/questions/7801175/conditional-switch-statements-in-php

**Comment by DavidGarciaCat** [comment]
Hi @cpennycuick 

If you have got this error then I can see 2 potential actions here:
1. You can wrap your Mailgun implementation into a `try ... catch ...` so you can manage the unexpected `Exception` thrown by the SDK
2. Please feel free to send a PR adding the missed HTTP Status Code so we can provide the expected response in case something went wrong.

Cheers,

**Comment by DavidGarciaCat** [comment]
Fixed here https://github.com/mailgun/mailgun-php/pull/455
