### ISSUE TITLE
Adding custom header - add a non-array value

### ISSUE THREAD

**Issue by mayurika** [mailgun/mailgun-php#451]
`function addCustomHeader($headerName, $headerData)
{
    if (!preg_match("/^h:/i", $headerName)) {
        $headerName = "h:" . $headerName;
    }
    **$this->message[$headerName] = array($headerData);**
    return $this->message[$headerName];
}`

Why isn't it just:
$this->message[$headerName] = $headerData;

Because right now I get weird headers like this:

["**Return-Path[0]"**, "2121293085+mayurika.parmar=xxxxx.com"]

When I call it like this:

$thing->addCustomHeader('h:Return-Path', '2121293085+mayurika.parmar=xxxxx.com');

----------------------------------------------------------------------------------------------

What we need is header array is created,
Using $this->message[$headerName] = array($headerData);

Instead it should give 2 options, where in we can either create array of heaeders or just use string value for a header

Present implementation :
When I set header for return-path it sets the array as
$this->message['Return-Path'] = array('Return path to be set');

What I want :
$this->message['Return-Path'] = 'Return path to be set';

So when I read the headers the header is set as 'Return-Path[0]' : Return path to be set, instead of 'Return-path' : 'Return path to be set'

User should have option to set header - set as string or array.

**Comment by DavidGarciaCat** [comment]
Duplicated here https://github.com/mailgun/mailgun-php/issues/449

Please let's try to not add duplicated issues, it's just confusing
