### ISSUE TITLE
Upgrading mailgun-php to 2.4.1 No transactional email sends on magento 2.2.2 and 2.2.3

### ISSUE THREAD

**Issue by tanolalano** [mailgun/mailgun-php#452]
I upgraded mailgun-php to version 2.4.1, failing to send transactional emails. I performed the same test on both version 2.2.2 and 2.2.3.
Also I looked in the logs and I can not find any errors.
If I return to version 2.4.0 everything works properly.
Some idea?

**Comment by Nyholm** [comment]
Interesting. I’ll investigate this weekend. 
Thank you for reporting this.

**Comment by tanolalano** [comment]
If it helps i found this in exception log of magento 
`2018-03-02 17:18:53] main.ERROR: Source class "\Nyholm\Psr7\Factory\Stream" for "Nyholm\Psr7\Factory\StreamFactory" generation does not exist. [] []
`
It's the only error and has the same time of a test order

**Comment by NickvdMeij** [comment]
@Nyholm This seems to be quite a problem. I'm encountering the same problem in Magento 2.1.12. I've tried using the following versions of mailgun/mailgun-php:

- 2.3.6
- 2.4.0
- 2.4.1

All throwing the same error as @tanolalano said (`[2018-03-07 15:33:57] main.ERROR: Source class "\Nyholm\Psr7\Factory\Stream" for "Nyholm\Psr7\Factory\StreamFactory" generation does not exist. [] []`).

**Comment by NickvdMeij** [comment]
@Nyholm After a few hours digging, I found the problem. The underlying problem is that you added your package nyholm/psr7 to php-http/discovery version 1.4.0. However, you didn't specify your package in the require section of the composer.json, so your source code is never included resulting in the _correct_ error "Source class does not exist", because it's simply not there. Please see https://github.com/php-http/discovery/issues/105 for further details.

@tanolalano to fix this, add the following require in your composer.json:

```
"php-http/discovery": "1.3.0"
```

when @Nyholm fixed this, you can remove it again.

**Comment by DavidGarciaCat** [comment]
Hi @Nyholm 

If @NickvdMeij is right, then I guess that [this PR](https://github.com/Nyholm/psr7/pull/28) should fix the issue that we have here.

Cheers,

**Comment by NickvdMeij** [comment]
@DavidGarciaCat no it would not. php-http/discovery needs to require nyholm/psr7, not the other way around.

**Comment by Nyholm** [comment]
Im closing this issue since it is a problem with Magento and not this library. 

Im also sorry that Magento refused to acknowledge the problem.

**Comment by tanolalano** [comment]
There is a way to use with magento 2.2.6, I'm struggle with this issue?
The only version that works i 2.4.0

**Comment by DavidGarciaCat** [comment]
Hi @tanolalano 

Given the Mailgun SDK is working when we run test projects and this is an issue that appears when using Magento, then the Magento integration should fix the problem.

Unfortunately, we can't maintain every single project that might be using this SDK, so you can try to suggest a new update on Magento-Mailgun integration, or maybe you can build the bug fix yourself and send a PR.

Hope this makes sense.

Best,

**Comment by tanolalano** [comment]
Thanks @DavidGarciaCat for your response, but I'm not a developer.
[I send a pr](https://github.com/andelux/mailgun-magento2/pull/6/commits/8cef128afcafadaac9e5fed238385f63dd398938) hoping is the right way.
