### ISSUE TITLE
Aggregates stats of tag

### ISSUE THREAD

**Issue by benjamin-dancecloud** [mailgun/mailgun-php#453]
I was just removing the references of the deprecated get method and couldn't figure out how to get the aggregated device and country stats of a tag. Can anyone help?

**Comment by DavidGarciaCat** [comment]
Hi @benjamin-dancecloud 

I think that, given there were no tables with the provided data for these API endpoints on the official [Mailgun API Docs](https://documentation.mailgun.com/en/latest/api-tags.html#tags) then we didn't cover it for the current release.

Anyway, I must say that this is - obviously - something that we should provide with the new SDK - given the API docs are providing these API endpoints - and should be included as part of the [Roadmap to v3](https://github.com/mailgun/mailgun-php/issues/442), so I will add them now.

Many thanks for pointing it, we will try to keep you posted about any update related with this issue.

Best regards,

**Comment by DavidGarciaCat** [comment]
Hey @benjamin-dancecloud 

Can you please confirm that the returned data for the `country`, `provider` and `device` stats is matching with the content displayed on Mailgun API Docs examples?

https://documentation.mailgun.com/en/latest/api-tags.html#examples

Sorry to ask for this confirmation, but I don't use tags on my sendings, so I just want to make sure everything is matching before we return wrong data.

Thanks,

**Comment by benjamin-dancecloud** [comment]
I am currently not in office but as far as I can remember they are the same. I will look it up tomorrow and post some sample outputs if you want

**Comment by DavidGarciaCat** [comment]
👍 That would be really helpful, indeed.

Thanks for pointing out this missed implementation, and thanks for the examples that you can give us tomorrow.

Cheers!

**Comment by DavidGarciaCat** [comment]
Hi @benjamin-dancecloud 

Excellent, thanks for the Gist! Let's see if this update can be developed soon.

Please don't remove this Gist for now, might need to be checked while the new feature is developed.

Enjoy the rest of your day!
