### ISSUE TITLE
Add Mailing Lists support

### ISSUE THREAD

**Issue by Etmolf** [mailgun/mailgun-php#456]
So i'am seeing 
`stats()` 
`domains()` 
`tags()` 
`events()` 
`routes()` 
`webhooks()`

and so on.

What about `lists()` ? so we can easily interact with the Mailing Lists API
Is this alsready on the roadmap or can/should i create a PR for this?

Shouldn't be too hard to implement as the underlying infrastructure for these "Api" classes already exists.

**Comment by DavidGarciaCat** [comment]
Duplicated issue, it was included here https://github.com/mailgun/mailgun-php/issues/442

**Comment by MACscr** [comment]
Im confused. If this is the official SDK, why isnt it keeping up with the API capabilities? Frustrating that there is no mailing list support. =(

**Comment by DavidGarciaCat** [comment]
Hi @MACscr 

This SDK is maintained by collaborators and contributors, and we work on this when we have some time.

You can send a pull request if you want to expedite a new feature, such the new calls for the mailing lists. In the meantime, we didn't remove the old methods so you could use them to make calls and manage your lists; we will remove the old methods once the v3 is released.

Hope this makes sense.

Cheers,
