### ISSUE TITLE
Create IP Api

### ISSUE THREAD

**Issue by Etmolf** [mailgun/mailgun-php#458]
If I look at the current roadmap for v3, this part of the Api seems to be missing too.

There are probably not many use cases where you need it, but to be feature complete at least.
I could do that as soon as the mailing lists are done.

I would then create another pull request if no one has any objections :)

**Comment by DavidGarciaCat** [comment]
IPs was already added to the `Roadmap to v3` here https://github.com/mailgun/mailgun-php/issues/442
