### ISSUE TITLE
Update Assets to validate the limits when available on endpoints

### ISSUE THREAD

**Issue by DavidGarciaCat** [mailgun/mailgun-php#461]
As per a ticket that I opened with Mailgun team, these are the limits:
- Domains => 1000
- Events => 300
- Stats => None
- Tags => 1000
- Suppressions => 10000
- Routes => 1000
- Mailing Lists => 100

**Comment by DavidGarciaCat** [comment]
@Nyholm do you think that we should add this, or allow the API itself to return the error message when needed? I guess that makes sense not to block the potential call if the API changes their limits, so this might be useless or even a blocker. Thoughts?

**Comment by Nyholm** [comment]
Yeah, sure lets add these

**Comment by DavidGarciaCat** [comment]
Makes sense adding these `Assert`? Should we risk ourselves to limit the user if the API changes the limits to allow more? Or less?

**Comment by Nyholm** [comment]
Let's try. 
If we add them now, we can remove them without any issues. 
It is harder to add them later.

**Comment by DavidGarciaCat** [comment]
👍 I can add them
