### ISSUE TITLE
Mailgun\Connection\Exceptions\InvalidCredentials: Your credentials are incorrect

### ISSUE THREAD

**Issue by matteocollina** [mailgun/mailgun-php#464]
Hi, i have a problem in sending emails on production with Mailgun (PHP Sdk).
On localhost it works with sandbox url but not not in production.
- the key is valid
- my domain is: mydomain.app 
- in "from" field i have "xxx@mydomain.app"

My code moves to "catch".
Sandbox has the same API key of production so where's the problem? 
Tnx

```php
try {
            $apiKey = "mykey";
            $mg = new Mailgun($apiKey);
            $domain = "mydomain.app";

            $fields = array(
                'from' => 'MySite <info@mydomain.app>',
                'to' => 'User <user@gmail.com>',
                'subject' => 'Try sending email',
            );

            $result = $mg->sendMessage($domain, $fields);
            if ($result->http_response_code == 200) {
                var_dump("Result: " . $result->http_response_code . "<p>");
            } else {
                var_dump("Error sending email<br>");
            }
            return $result;
        } catch (Exception $e) {
            var_dump("Error occured: " . $e . "<br>");
        }
```

**Comment by DavidGarciaCat** [comment]
Hi @matteocollina 

As per a quick check on all DNS records for `mydomain.app` looks like you have not set-up the TXT records that Mailgun suggests to authorise the email sending (adding the SPF sules to include Mailgun servers). I suggest you to review your settings on your Mailgun account and update your domain as per the suggested configuration.

Having said that, please bear in mind that the `Mailgin` constructor in the way you're calling it is no longer recommended, I encourage you to follow the steps we describe on the README file here:

https://github.com/mailgun/mailgun-php#usage

Hope it helps,

**Comment by matteocollina** [comment]
@DavidGarciaCat I found the solution here : https://github.com/mailgun/mailgun-php/issues/454
The IP whitelist gave me an error "Mailgun\Connection\Exceptions\InvalidCredentials: Your credentials are incorrect"

**Comment by daveozoalor** [comment]
In my case, I used Borgado mailgun package for laravel. 
In my .env file I only listed MAILGUN_SECRET , but according to the package, it is supposed to be MAILGUN_PRIVATE 

So I set both of them, 
MAILGUN_SECRET = {my mailgun secret api key}
MAILGUN_PRIVATE = {my mailgun secret api key}
MAILGUN_PUBLIC= {my mailgun public api key}

make sure config/mailgun.php file exists 

If it doesn't, go back to the borgado documentation and follow the instruction to publish the file.
