### ISSUE TITLE
How can i add preview text (preheader text)? 

### ISSUE THREAD

**Issue by bgdomainer** [mailgun/mailgun-php#465]
Do you have a specific method in the API or i have to create a custom HTML. If i have to add a custom HTML do you have a doc with best practices?

**Comment by DavidGarciaCat** [comment]
Hi @bgdomainer 

I don't think the API has a "preview" endpoint and this SDK is managing the API endpoints but not including code that is not related.

On the other hand, please bear in mind that preheader might change depending on the font size as well as the mail client / web mail client that your recipient is using, usually this can be managed through the settings page / window on each mail client.

Best,
