### ISSUE TITLE
Don't bother with Mailgun's convoluted library setup. Use PHP CURL directly instead. 

### ISSUE THREAD

**Issue by ffjabre** [mailgun/mailgun-php#468]
-----------------------------------------------------------------------------
We spent hours on Mailgun's inconsistent documentation for PHP with multiple steps to get proper libraries in place. God forbid you install Composer as root and all hell breaks loose. Don't make the same mistake we did if you've had any trouble using Mailgun's convoluted PHP library setup and install. Just use CURL directly. As seen in the code below:
------------------------------------------------------------------------------
$api_key="your api key";/* Api Key got from https://mailgun.com/cp/my_account */
$domain ="mydomain.com";/* Domain Name you given to Mailgun */
$ch = curl_init();
curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
curl_setopt($ch, CURLOPT_USERPWD, 'api:'.$api_key);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
curl_setopt($ch, CURLOPT_URL, 'https://api.mailgun.net/v3/'.$domain.'/messages');
curl_setopt($ch, CURLOPT_POSTFIELDS, array(
'from' => 'Open <contact@mydomain.com>',
'to' => $email,
'subject' => 'Patient questionnaire result',
'html' => ''
));
$result = curl_exec($ch);
curl_close($ch);
return $result;

**Comment by Nyholm** [comment]
I’m sorry you had a hard time using this library. I can understand it is tricky if you don’t know composer. 

Even if you don’t like it, learning to use composer may save you “hours of work” achieving simple tasks in the future. 

I’m closing this since it is not really an issue.
