### ISSUE TITLE
Limit in get bounces

### ISSUE THREAD

**Issue by dimkalinux** [mailgun/mailgun-php#47]
If limit is over 1000 i got error http://thecode.punbb.org.ua/get/raw:9S6F3qsTIkwlYn/lq4oivjll3.php

code
$mgClient = new Mailgun($config->mailgun->key);
$domain   = $config->mailgun->domain;
$result = $mgClient->get("$domain/bounces", array('skip' => 0, 'limit' => 2000));

PHP 5.3.23 (cli) (built: Mar 18 2013 21:54:26)
"mailgun/mailgun-php": "v1.7.1"

If i made request use desktop rest-client - all working fine.

**Comment by Nyholm** [comment]
Is this still an issue in the latest version? When reading the code I can not see that the *client* limits you. But the API might... 

Can this be closed?

**Comment by NolanMG** [comment]
This can be closed. Version 2 of our Bounce API only allowed a maximum limit of 300 addresses. Verison 3 of the Suppression API (https://documentation.mailgun.com/api-suppressions.html#view-all-bounces) allows for 10,000. 

Currently, mailgun-php calls version 2 and will error if the limit is set over 300. Quoting Sergey on pull request #129 "Some endpoints still support only v2 and not v3 e.g. /v2/<domain name>/bounces. To change the version you can always do. 

`
$mg = new Mailgun('key-example', null, 'bin.mailgun.net');
$mg->setApiVersion('v3');
`

**Comment by Nyholm** [comment]
Thank you for the response @NolanMG. 

I've added #258 to make sure we support the suppressions API in the next version of the API client.
