### ISSUE TITLE
Adding attachments when sending via API?

### ISSUE THREAD

**Issue by GazCBG** [mailgun/mailgun-php#470]
Hi,

So I have read the docs about attachment and not  sure how to add multi attachments

It says
`'attachment' => [    ['filePath'=>'/tmp/foo.jpg', 'filename'=>'test.jpg']   ]`

So do I just repeat for each attachment added?

Thanks,
Gaz

**Comment by DavidGarciaCat** [comment]
Please check the answer here: https://github.com/mailgun/mailgun-php/issues/429#issuecomment-358316771

Closing this issue as duplicated due it was discussed on another issue how to send multiple files
