### ISSUE TITLE
Drop PHP 5 support

### ISSUE THREAD

**Issue by Nyholm** [mailgun/mailgun-php#475]
We should update our minimum PHP version to 7.1

**Comment by Nyholm** [comment]
Hehe, we should also drop PHP 5 support. 

(I made a typo)

**Comment by DavidGarciaCat** [comment]
Makes sense to me, PHP 5.5 is no longer provided by default by most important distros, instead PHP 7.0 is the minimum version that we can find nowadays.

Maybe this can be the final step before to release v3.0.0, to make sure that BC won't be a problem?
