### ISSUE TITLE
Web Hook models are deprecated

### ISSUE THREAD

**Issue by Maxeee09** [mailgun/mailgun-php#482]
Hi !

I recently read the [web hook](https://documentation.mailgun.com/en/latest/api-webhooks.html#webhooks) part of the official php documention and I think Web Hook models are deprecated (supported web hook ids are now: `clicked`, `complained`, `delivered`, `opened`, `permanent_fail`, `temporary_fail`, `unsubscribed`). 

Is the refactoring planned in your roadmap ?

**Comment by DavidGarciaCat** [comment]
Hey @Maxeee09 

Web Hooks should be ready based on the new code for this SDK.

You can follow `Roadmap to v3` here: https://github.com/mailgun/mailgun-php/issues/442

Cheers,
