### ISSUE TITLE
messages() html parameter isn't working since updating to 2.6

### ISSUE THREAD

**Issue by nickmblain** [mailgun/mailgun-php#483]
Can someone please tell me why I can't add the html param like so to the messages()->send() function?

`'html'    => $this->buildHTML($params)`

I really need to get this working because the version that does work using sendMessage() is going to be deprecated at v3.0.

Thank you in advance.

**Comment by DavidGarciaCat** [comment]
Hey @nickmblain 

I don't think `$this->buildHTML(...)` is part of the source code, isn't it?

As per the API docs here: https://documentation.mailgun.com/en/latest/api-sending.html#sending
* `text` Body of the message. (text version)
* `html` Body of the message. (HTML version)

This SDK is not taking actions on behalf of you, so as per the example code on the `README` file:

```php
# First, instantiate the SDK with your API credentials
$mg = Mailgun::create('key-example');

# Now, compose and send your message.
# $mg->messages()->send($domain, $params);
$mg->messages()->send('example.com', [
  'from'    => 'bob@example.com',
  'to'      => 'sally@example.com',
  'subject' => 'The PHP SDK is awesome!',
  'text'    => 'It is so simple to send a message.'
]);
```
...all what you need is to include the `html` tag with their content:
```php
# First, instantiate the SDK with your API credentials
$mg = Mailgun::create('key-example');

# Now, compose and send your message.
# $mg->messages()->send($domain, $params);
$mg->messages()->send('example.com', [
  'from'    => 'bob@example.com',
  'to'      => 'sally@example.com',
  'subject' => 'The PHP SDK is awesome!',
  'text'    => 'It is so simple to send a message.',
  'html'    => '<b>Even HTML tags</b> are allowed to be used!'
]);
```

If you think there is a problem with the SDK, do you mind to provide an example that can be analysed please?

Best,

**Comment by nickmblain** [comment]
@DavidGarciaCat thank you very much for the reply. What you have suggested above is actually what I have been trying. I'm wondering if I need to set the mime type before or maybe the string that is returned from my buildHTML function is too long. Would you mind taking a look at my gist to see if you can spot what I am doing wrong?

[https://gist.github.com/nickmblain/f4c88f768ab70ab12dc883e387575916](url)

**Comment by nickmblain** [comment]
Thank you for the great reply. I just figured out that something is wrong in my buildHTML function because when I hardcode some simple html into the html param the email will send just fine. So, I thank you for your time.

**Comment by Yinxing-Gao** [comment]
Hi dear.
Did you solve this issues? And help me.
I can see the html code in mail. 
For example, if I add the code like this:
"<a href="http:/strategypoint.co"> 
      <img src="http:/app.strategypoint.co/small.png" /> 
</a>"  
I can see that code in mail. How I can do that?
