### ISSUE TITLE
How to create new domain in EU region through API?

### ISSUE THREAD

**Issue by dannevang** [mailgun/mailgun-php#484]
I'm lacking documentation for how to create a new domain in the EU region through the API. 

I have been trying to use a similar approach to how I send emails, but without any luck:

```
		# Instantiate the client.
		$configurator = new HttpClientConfigurator();
		$configurator->setEndpoint('https://api.eu.mailgun.net/v3/'.$domain.'/domains');
		$configurator->setDebug(true);
		$configurator->setApiKey($this->apiKey);
		$mailgun = Mailgun::configure($configurator);

		try {
			$result = $mailgun->domains()->create($newDomain);

			return 'Result: ' . $result;
		} catch (Exception $e) {
			return $e->getMessage();
		}
```

**Comment by umbbberto** [comment]
This is run for me:

`
require 'vendor/autoload.php';
use Mailgun\HttpClientConfigurator;
use Mailgun\Mailgun;
$domain = "my_mailgun_domain";
$key = "my_private_key";

$configurator = new HttpClientConfigurator();
$configurator->setEndpoint('https://api.eu.mailgun.net/v3/'.$domain.'/messages');
$configurator->setDebug(true);
$configurator->setApiKey($key);
$mailgun = Mailgun::configure($configurator);

$result = $mailgun->sendMessage("$domain",
  array('from'    => 'postmaster@my_mailgun_domain',
         'to'      => 'a@recipient',
        'subject' => 'Hello',
        'text'    => 'Testing some Mailgun awesomeness!'))
;`

**Comment by dannevang** [comment]
@umbbberto Yes, but that is the messages endpoint. The same doesn't work for the domains endpoint. 

I ended up solving it by using guzzle instead.

**Comment by DavidGarciaCat** [comment]
@dannevang 

Just pass the endpoint as part of the call to create the Mailgun Client:

```php
# This sets US servers
$mg = Mailgun::create('key-example');

# This sets EU servers
$mg = Mailgun::create('key-example', 'https://api.eu.mailgun.net');
```
