### ISSUE TITLE
Remove log messages of not installed packages

### ISSUE THREAD

**Issue by craig77** [mailgun/mailgun-php#488]
Hi,

I did a quick setup using 

php composer.phar require mailgun/mailgun-php php-http/curl-client guzzlehttp/psr7

This all works fine for me.  In the logs though I see loads of notice messages around Nyholm not loading which is correct cause I didn't require it when running the above command.  CommonClassesStrategy.php is including these as part of php-http package so it's trying to load them.

What is the correct approach to removing these dependencies without commenting out the includes manually?

![image](https://user-images.githubusercontent.com/6513424/45813741-5aa5d300-bccb-11e8-9239-5853c830c377.png)

Thanks,

Shaun.

**Comment by DavidGarciaCat** [comment]
@Nyholm Do you know what might be happening here?

**Comment by craig77** [comment]
Hi,

I would really like to have those messages removed from the logs but reluctant to start commenting out code on a production server!

Thanks,

Shaun.

**Comment by craig77** [comment]
Hi @Nyholm 

I appreciate you are a busy man just wondering if you could have a quick look at this before I start commenting out lines of code!

Thanks.

**Comment by Nyholm** [comment]
Sorry for a late repou. 
If you posted this issue on php-http/discovery you would gotten a much quicker reply. 

The `php-http/discovery` package is doing a few `class_exists()` calls. I assume that is why you get this messages.

**Comment by craig77** [comment]
Hi @Nyholm,

Thanks for the reply, I've now posted the question on php-http/discovery so I will update here with their response and hopefully get this closed off.

Thanks,

Shaun.

**Comment by Nyholm** [comment]
Good good.
