### ISSUE TITLE
HydrationException when getting application/octet-stream

### ISSUE THREAD

**Issue by matejbukovsky** [mailgun/mailgun-php#492]
Hello,

I have working configuration on production, but when I try to send email from local development environment I am getting `Mailgun\Exception\HydrationException` with message `Error (4) when trying to json_decode response`.
The content type of response is `application/octet-stream`. After casting body to string it contains `"Mailgun Magnificent API"`. The status code is 200.
In my opinion the Mailgun is restricted to production IP, therefore it returns this. What is common workflow in dev env? Should I just catch it?

**Comment by DavidGarciaCat** [comment]
Hi @matejbukovsky 

Do you mind please to paste an example of the code that you are using?

Cheers,

**Comment by matejbukovsky** [comment]
Hi @DavidGarciaCat Here is the code:

```php
$mailgun = \Mailgun\Mailgun::create($apiKey)
$this->mailgun->messages()->send($this->baseUrl, [
	'from' => 'server@example.com',
	'to' => 'server@example.com',
	'h:Reply-To' => 'user@example.com',
	'subject' => 'Contact form',
	'html' => 'Some text',
]);
```

**Comment by DavidGarciaCat** [comment]
Hi @matejbukovsky

Please make sure that `$this->baseUrl`:
* Is "just" a domain without protocols (like `example.com`)
* Is a domain that you have registered and validated through Mailgun's Dashboard

If that's the case, then can I see please the vendors installed as part of your `composer.json` file?

Cheers,

**Comment by matejbukovsky** [comment]
Dear @DavidGarciaCat that's it. The domains have differed. It would be great if in exception would be some hint for that. Sure, it's my fault...

Do you still want to send composer.json?

**Comment by DavidGarciaCat** [comment]
There is no need to send the composer file if the problem was the domain

:-)

Cheers,
