### ISSUE TITLE
New tag needed for EU endpoint support

### ISSUE THREAD

**Issue by cabdesigns** [mailgun/mailgun-php#497]
Is it possible to get a tagged release? This lib can't be used with the new EU region until [this recent patch](https://github.com/mailgun/mailgun-php/commit/860d49d9d2a0e5f3d5fc26e67986512e2a98b121) is tagged.

For now, I'm directly using dev-master just so I can have something working.

Thanks!

**Comment by DavidGarciaCat** [comment]
Hi @cabdesigns 

We'll do it soon, we would like adding a new feature before to add a new tag. In the meantime, keep `dev-master` is not a blocker to use the new feature.

Hope it makes sense.

Cheers,

**Comment by Nyholm** [comment]
I'll tag 2.7 now.
