### ISSUE TITLE
Add phpstan checks

### ISSUE THREAD

**Issue by Nyholm** [mailgun/mailgun-php#529]
I want to try @oskarstark’s github action: https://github.com/OskarStark/phpstan-ga

What do you think? Should we try to see if phpstan can help us while reviewing PRs?

**Comment by OskarStark** [comment]
Nice 👍 

Let me know when I can support you, but first we need ti find out, if mailgun organization is invited to the beta (and is currently available for "organizations" 🤔 )

**Comment by Nyholm** [comment]
Oh, I thought it was just to make a PR like #530 and it would magically turn up in the PR's "Checks".

**Comment by OskarStark** [comment]
You are right, from this moment, where Github will allow/activate Github Actions for everyone or at least public organization repositories it will work

**Comment by OskarStark** [comment]
As I am using `FROM phpstan/phpstan:0.10` docker image as base, it is not possible to use phpstan extensions.
