### ISSUE TITLE
Documentation Example Broken

### ISSUE THREAD

**Issue by jacobhaug** [mailgun/mailgun-php#568]
So, I copied and pasted the below code exactly from the example referenced in the readme. 
<img width="953" alt="documentation" src="https://user-images.githubusercontent.com/1895442/52515947-841ab900-2bf0-11e9-99ff-826e4d8cfe5c.png">

Composer installed worked fine.
<img width="1078" alt="composer-intall" src="https://user-images.githubusercontent.com/1895442/52515950-a9a7c280-2bf0-11e9-89ac-021787e76d20.png">

**However, when loading the page I get the below fatal error.**

`Fatal error: Uncaught TypeError: Argument 1 passed to Buzz\Client\AbstractClient::__construct() must be of the type array, object given, called in /Users/jacob/Code/qc/vendor/php-http/discovery/src/Strategy/CommonClassesStrategy.php on line 119 and defined in /Users/jacob/Code/qc/vendor/kriswallsmith/buzz/lib/Client/AbstractClient.php:31 Stack trace: #0 /Users/jacob/Code/qc/vendor/php-http/discovery/src/Strategy/CommonClassesStrategy.php(119): Buzz\Client\AbstractClient->__construct(Object(Nyholm\Psr7\Factory\HttplugFactory)) #1 /Users/jacob/Code/qc/vendor/php-http/discovery/src/ClassDiscovery.php(207): Http\Discovery\Strategy\CommonClassesStrategy::buzzInstantiate() #2 /Users/jacob/Code/qc/vendor/php-http/discovery/src/HttpClientDiscovery.php(34): Http\Discovery\ClassDiscovery::instantiateClass(Array) #3 /Users/jacob/Code/qc/vendor/mailgun/mailgun-php/src/Mailgun/HttpClientConfigurator.php(160): Http\Discovery\HttpClientDiscovery::find() #4 /Users/jacob/Code/qc/vendor/mailgun/mailgun-php/src/Mailgun/HttpClientConfigurato in /Users/jacob/Code/qc/vendor/kriswallsmith/buzz/lib/Client/AbstractClient.php on line 31`

**Comment by jacobhaug** [comment]
Just in case you felt this was an issue with PHP, I've tested it with PHP 7.3.1 and PHP 7.2.14.

**Comment by loomsen** [comment]
Same issue here.

**Comment by StoryHack** [comment]
Can verify, I'm getting the same thing.

**Comment by StoryHack** [comment]
I traded emails with mailgun, and it'll work if you install a slightly different set of dependencies. So instead of using:

**composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7**

As it currently states in the docs, instead use:

**composer require mailgun/mailgun-php php-http/curl-client guzzlehttp/psr7**

I just tested using this other set of packages and was able to send an email.

**Comment by DavidGarciaCat** [comment]
This might be related to the fact that `master` branch is now under some (final) changes to release the v3 in the upcoming weeks, however the latest stable tag is still flagging v2.

Can you please review if the error persists when you follow the v2 branch for the install process?

https://github.com/mailgun/mailgun-php/blob/2.x/README.md#usage

Thanks,

**Comment by Nyholm** [comment]
I think you downloaded buzz <1.0. 

Try again with the latest version and you will be fine.
