### ISSUE TITLE
Fatal error: Uncaught TypeError

### ISSUE THREAD

**Issue by samuelgfeller** [mailgun/mailgun-php#569]
I just copied [this](https://documentation.mailgun.com/en/latest/api-sending.html) php api example and I get this error: 
> Fatal error: Uncaught TypeError: Argument 1 passed to Buzz\Client\AbstractClient::__construct() must be of the type array, object given, called in C:\xampp\htdocs\mailtest\vendor\php-http\discovery\src\Strategy\CommonClassesStrategy.php on line 119 and defined in C:\xampp\htdocs\mailtest\vendor\kriswallsmith\buzz\lib\Client\AbstractClient.php on line 31  

I installed mailgunphp with composer with this command found [here](https://github.com/mailgun/mailgun-php): 
**composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7**  
For this purpose I set up a test project which I shared [here](https://github.com/samuelgfeller/mailtest).

**Comment by samuelgfeller** [comment]
Huge thank you to Chris Clark from the mailgun support team which gave me this command because it actually worked perfectly fine. So I think you should maybe update the composer command on mailgun-php?

```cmd
composer require mailgun/mailgun-php php-http/curl-client guzzlehttp/psr7
```

**Comment by DavidGarciaCat** [comment]
Hi @samuelgfeller 

This issue might be related to this other case:

https://github.com/mailgun/mailgun-php/issues/568#issuecomment-462951198

Cheers,

**Comment by Nyholm** [comment]
Use buzz version 1 and you will be fine
