### ISSUE TITLE
How to attach a file without deprecated functions

### ISSUE THREAD

**Issue by samuelgfeller** [mailgun/mailgun-php#572]
In the documentation is an example with the method sendMessage which is deprecated so I don't want to use it. 

I found this function [here](https://github.com/mailgun/mailgun-php/blob/master/doc/attachments.md):
```php
$mg->messages()->send('example.com', [
  'from'    => 'bob@example.com', 
  'to'      => 'sally@example.com', 
  'subject' => 'Test file path attachments', 
  'text'    => 'Test',
  'attachment' => [
    ['filePath'=>'/tmp/foo.jpg', 'filename'=>'test.jpg']
  ]
]);
```
When I tried it I got this error: 
`Uncaught TypeError: Argument 2 passed to Mailgun\Api\Message::prepareFile() must be of the type array`

So I tried to add a `[1]` to `'attachment'` and it didn't throw any error BUT the mail was delivered without the attachment. So it doesn't work.
```php
$mg->messages()->send('example.com', [
  'from'    => 'bob@example.com', 
  'to'      => 'sally@example.com', 
  'subject' => 'Test file path attachments', 
  'text'    => 'Test',
  'attachment[0]' => [
    ['filePath'=>'/tmp/foo.jpg', 'filename'=>'test.jpg']
  ]
]);
```

**Comment by DavidGarciaCat** [comment]
Hi @samuelgfeller 

The helper to send the email with an attached file has this definition:

```php
/**
 * @param array $filePath array('fileContent' => 'content') or array('filePath' => '/foo/bar')
 *
 * @throws InvalidArgumentException
 */
private function prepareFile(string $fieldName, array $filePath): array
```

Can you please confirm that you're providing the content as an array, and the result?

If you're getting an error, then the output with the exception might be useful.

Additionally, can you please check your Mailgun Dashboard and confirm there if there is any reference to the attached file?

Thanks,

**Comment by samuelgfeller** [comment]
Hi @DavidGarciaCat 
Okay I feel dumb now. You are totally right what I actually did was: 
```php
$mg->messages()->send('example.com', [
  'attachment' => [
    'filePath'=>'/tmp/foo.jpg', 'filename'=>'test.jpg'
  ]
]);
```
