### ISSUE TITLE
RequestBuilder allow send parameters in application/json format

### ISSUE THREAD

**Issue by shakaran** [mailgun/mailgun-php#576]
I am doing a customization for a Api client and using parts of Mailgun code in this new project, but I have some problems like I would need pass via POST and format application/json parameters instead of based in multipart/form-data and in php arrays.

Digging in the code of RequestBuilder I see that the psr7 and psr18 [is forcing in some way](https://github.com/mailgun/mailgun-php/blob/master/src/HttpClient/RequestBuilder.php#L75) to use multipart/form-data

In HttpClientConfigurator I am forcing to use always as HeaderDefaultsPlugin the header:

`'Content-Type' => 'application/json',`

In other part, also I am losing the "endpoint" url since you return a PluginClient without that info:

`return new PluginClient($this->getHttpClient(), $plugins);`

        $params = [
            'limit' => (string) $limit,
         // a lot params
        ];
        $endpoint = 'https://api.someurl.com/v1'; // I have to force this, since the setEndPoint() data is loss returning the PluginClient

        $response = $this->httpPost($endpoint . '/register', $params,  ['Content-Type' => 'application/json']);

The idea here, is that RequestBuilder detect the content-type and adapt the $params array to the proper format, in this case not calling to MultipartStreamBuilder to look for generate a boundary and pass the json data in the request. But I don't know how to change that in RequestBuilder to pass that json data, could you help me in this customization?

**Comment by Nyholm** [comment]
The RequestBuilder is pretty much perfect. =)

Try to read up a bit about MultipartStreams and how they work. Example, see here: http://docs.php-http.org/en/latest/components/multipart-stream-builder.html

You can do something like this: 
```php

$this->requestBuilder('GET', 'https://foo.com', ['Content-Type'=>'application/json'], json_encode(['foo'=>'bar']));

// OR using MultipartStream

$this->requestBuilder('GET', 'https://foo.com', [], [
   'content' => json_encode(['foo'=>'bar']),
   'headers' => ['Content-Type'=>'application/json'],
]);

```
