### ISSUE TITLE
Can not get stored email attachment using default hydrator.

### ISSUE THREAD

**Issue by kormik** [mailgun/mailgun-php#577]
It is not possible to get stored email attachment using default ModelHydrator.
I used this:
`$mailgunClient->attachment()->show($url);`
and I got this Exception:
`The ModelHydrator cannot hydrate response with Content-Type: image/jpeg`

Even though there is a model class for attachment it is not possible to hydrate it because the `ModelHydrator` always expect JSON but endpoint for attachments returns actual file content.

**Comment by DavidGarciaCat** [comment]
Hi @kormik 

Can you please provide an example for this case?

Do we just need to send an email with an attached file and then trying to retrieve it, and that's all?

Thanks,

**Comment by kormik** [comment]
I think so. You can test it on stored email with an attachment.
- When you retrieve the email, you will get an url for the attachment.
- When you try to retrieve the attachment using provided url you will get the exception.
Endpoint for attachments looks like:
`https://storage.eu.mailgun.net/v3/domains/<OUR_DOMAIN>/messages/<MESSAGEID>/attachments/0`
Which returns attachment content but ModelHydrator always expects json.

**Comment by DavidGarciaCat** [comment]
Thanks @kormik 

We'll try to take a look and fix it.

If, in the meantime, you want to expedite a potential solution, PRs are more than welcome.

Thanks,
