### ISSUE TITLE
Mailgun compatibility with php version and others

### ISSUE THREAD

**Issue by ambikaAashi** [mailgun/mailgun-php#578]
Please provide link for older version of mail gun compatible with my php version 5.5.9, so that I don't have to update my php version.

**Tried to run this command** 
composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7

**Error I got:'**

[InvalidArgumentException]                                                   
  Package nyholm/psr7 at version  has a PHP requirement incompatible with you  
  r PHP version (5.5.9) 

Thanks

**Comment by tghilardi** [comment]
Bump.

**Comment by Nyholm** [comment]
Oh. 
1) Update your PHP version
2) Really.. Update your PHP version.
3) Check out the [2.x branch](https://github.com/mailgun/mailgun-php/tree/2.x)

=)
