### ISSUE TITLE
Argument 1 passed to Zend\Diactoros\StreamFactory::createStream() must be of the type string, null given

### ISSUE THREAD

**Issue by max-petrovich** [mailgun/mailgun-php#581]
Fatal error: Uncaught TypeError: Argument 1 passed to Zend\Diactoros\StreamFactory::createStream() must be of the type string, null given, called in ../mailgun-php/src/HttpClient/RequestBuilder.php on line 56 and defined in ../vendor/zendframework/zend-diactoros/src/StreamFactory.php:26
Stack trace:
#0 ../mailgun-php/src/HttpClient/RequestBuilder.php(56): Zend\Diactoros\StreamFactory->createStream(NULL)
#1 ../mailgun-php/src/Api/HttpApi.php(114): Mailgun\HttpClient\RequestBuilder->create('GET', '/v3/22/events', Array)
#2 ../mailgun-php/src/Api/Event.php(37): Mailgun\Api\HttpApi->httpGet('/v3/22/events', Array)
#3 ../test.php(10): Mailgun\Api\Event->get('22')
#4 {main}
  thrown in ../vendor/zendframework/zend-diactoros/src/StreamFactory.php on line 26

**Comment by max-petrovich** [comment]
On master branch

**Comment by DavidGarciaCat** [comment]
Hi Max,

Can you please provide the source code used to reproduce the error?

Thanks,

**Comment by Nyholm** [comment]
That is correct. We should type cast RequestBuilder.php(56) to a string.
