### ISSUE TITLE
SDK version in Api constants

### ISSUE THREAD

**Issue by krystalcode** [mailgun/mailgun-php#583]
Could you keep the `Api::SDK_VERSION` constant updated so that we can know in the code which version is being used? It's stuck in `1.7` including on the 2+ versions.

**Comment by Nyholm** [comment]
Could you explain your scenario? Dont you know what version you got installed?

**Comment by krystalcode** [comment]
Hey,
I'm developing a PHP library that uses the SDK and I want to maintain compatibility with previous versions while progressively supporting the new SDK. That means I need to be able to detect which version of the SDK we are using and alter the code accordingly.

**Comment by DavidGarciaCat** [comment]
Isn't this possible by checking the version either on the `composer.json` or the `composer.lock` file that you have in your project?

**Comment by krystalcode** [comment]
So in the PHP code I'd have to load the `composer.lock` file, parse it and detect the version? Doesn't sound like the right solution. Anyways, more likely that I can't implement progressive support of the new SDK and my library will have to wait for a rewrite.

**Comment by Nyholm** [comment]
No, we cannot keep it. Even if we added it back, you cannot trust that constant to exist.
