### ISSUE TITLE
Mailgun class is going "final" is v3 -- how do we mock it then? 

### ISSUE THREAD

**Issue by chdeliens** [mailgun/mailgun-php#584]
Hi everyone,

I noticed that the Mailgun class is now "final" on `master` (change from the latest release 2.8.1) but it's not implementing any interface. I'm just then wondering what's the recommended way to mock Mailgun with PHPUnit (doing so on a final class with PHPUnit reports a warning)? 🤔

[swiftmailer-mailgun-bundle](https://github.com/tehplague/swiftmailer-mailgun-bundle) will have the same issue, since it's mocking the Mailgun\Mailgun class for its tests.

I see two ways out of this issue:

1. Mailgun to expose an interface that developers can mock (cf. [Marco Pivetta's post](https://ocramius.github.io/blog/when-to-declare-classes-final/));
2. Developers to use [dg/bypass-finals](https://github.com/dg/bypass-finals) (further explained in [Tomas Vortruba's post](https://www.tomasvotruba.cz/blog/2019/03/28/how-to-mock-final-classes-in-phpunit/))

Or did I miss something? 😅

Let's discuss this further! 👍

**Comment by Nyholm** [comment]
You are correct. I dont think an interface is a good idea, because then we need to update the interface 
 (BC break) every time mailguin adds a new version. 

Lets drop final.
