### ISSUE TITLE
Getting endpoint issue on Delete and Route with V3

### ISSUE THREAD

**Issue by codoffer** [mailgun/mailgun-php#586]
I am getting an error with Delete Route and Create Route

Error is

The endpoint you have tried to access does not exist. Check if the domain matches the domain you have configure on Mailgun

**Comment by Nyholm** [comment]
Using dev-master works. 

Also, the error message tells us that you are using the wrong domain.

**Comment by codoffer** [comment]
I am not using wrong domain. Its verified domain. It was working fine with old API (V2). Will I have to use latest version of repository or How will I fix this?

**Comment by Nyholm** [comment]
> Check if the domain matches the domain you have configure on Mailgun

This part made me thing you were using the wrong domain. 

> Will I have to use latest version of repository or How will I fix this?

I tried the latest beta and it worked for me.

**Comment by codoffer** [comment]
@Nyholm - Can you help me for this? How can I install latest beta? Its creating lots of issue with my current code. I am not able to create mailing list and getting same issue.

Type: Mailgun\Exception\HttpClientException

Message: The endpoint you have tried to access does not exist. Check if the domain matches the domain you have configure on Mailgun.

Filename: ../third_party/Mailgun/vendor/mailgun/mailgun-php/src/Mailgun/Exception/HttpClientException.php

Line Number: 87

I have tried to pass endpoint with constructor and create function but its not working.

```
Mailgun(KEY, null, 'https://api.mailgun.net/v3/MY_DOMAIN/');
Mailgun::create(KEY, 'https://api.mailgun.net/v3/MY_DOMAIN/');
Mailgun::create(KEY, 'https://api.mailgun.net');
```

**Comment by DavidGarciaCat** [comment]
Hi, @codoffer 

Please check:
- the [installation](https://github.com/mailgun/mailgun-php/blob/master/README.md#installation) section and make sure that you have installed all the required packages; please bear in mind that Mailgun SDK uses HTTPlug so you can change the adapters to use anyone that implements the right version
- the [usage](https://github.com/mailgun/mailgun-php/blob/master/README.md#usage) section to get more details about how to set-up your client

If you don't want to install a released version but the main code into the `master` branch then the best way to do it is setting the `dev-master` version (usually manually into your `composer.json` file):

```js
{
    "require": {
        "mailgun/mailgun-php-sdk": "dev-master"
    }
}
```

And then you'll need to install your dependencies updating this specific package:

```
$ composer update mailgun/mailgun-php-sdk
```

Even with this approach, I would suggest to install the packages through the suggested approach via the `installation` section of the README and then update to the `dev-master` if needed.

As per the `Mailgun`'s Client file, this is the definition of the `create` method:

```php
public static function create(string $apiKey, string $endpoint = 'https://api.mailgun.net')
```

So once you have installed all the packages to run the SDK, you can instantiate your Mailgun Client with the following calls:

```php
// Set your key into a variable or constant
$apiKey = 'key-xxxxxxxxxx';

// US servers
$usMailgun = Mailgun::create($apiKey);

// EU servers
$euMailgun = Mailgun::create($apiKey, 'https://api.eu.mailgun.net');
```

Once the client has been instantiated, you can try your implementation by sending an email to yourself (check the steps on the Usage section). Other calls to each method should be available through the helpers included for each one.

Hope it helps.

Cheers,

**Comment by DavidGarciaCat** [comment]
Please don't forget to check the helpers that your IDE should tell you when calling each method, make sure that all the required arguments are provided as expected. ;-)
