### ISSUE TITLE
Issue with server configuration while sending email

### ISSUE THREAD

**Issue by rohitbhilare3** [mailgun/mailgun-php#587]
result3 = $mgClient->sendMessage("$domain",
array('from' => 'Mailgun Sandbox <postmaster@sandbox09bf542d495e42149d14eb8508259721.mailgun.org>',
'to' => $email,
'subject' => 'Welcome to Soar , Thanks For your Enquiry',
'html'	=> '<html>Email:</html>'));

Giving error on line of to => $email, Error is 
[04-Apr-2019 04:28:50 UTC] PHP Fatal error: Uncaught Mailgun\Connection\Exceptions\MissingRequiredParameters: The parameters passed to the API were invalid. Check your inputs! Sandbox subdomains are for test purposes only. Please add your own domain or add the address to authorized recipients in Account Settings. in /Applications/MAMP/htdocs/soarbyjmm/create-trip/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:254
Stack trace:
#0 /Applications/MAMP/htdocs/soarbyjmm/create-trip/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(110): Mailgun\Connection\RestClient->responseHandler(Object(Nyholm\Psr7\Response))
#1 /Applications/MAMP/htdocs/soarbyjmm/create-trip/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(179): Mailgun\Connection\RestClient->send('POST', 'sandbox09bf542d...', Object(Nyholm\Psr7\Stream), Array)
#2 /Applications/MAMP/htdocs/soarbyjmm/create-trip/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(208): Mailgun\Connection\RestClient->post('sandbox09bf542d...', Array, Array)
#3 /Applications/M in /Applications/MAMP/htdocs/soarbyjmm/create-trip/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php on line 254x

**Comment by Nyholm** [comment]
The error message you get is:
> "The parameters passed to the API were invalid. Check your inputs! "

=)
