### ISSUE TITLE
New release :D

### ISSUE THREAD

**Issue by bobbybouwmann** [mailgun/mailgun-php#588]
Hi,

I was wondering if it's possible to get a new release with all the goodies that were added!

I mostly have problems with the following issue: #510

This seems to be fixed in the master branch, but there is no release yet!

Thanks in advantage!

**Comment by bobbybouwmann** [comment]
@Nyholm I don't really want to spam anyone, but the current `mailgun/mailgun-php` release doesn't work for any of the swiftmailer bundles that work on Symfony 4.2.x. A new release would probably fix this!

**Comment by Nyholm** [comment]
Thank you. 

We were waiting for something. But I think that is fixed now. 

Could you try to dev master and see if it works correctly for you?
```
"mailgun/mailgun-php": "dev-master as 3.0",
```

**Comment by bobbybouwmann** [comment]
@Nyholm Thanks for your quick reply!

It seems that this line is working for me:
```
"mailgun/mailgun-php": "dev-master as 2.9",
```
I'm using the `tehplague/swiftmailer-mailgun-bundle` mailgun bundle that is also recommended by this repository in the readme. The 3.0 didn't seem to work, so I got it working like this. Any default doesn't seem to work right now. 

Let's hope we can do this 3.0 release soon ;) Let me know if I can help in any way!

**Comment by dvdknaap** [comment]
Any update on this issue because the current version is broke

**Comment by Nyholm** [comment]
Please try the [Beta1](https://github.com/mailgun/mailgun-php/tree/3.0.0-beta1). If that verison works perfectly for you then we will be more confident making a new release.

**Comment by dvdknaap** [comment]
@Nyholm When updating to Beta1 i get the following error:
`No PSR-17 url factory found. Install a package from this list: https://packagist.org/providers/psr/http-factory-implementation`

**Comment by kicktraq** [comment]
@dvdknaap Any chance you'd show how your fix is setup in pseudo? I can't get the beta release to behave at all and the current state of the documentation is all over the place.

**Comment by dvdknaap** [comment]
@kicktraq The only thing what i did was installing that plugin and it works
`composer require kriswallsmith/buzz`

**Comment by kicktraq** [comment]
Hrm, I did the same and it's not working. I'll keep poking at it. Thank you for your reply!

**Comment by dvdknaap** [comment]
This repo looks dead to me or isn't it ?

Maybe we can beter move to https://github.com/symfony/mailgun-mailer ?

**Comment by DavidGarciaCat** [comment]
Hi @dvdknaap 

This repo is not dead, there is activity posting issues, getting answers and merging PRs.

Please note that this repo is an SDK for Mailgun, while the Symfony repo is an integration for Symfony Mailer when aiming to send emails, but - as far as I know - it doesn’t provide a full integration with every single API endpoint.

Cheers,

**Comment by Nyholm** [comment]
Correct!

**Comment by dvdknaap** [comment]
@DavidGarciaCat well i'm at the point now that composer comes to the conclusion that it can't install mailgun anymore.
i have to remove this repo and try it with symfony/mailgun-mailer anyway.

**Comment by DavidGarciaCat** [comment]
Hey @dvdknaap 

Why not? What error do you get?

Cheers,

**Comment by DavidGarciaCat** [comment]
Hi all,

Just letting you know that a new tag `3.0.0 Beta 2` has been released.

I'm going to close this issue.

Cheers,

D
