### ISSUE TITLE
Failure to install mailgun

### ISSUE THREAD

**Issue by noxidsoft** [mailgun/mailgun-php#591]
Pulling the command from mailgun website, I can't get the framework installed.

OS: Windows 10
PHP version: 7.2.10

> php composer.phar require mailgun/mailgun-php php-http/guzzle6-adapter php-http/message

Output:
C:\redacted>php composer.phar require mailgun/mailgun-php php-http/guzzle6-adapter php-http/message
Using version ^2.8 for mailgun/mailgun-php
Using version ^2.0 for php-http/guzzle6-adapter
Using version ^1.7 for php-http/message
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1].
    - Can only install one of: php-http/httplug[v2.0.0, v1.0.0].
    - Can only install one of: php-http/httplug[v2.0.0, v1.1.0].
    - Conclusion: don't install php-http/httplug v2.0.0|don't install mailgun/mailgun-php 2.8.1
    - Conclusion: install php-http/httplug v2.0.0
    - mailgun/mailgun-php 2.8.0 requires php-http/client-common ^1.1 -> satisfiable by php-http/client-common[1.3.0, 1.5.0, 1.7.0, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, v1.1.0, v1.2.0, v1.2.1, v1.4.0, v1.4.1, v1.4.2, v1.6.0].
    - php-http/client-common v1.1.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
    - php-http/client-common v1.2.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
    - php-http/client-common v1.2.1 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
    - php-http/client-common 1.3.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common 1.5.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common 1.7.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common 1.8.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common 1.8.1 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common 1.8.2 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common 1.9.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common 1.9.1 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common v1.4.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common v1.4.1 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common v1.4.2 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common v1.6.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - Installation request for mailgun/mailgun-php ^2.8 -> satisfiable by mailgun/mailgun-php[2.8.0, 2.8.1].

Installation failed, deleting ./composer.json.

C:\redacted>

**Comment by noxidsoft** [comment]
> composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7

This command from Github works, nice.

**Comment by DavidGarciaCat** [comment]
Hi @noxidsoft 

Glad to hear that the command on this repo works; the official website is not yet updated.

Have a nice day

**Comment by jasperkuperus** [comment]
Just bumped into this issue. Cost me quite some time since the official website still hasn't been updated. @DavidGarciaCat

**Comment by DavidGarciaCat** [comment]
Hi @jasperkuperus 

There are open issues to update the docs:
- https://github.com/mailgun/mailgun-php/issues/387
- https://github.com/mailgun/documentation/issues/274

Cheers,

**Comment by daveav** [comment]
doesn't work for me. when I run composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7 - 

Using version ^3.0 for mailgun/mailgun-php
Using version ^1.1 for kriswallsmith/buzz
Using version ^1.2 for nyholm/psr7
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Conclusion: don't install php-http/guzzle6-adapter v2.0.1
- Installation request for php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1].
- Conclusion: don't install php-http/curl-client v1.7.1
- php-http/curl-client v1.7.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
- Can only install one of: php-http/httplug[v2.0.0, v1.1.0].
- Can only install one of: php-http/httplug[v2.0.0, v1.0.0].
- php-http/guzzle6-adapter v2.0.0 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[2.1.0, v2.0.0].
- Conclusion: don't install php-http/curl-client v1.7.0|don't install php-http/httplug 2.1.0
- Installation request for php-http/curl-client ^1.7 -> satisfiable by php-http/curl-client[v1.7.0, v1.7.1].
Installation failed, reverting ./composer.json to its original content.

Help!

**Comment by daveav** [comment]
Solved by deleting all previously installed composer / Mailgun packages and starting from scratch.
