### ISSUE TITLE
correct set of packages 

### ISSUE THREAD

**Issue by harvyde** [mailgun/mailgun-php#592]
Can you please help me installing the correct set of packages required for mailgun 2.8 to work.

My composer.json file:
	"require": {
		"mailgun/mailgun-php": "^2.8",
		"guzzlehttp/psr7": "^1.5",
		"guzzlehttp/guzzle": "^6.3"
	},

I tried to install suggested packages, php-http/curl-client

Using version ^2.0 for php-http/curl-client, I've following issues:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: php-http/httplug[v2.0.0, v1.1.0].
    - Can only install one of: php-http/httplug[v2.0.0, v1.1.0].
    - Can only install one of: php-http/httplug[v2.0.0, v1.1.0].
    - php-http/curl-client 2.0.0 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0].
    - Installation request for php-http/curl-client ^2.0 -> satisfiable by php-http/curl-client[2.0.0].
    - Installation request for php-http/httplug (locked at v1.1.0) -> satisfiable by php-http/httplug[v1.1.0].

**Comment by DavidGarciaCat** [comment]
Hi,

Try installing ^1.0 for the HTTPlug, the v2 should be the requirement for the upcoming v3 release for this SDK although it should work too.

Please note that the minimum version of your PHP might be a blocker for newer versions, so as far as you can keep compatibility between the libraries then it should work.

Cheers,

**Comment by harvyde** [comment]
Thanks David,

The conflict is with suggested package php-http/curl-client that requires 
"php-http/httplug": "^2.0",

Whereas mailgun/mailgun-php requires php-http/client-common that requires
"php-http/httplug": "^1.1",

To fix it I had to reduce the version of php-http/curl-client

My composer looks like:
"require": {
		"php-http/curl-client": "^1.7",
		"guzzlehttp/guzzle": "~6.0.0",
		"mailgun/mailgun-php": "^2.5",
		"guzzlehttp/psr7": "^1.4"
	},


**Suggested fix**
php-http/curl-client should be moved to require section instead of suggest
Or please mention the version in suggest section.
 "php-http/curl-client": "cURL client for PHP-HTTP",

Cheers,
harvy

**Comment by DavidGarciaCat** [comment]
Hi @harvyde 

Thanks for sharing your list of packages, we'll try to bear it in mind for the upcoming release.

Cheers,
