### ISSUE TITLE
Error on add member into mailList

### ISSUE THREAD

**Issue by Britskiy** [mailgun/mailgun-php#594]
Hello! Got problem with example in doc: 
```php
        $mgClient = new Mailgun($this->api_key);
        $listAddress = "mylist@testsandbox.com"; //Already exists list
        # Issue the call to the client.
        $result = $mgClient->post("lists/$listAddress/members", array(
            'address'     => 'bar@example.com',
            'name'        => 'Bob Bar',
            'description' => 'Developer',
            'subscribed'  => true,
            'vars'        => '{"age": 26}'
        ));
```
Got error: 

>  PHP Fatal error:  Uncaught InvalidArgumentException: First argument to Stream::create() must be a string, resource or StreamInterface. in /vendor/nyholm/psr7/src/Stream.php:87

Other POST method (create MailList .. etc) works perfect, except this.

**Comment by DavidGarciaCat** [comment]
Hi @Britskiy 

Please follow the instructions here to install the SDK:
https://github.com/mailgun/mailgun-php#installation

And then these ones to send emails:
https://github.com/mailgun/mailgun-php#usage

Cheers,

**Comment by Britskiy** [comment]
@DavidGarciaCat I followed all the instructions, but the result is the same ... Also all api method that I need works fine, except "add member to mailList"

**Comment by Noraus** [comment]
Hi @Britskiy 

After some minutes of googling and trying to understand what was the problem, I discovered that the boolean arguments must be string, so, change this:

`'subscribed' => true`

to

`'subscribed' => 'true'`

Here also works `'yes'` for TRUE and `'no'` for FALSE.

**Comment by DavidGarciaCat** [comment]
Hi,

Indeed, as per the API Documentation, the expected content should be a string:
https://documentation.mailgun.com/en/latest/api-mailinglists.html#mailing-lists

So yes, as far as it is a string then it should work.

Cheers,
