### ISSUE TITLE
member->createMultiple() not working

### ISSUE THREAD

**Issue by palpalani** [mailgun/mailgun-php#595]
I am using Laravel 5.7 and Mailgun extension.

Mailgun SDK version 2.8.1

I am able to create a Mailing list using new methods.

```php
$address = 'sample@mail-domain.com';
$ml = Mailgun::api()->mailingList();
$list = $ml->create($address, $name);
$response = $list->getList()->getAddress();
echo $response;
```

but not able to insert subscribers.

```php
$recipients[] = [
            'address' => 'myemail1@gmail.com',
            'name' => 'My name',
            'subscribed' => 'yes'
        ];
        $recipients[] = [
            'address' => 'm3pamyemail2lani@gmail.com',
            'name' => 'Sub 2',
            'subscribed' => 'yes'
        ];
        $pages = $ml->member()->createMultiple($address, $recipients);
```

No error message received but subscribers not created.

**Comment by DavidGarciaCat** [comment]
Hey there,

It doesn't look good to me, you're not even instantiating/creating the client with your API Key

Please follow the details here to set-up your client, and proceed from there:
https://github.com/mailgun/mailgun-php#usage

If you still have problems with a correctly instantiated client, feel free to open a new Issue but please provide more details to debug it properly.

Cheers,

**Comment by arghos** [comment]
I have not ben able to figure out how to create in PHP a maillist in batch. The new API is very poory documented and this is the only thing I have found:

require 'vendor/autoload.php';
use Mailgun\Mailgun;

# Instantiate the client.
$mgClient = Mailgun::create('PRIVATE_API_KEY', 'https://API_HOSTNAME');
$mailing_list = 'LIST@YOUR_DOMAIN_NAME';
$members = array(
    array(
        'address'   => 'bob@example.com',
        'name'      => 'Bob',
        'vars'      => array("id" => "123456")
    )
);

# Issue the call to the client.
$result = $mgClient->mailingList()->member()->createMultiple($mailing_list, $members);

In version 2 we had the following that worked fine:

				$result = $mgClient->post("lists/$strMailingListAddress/members.json", array(
	    			'members'    => $strBatch,
				    'upsert'	  => 'yes'
					));

...where $strBatch contains a complete JSON list of the addresses to be added. But now I do not know how to construct a multiple address PHP array that would pass with the new API call. I need to collect the array by going through a database and have sent the addresses in batches of 500 but do not understand how the address array should be created. Just having them in PHP arrays, or an array containing arrays (as shows by the documentation), or trying to send a similar array as in V2, does not work. 

Currently I need to work around this by adding addresses one by one but that does not really work as that is very slow and the process times out before all members are added (somewhere at 400 - 500 users).
