### ISSUE TITLE
Error on simple usage

### ISSUE THREAD

**Issue by mjakubowskilkr** [mailgun/mailgun-php#596]
I configured it few days ago and it worked untill yesterday. Today I've got error (the same error on the simplest usage from github):

>Fatal error: Uncaught Buzz\Exception\NetworkException: file_get_contents(https://api.eu.mailgun.net/v3/sandbox71500f3b967b4b189ef9a7363ea93bc0.mailgun.org/messages): failed to open stream: php_network_getaddresses: getaddrinfo failed: Try again in /var/www/html/mvclogin/mailgun/vendor/kriswallsmith/buzz/lib/Client/FileGetContents.php:27 Stack trace: #0 /var/www/html/mvclogin/mailgun/vendor/php-http/client-common/src/HttpClientDecorator.php(28): Buzz\Client\FileGetContents->sendRequest(Object(Nyholm\Psr7\Request)) #1 /var/www/html/mvclogin/mailgun/vendor/php-http/client-common/src/PluginClient.php(82): Http\Client\Common\EmulatedHttpAsyncClient->sendRequest(Object(Nyholm\Psr7\Request)) #2 /var/www/html/mvclogin/mailgun/vendor/php-http/client-common/src/Plugin/HistoryPlugin.php(39): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(Nyholm\Psr7\Request)) #3 /var/www/html/mvclogin/mailgun/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\HistoryPlugin->handleRequest(Object(N in /var/www/html/mvclogin/mailgun/vendor/kriswallsmith/buzz/lib/Client/FileGetContents.php on line 27

**Comment by Nyholm** [comment]
Looking at your error message: 

> Fatal error: Uncaught Buzz\Exception\NetworkException: file_get_contents(https://api.eu.mailgun.net/v3/sandbox71500f3b967b4b189ef9a7363ea93bc0.mailgun.org/messages): failed to open stream: php_network_getaddresses: getaddrinfo failed

It seams like you have a problem connecting to the internet. 

Im closing this becuase there is nothing wrong with the client.
