### ISSUE TITLE
How to send bulk email to user

### ISSUE THREAD

**Issue by iamanupammaity** [mailgun/mailgun-php#597]
How to send multiple emails to different users in a single hit. To how many users I can send email in one time?

**Comment by DavidGarciaCat** [comment]
Hey @iamanupammaity 

What do you mean with "multiple emails":
- The same content to many recipients?
- Different content to the expected recipients?

Cheers,

**Comment by iamanupammaity** [comment]
The same content to many recipients?

**Comment by DavidGarciaCat** [comment]
Hi, @iamanupammaity 

**Option 1: Individual calls through a loop**

Run a loop to process each recipient individually; not very efficient but it works without major changes on your current source code:

```php
use Mailgun\Mailgun;

$mg = Mailgun::create('key-example'); // For US servers

foreach ($recipients as $recipient) {
    $mg->messages()->send('domain.com', [
        'from'    => 'noreply@domain.com',
        'to'      => $recipient,
        'subject' => 'The PHP SDK is awesome!',
        'text'    => 'It is so simple to send a message.'
    ]);
}
```

**Option 2: use the Message Builder**

Build a Message and then send it to all the expected recipients:

```php
use Mailgun\Mailgun;
use Mailgun\Message\MessageBuilder;

// BUILDER

$builder = new MessageBuilder();
# Define the from address.
$builder->setFromAddress("noreply@domain.com", array("first"=>"PHP", "last" => "SDK"));
# Define a to recipient.
$builder->addToRecipient("recipient1@domain.com", array("first" => "Name1", "last" => "Surname1"));
$builder->addToRecipient("recipient2@domain.com", array("first" => "Name2", "last" => "Surname2"));
# Define the subject.
$builder->setSubject("A message from the PHP SDK using Message Builder!");
# Define the body of the message.
$builder->setTextBody("This is the text body of the message!");

// SENDING

$mg = Mailgun::create('key-example'); // For US servers
$mg->messages()->send("domain.com", $builder->getMessage());
```

Please read more [here](https://github.com/mailgun/mailgun-php/tree/master/src/Message#usage---message-builder) about the `Message Builder`

**Option 3: use the Batch Message**

Similar to the `Message Builder`

Please read more [here](https://github.com/mailgun/mailgun-php/tree/master/src/Message#usage---batch-message) about the `Batch Message`

Hope this helps,
