### ISSUE TITLE
Bug in ShowResponse

### ISSUE THREAD

**Issue by Alexander-Fuchs** [mailgun/mailgun-php#599]
Instead of 'urls' the function 'getWebhookUrl' checks for 'url' so you actually can't query (show) any existing webhooks.

$openHook = $mg->webhooks()->show($mgDomain, 'opened')->getWebhookUrl();
$openHook = null

Fix in ShowResponse Class:
```
    /**
     * @return array|null
     */
    public function getWebhookUrl()
    {
        if (isset($this->webhook['urls'])) {
            return $this->webhook['urls'];
        }
    }
```

**Comment by DavidGarciaCat** [comment]
Hi @Alexander-Fuchs 

Thanks for bringing this into our attention.

If you have time, we're more than happy to get a Pull Request with the fix and the PHP Unit tests to verify the source code works as expected.

----

Adding the following documentation to the issue, for better tracking:

https://documentation.mailgun.com/en/latest/api-webhooks.html#examples

<img width="948" alt="Screenshot 2019-05-14 at 17 33 13" src="https://user-images.githubusercontent.com/7809429/57715374-8288e300-766e-11e9-8146-999489186202.png">

**Comment by DavidGarciaCat** [comment]
The webhooks response should be sorted by now, as part of the 2 PRs referred in this other issue https://github.com/mailgun/mailgun-php/pull/609

Closing this one.
