### ISSUE TITLE
Uncaught TypeError for Mailgun 

### ISSUE THREAD

**Issue by akeren** [mailgun/mailgun-php#604]
`<?php 
ini_set('display_errors', 1);
error_reporting(E_ALL);

require_once 'vendor/autoload.php';
use Mailgun\Mailgun;

define('MAILGUN_KEY', 'key-hghhjghghjhjhjhh'); //private key
define('MAILGUN_PUBKEY', 'pubkey-87585875857858'); //public key

define('MAILGUN_DOMAIN', 'sandboxf66b8d62eb524879ab71425a1bddcee1.mailgun.org'); //domain
define('MAILGUN_LIST', 'news@sandboxf66b8d62eb524879ab71425a1bddcee1.mailgun.org'); //domain listing
define('MAILGUN_SECRET', 'Christlovesme'); //secret phrase 

$mailgun = new Mailgun(MAILGUN_KEY);
$mailgunValidate =  new Mailgun(MAILGUN_PUBKEY);

$mailOptIn = $mailgun->OptInHandler();`
![25](https://user-images.githubusercontent.com/39645910/58777615-ff9cdd80-85c6-11e9-9814-54c168ae3a8b.png)

**Comment by DavidGarciaCat** [comment]
Hi @akeren 

Please follow the [https://github.com/mailgun/mailgun-php#installation](installation) and [https://github.com/mailgun/mailgun-php#usage](usage) instructions.

Cheers,

**Comment by DavidGarciaCat** [comment]
Hi @akeren 

Please follow the [installation](https://github.com/mailgun/mailgun-php#installation) and [usage](https://github.com/mailgun/mailgun-php#usage) instructions.

Cheers,
