### ISSUE TITLE
Instructions are broken on mailgun.com

### ISSUE THREAD

**Issue by KimTheFirst** [mailgun/mailgun-php#605]
Please delete the out of date instructions from mailgun.com and just leave the link to github, It is no good having one thing there and another thing here.

Not really an issue with the repo but I feel like the person who reads this will probably be the right person.

**Comment by DavidGarciaCat** [comment]
Hi, @KimTheFirst 

Please refer to this issue: https://github.com/mailgun/mailgun-php/issues/387

Cheers,
