### ISSUE TITLE
Getting endpoint issue on Delete Route with V3

### ISSUE THREAD

**Issue by codoffer** [mailgun/mailgun-php#606]
Getting below error with Route Deletion (V3) PHP API

Type: Mailgun\Exception\HttpClientException

Message: The endpoint you have tried to access does not exist. Check if the domain matches the domain you have configure on Mailgun.

Filename: ../third_party/Mailgun/vendor/mailgun/mailgun-php/src/Mailgun/Exception/HttpClientException.php

Line Number: 87

I have tried to pass endpoint with constructor and create function but its not working.

```
$mgClient = Mailgun(KEY, null, 'https://api.mailgun.net/v3/MY_DOMAIN/');
$mgClient = Mailgun::create(KEY, 'https://api.mailgun.net/v3/MY_DOMAIN/');
$mgClient = Mailgun::create(KEY, 'https://api.mailgun.net');
```
Getting error, when using route delete
$mgClient->routes()->delete(ROUTE_ID);

$mgClient->routes()->create is working fine.

**Comment by DavidGarciaCat** [comment]
Hi @codoffer 

Please let's try not to add or post on multiple issues when the context is the same. I have just posted an answer and examples for you [here](https://github.com/mailgun/mailgun-php/issues/586).

Hope it helps.
