### ISSUE TITLE
Fail to send Batch Email 

### ISSUE THREAD

**Issue by putrafajarh** [mailgun/mailgun-php#610]
```
    $mg = Mailgun::create($apiKey); 
    $batchMessage = $mg->messages()->getBatchMessage(env('MAILGUN_DOMAIN'));
    $batchMessage->setFromAddress(env('MAIL_FROM_ADDRESS'));
    $batchMessage->setSubject($value->subject);
    $batchMessage->setClickTracking(true);
    // $batchMessage->setReplyToAddress(env('MAIL_FROM_ADDRESS'));
    $batchMessage->setMessage(['html']);
    $batchMessage->setHtmlBody($value->cotent);
    foreach ($recipients as $k => $v) {
        $batchMessage->addToRecipient($v->email, ['full_name' => $v->name]);
    }
    $batchMessage->finalize();
    $messageIds = $batchMessage->getMessageIds();
```

i got this error

`The parameters passed to the API were invalid. Please specify "from".`

already set to this right ?
$batchMessage->setFromAddress(env('MAIL_FROM_ADDRESS'));

**Comment by DavidGarciaCat** [comment]
Hey @putrafajarh 

Can you please try following the examples that we have for the Batch Message and Message Builder here?

https://github.com/mailgun/mailgun-php/blob/master/src/Message/README.md

Please let me know if it works.

Cheers,

**Comment by uavn** [comment]
The only way this error may appear is that env('MAIL_FROM_ADDRESS') is null, I was able to reproduce this with emulating this behavior:

$mg = Mailgun::create($key);
$batch = $mg->messages()->getBatchMessage($domain);

$batch->addToRecipient('artbonvic@gmail.com', ['first' => 'Test3', 'last' => 'User']);
$batch->addToRecipient('artbon.vic@gmail.com', ['first' => 'Test4', 'last' => 'User2']);
$batch->setFromAddress(null);
$batch->setSubject('coocoo');
$batch->setTextBody('Hello %recipient.first% %recipient.last%');
$batch->addInlineImage('@./dell0.jpg', 'inline-name-test.jpg');


$resp = $batch->finalize();
```
error:
```
root@db5b5f913e78:/var/www/mailgun-php-client# php index.php 
[18-Sep-2020 19:53:51 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Mailgun\Message\MessageBuilder::setFromAddress() must be of the type string, null given, called in /var/www/mailgun-php-client/index.php on line 17 and defined in /var/www/mailgun-php/src/Message/MessageBuilder.php:202
Stack trace:
#0 /var/www/mailgun-php-client/index.php(17): Mailgun\Message\MessageBuilder->setFromAddress(NULL)
#1 {main}
  thrown in /var/www/mailgun-php/src/Message/MessageBuilder.php on line 202
```

**Comment by DavidGarciaCat** [comment]
I'm closing the issue due to inactivity and no feedback since 2019.

Thanks @uavn for providing further testing
