### ISSUE TITLE
MessageBuilder::addInlineImage() - $inlineImageName argument not applied

### ISSUE THREAD

**Issue by micschk** [mailgun/mailgun-php#611]
Say I have an image: 
```$abs_img_path = "/some/full/path/to/image.jpg";```

When I inline it using just the path, it works as expected:
```$mb->addInlineImage("@$abs_img_path");```

But when I try to inline it while also applying a (different) name ...
```
$img_name = "picture.jpg";
$mb->addInlineImage("@$abs_img_path", $img_name);
```

... the $img_name is not used in the resulting email:
```Content-Id: <image.jpg>```

(instead of the expected ID:)
```Content-Id: <picture.jpg>```

**Comment by erikduracom** [comment]
Same issue here, nothing happens with the second argument

**Comment by uavn** [comment]
Is it still reproduced? @erikduracom @micschk

**Comment by DavidGarciaCat** [comment]
It would be useful if someone having this problem provides a full example of the used code for testing and reproduce the issue.

Also, Pull Requests are always helpful, as this repo is under the MIT license and contributors are welcome.

**Comment by uavn** [comment]
This works just fine:

```
$mg = Mailgun::create($key);
$batch = $mg->messages()->getBatchMessage($domain);

$batch->addToRecipient('artbonvic@gmail.com', ['first' => 'Test3', 'last' => 'User']);
$batch->addToRecipient('artbon.vic@gmail.com', ['first' => 'Test4', 'last' => 'User2']);
$batch->setFromAddress('batch@uartema.com');
$batch->setSubject('coocoo');
$batch->setTextBody('Hello %recipient.first% %recipient.last%');
$batch->addInlineImage('@./dell0.jpg', 'inline-name-test.jpg');

$resp = $batch->finalize();
```

![Screenshot from 2020-09-18 22-48-56](https://user-images.githubusercontent.com/315338/94287590-2c64c900-ff5f-11ea-9509-f1d89e4a1b0a.png)

**Comment by DavidGarciaCat** [comment]
Thanks @uavn for providing a functional test. Closing this issue
