### ISSUE TITLE
Unable to add members to mailing list

### ISSUE THREAD

**Issue by Scumble373** [mailgun/mailgun-php#612]
Hi there, 

I've been trying to add mailing list support, but got stuck at adding recipients. Deleting recipients, viewing lists / recipients works perfectly. 

After looking at the following issues: 
https://github.com/mailgun/mailgun-php/issues/487
https://github.com/mailgun/mailgun-php/issues/49

I came to this:

                $mgClient = Mailgun::create('MY-API-KEY');
                $listAddress = 'LIST-NAME@MY-DOMAIN';
                $name = "John Doe";
                $mail = "MyValidGmailAddress@gmail.com";
                $errresult = $mgClient->post(sprintf('/v3/lists/%s/members', $listAddress),
                [
                    'name'       => $name,
                    'address'    => $mail,
                    'subscribed' => 'yes'
                ]);

I get the following response:

{"http_response_body":"Mailgun Magnificent API","http_response_code":200}

But the recipient isn't being added to the list. I feel like I'm close... what am I missing? 

Thanks!

**Comment by DavidGarciaCat** [comment]
Hey @Scumble373 

Can you please try using the helpers instead of running a `post` call? There should be helpers for every action (not just messages). Please use your IDE to get all the available options.

You can follow the [README Usage](https://github.com/mailgun/mailgun-php#usage) as an example, but try using the method to get access to the mailing lists (`mailingList()` instead of `messages()`, then continue following the methods that the SDK gives you to get access to the resource that you want to use).

Cheers,

**Comment by Scumble373** [comment]
Thanks @DavidGarciaCat! I found the functions I was looking for and came up with:

$result = $mgClient->mailingList()->member()->create($listAddress,$mail,$name);

To get the add to work, in case someone stumbles upon the same question in the future. 

Thanks for all the hard work you guys do on this project! :)

**Comment by DavidGarciaCat** [comment]
Glad to hear that it worked!

Enjoy the rest of your day!

**Comment by brandaolopes** [comment]
> ```
> mailingList()->member()->create($listAddress,$mail,$name)
> ```

Hi @Scumble373! 
Could you show your final code for this action, once we haven't an official documentation update for this matter yet? 

Thanks!

**Comment by Scumble373** [comment]
Absolutely!

`include_once` 'vendor/autoload.php';
use Mailgun\Mailgun;

        $subscribed = 1;
        $fromemail = mysqli_real_escape_string($link, $_POST["email"]);
        $listaddress = "LISTEMAIL@DOMAIN.COM";
        $name = "Recipient";

        $mgClient = Mailgun::create('MY_API_KEY');
        try
        {
            $result = $mgClient->mailingList()->member()->create($listaddress,$fromemail,$name);
        }
        catch (Exception $e)
        {
            if($e->getResponseCode() == 400)
                //Email is already on list!
            else
                //Error has occurred
        }
    }
`

**Comment by brandaolopes** [comment]
Thank you very much!
Let's code! =)
