### ISSUE TITLE
SMTP password changes

### ISSUE THREAD

**Issue by nathanntg** [mailgun/mailgun-php#614]
I am not seeing a change in the Mailgun documentation regarding the domain creation, but I am now getting an error regarding the SMTP password. Has that API call changed? And if so, any guidance on how to specify other settings, like SPAM filtering, which appear to only be processed if an SMTP password is present?

```
PHP Fatal error:  Uncaught Mailgun\Exception\HttpClientException: The parameters passed to the API were invalid. Check your inputs!

smtp_password is not stored anymore in vendor/mailgun/mailgun-php/src/Mailgun/Exception/HttpClientException.php:72
Stack trace:
#0 vendor/mailgun/mailgun-php/src/Mailgun/Api/HttpApi.php(91): Mailgun\Exception\HttpClientException::badRequest(Object(Nyholm\Psr7\Response))
#1 vendor/mailgun/mailgun-php/src/Mailgun/Api/HttpApi.php(73): Mailgun\Api\HttpApi->handleErrors(Object(Nyholm\Psr7\Response))
#2 vendor/mailgun/mailgun-php/src/Mailgun/Api/Domain.php(104): Mailgun\Api\HttpApi->hydrateResponse(Object(Nyholm\Psr7\Response), 'Mailgun\\Model\\D...')
#3 includes/helpers/mailgun.i.php(17): Mailgun\Api\Domain->create(...)
```

**Comment by DavidGarciaCat** [comment]
Hi @nathanntg 

Can you please paste here the whole code instead of just the stack trace?

Is really hard to know what's going on when no one can see the code that you're running.

Thanks,

**Comment by nathanntg** [comment]
Happy to. It’s pretty basic:

```php
$mg = Mailgun::create(MAILGUN_KEY);

// subdomain
$domain = 'email.example.com';

// random password
$password = random_str(16);

// create domain
$mg->domains()->create($domain, $password, 'tag', false);
```

**Comment by DavidGarciaCat** [comment]
Based on the API docs and the SDK requirements, it should be working, so that some additional investigation is required.

In the meantime, and not to cause a blocker and delay a solution, would you mind trying with this other approach?

```php
// Instantiate your client
$mg = Mailgun::create(MAILGUN_KEY);
// Set the domain that you want to register
$domain = 'email.example.com';
// Set the expected username
$username = sprintf('mailgun@%s', $domain);
// Generate a random password
$password = random_str(16);
// Create the new Mailgun's domain
$mg->domains()->create($domain);
// Create the new credentials
$mg->domains()->createCredential($domain, $username, $password);
```
Please let us know if it works.

Cheers,

**Comment by DavidGarciaCat** [comment]
Cool; I've reviewed the PR and added a couple of comments. Please let's follow the chat there so that we can take care of the update and merge it once it's ready.

**Comment by DavidGarciaCat** [comment]
PR https://github.com/mailgun/mailgun-php/pull/622 has been merged into `master`. Closing this issue now. Please feel free to use the `dev-master` dependency on your `composer.json` file while the new tag is not released.
