### ISSUE TITLE
Email Validation Not Working

### ISSUE THREAD

**Issue by CameronSumpter** [mailgun/mailgun-php#617]
In 3.0.0-beta1, the email validation function fails because of an invalid response from the API. It appears that, in EmailValidation.php, the GET request on Line 54 `/address/private/validate` should be `/v4/address/validate` (and Line 93 as well).

**Comment by DavidGarciaCat** [comment]
Hi, @CameronSumpter 

Can you please confirm that the current bulk implementation [here](https://github.com/mailgun/mailgun-php/blob/master/src/Api/EmailValidation.php#L93) is failing too and that we need a completely new integration with the new API v4 docs?

Thanks,

**Comment by CameronSumpter** [comment]
Hi @DavidGarciaCat, my use-case is only checking a given single address, but I did quickly test and using `parse` resulted in the same:
```
HydrationException
Error (4) when trying to json_decode response
in ModelHydrator.php line 40
```

Also, possibly something on the back-end of the API itself, I found that even when using the v4 endpoints, while it is giving `didYouMean`, `isDisposableAddress`, `isRoleAddress`, `isValid`, etc..., it is not returning `result` or `risk` (expected from [Documentation](https://documentation.mailgun.com/en/latest/api-email-validation.html)).

**Comment by DavidGarciaCat** [comment]
Thanks, @CameronSumpter 

I'll try to continue working on the already opened PR tomorrow; it's too late for me now 🙂

Cheers,

**Comment by DavidGarciaCat** [comment]
Hey @CameronSumpter 

May I ask what region do you use? Is your domain registered in the US or the EU?

Thanks,

**Comment by CameronSumpter** [comment]
Sure thing! I've confirmed with two US domains; I don't have any EU registrations.

**Comment by DavidGarciaCat** [comment]
Hi, @CameronSumpter 

I've got confirmation from Mailgun support team that:
- Currently, the email validation just works with the US servers but not the EU - not a problem for you
- The API v3 - current integration - worked with the public key, as per their tests
- The API v4 - new one - will work using the private key

Thus, this SDK:
- Should work to validate emails, but you might need to instantiate it with both the Public and Private keys depending on what you want to run
- Will need a new update to ensure that the EU region is forwarded to the US for those that use domains hosted in the EU servers

Can you please run a test with your Public API Key and confirm that it works?

Thanks,

**Comment by DavidGarciaCat** [comment]
I'm closing this issue due to we have https://github.com/mailgun/mailgun-php/issues/619 to track the update. There is also a WIP PR that I'll do my best to finish and merge as soon as possible.
