### ISSUE TITLE
Review the Email Validation functionality

### ISSUE THREAD

**Issue by DavidGarciaCat** [mailgun/mailgun-php#619]
As pointed out here #617 the validation didn't work when tried it using the US servers.

The Mailgun Support team has confirmed that the service should work as follows:

---

> I can confirm the EU region does not have email validation at this time; only the US.  As for v3 of the email validation API, it is still operative.  I just ran a quick test just to confirm:

```
$ curl -G --user 'api:pubkey-REDACTED' -G \
>    https://api.mailgun.net/v3/address/validate \
>    --data-urlencode address='mgbox01@gmail.com'
```
```
{
    "address":"mgbox01@gmail.com",
    "did_you_mean":null,
    "is_disposable_address":false,
    "is_role_address":false,
    "is_valid":true,
    "mailbox_verification":"true",
    "parts":{
        "display_name":null,
        "domain":"gmail.com",
        "local_part":"mgbox01"
    },
    "reason":null
}
```

> And we moved the documentation for it to the following URL: https://documentation.mailgun.com/en/latest/api-email-validation-deprecated.html#email-validation

---

Thus, the SDK needs an update to cover the following cases:
- Potential check and error message if someone tries to validate an email through the EU service
- Potential check and error message if someone tries to validate an email through a private key
- Potential adjustments to use the API v4 instead of the API v3 for the email validation

Even if we don't update the code, then we should consider to add a disclaimer as part of the README file to announce these details and prevent other misunderstandings.

**Comment by saturnonearth** [comment]
Hi there,

Yes I have confirmed with support as well that 

> They are using v3 vs the v4 Email Validation API. the v3 is is_valid just means it’s a RFC syntactical address, it doesn’t perform mailbox verification unless specified. We recommend them use the v4 email validation API

Here's my vote for V4 implementation 🙌😎

**Comment by pinepain** [comment]
Hi, any progress on this issue? Is help needed?

**Comment by natatkinson** [comment]
I'm working with mailgun support and they said I should be using v4 of validation. Any idea on when this might be ready?

**Comment by Matroskeen** [comment]
Hello guys,
Any news so far? Do you have any estimates of the completion?

We would like to integrate Email Validation into Drupal module and I think it'll be great to use v4 version: https://www.drupal.org/project/mailgun/issues/2966690#comment-13400874

**Comment by saturnonearth** [comment]
> Hello guys,
> Any news so far? Do you have any estimates of the completion?
> 
> We would like to integrate Email Validation into Drupal module and I think it'll be great to use v4 version: https://www.drupal.org/project/mailgun/issues/2966690#comment-13400874


If it helps, I ended up using cURL as it didn't seem like the PHP version was going to update to v4 anytime soon.

**Comment by 9jaboy** [comment]
any update on this?

**Comment by EvanWashkow** [comment]
Hey. My company needs this fixed. I'm wondering when we can expect this fixed?

**Comment by RayHughes** [comment]
Having trouble with the SDK and found this. It seems that it cannot properly decode the response. Any idea when this may be updated?

**Comment by saturnonearth** [comment]
> Having trouble with the SDK and found this. It seems that it cannot properly decode the response. Any idea when this may be updated?

Use cURL to verify instead of the SDK.

**Comment by RayHughes** [comment]
> > Having trouble with the SDK and found this. It seems that it cannot properly decode the response. Any idea when this may be updated?
> 
> Use cURL to verify instead of the SDK.

That is what I wound up doing but it is still less than ideal

**Comment by DavidGarciaCat** [comment]
The previous implementations for a solution weren't successful as the validation calls were dependant on the US servers, and the SDK was targeting the EU servers when someone set them up to match with their domain. Furthermore, the API version might also be a problem if the Mailgun team updates them, but the community that maintains this SDK is not aware of any change.

If someone wants to work on a Pull Request to get this fixed, I'm more than happy to review and merge the code. If not, unfortunately, I cannot commit myself to a specific date as I have other matters to attend and invest a few hours on this update is not something I can handle at the moment in time.

**Comment by DavidGarciaCat** [comment]
Implemented on PR https://github.com/mailgun/mailgun-php/pull/726
