### ISSUE TITLE
How to read mailgun API responses

### ISSUE THREAD

**Issue by mihitha** [mailgun/mailgun-php#620]
I am super confused how to read API response when a mail is successfully queued.

```
// First, instantiate the SDK with your API credentials
$mg = Mailgun::create('key-example'); // For US servers
$mg = Mailgun::create('key-example', 'https://api.eu.mailgun.net'); // For EU servers

// Now, compose and send your message.
// $mg->messages()->send($domain, $params);
$response = $mg->messages()->send('example.com', [
  'from'    => 'bob@example.com',
  'to'      => 'sally@example.com',
  'subject' => 'The PHP SDK is awesome!',
  'text'    => 'It is so simple to send a message.'
]);

var_dump($response);
```

$response is a private object and I cannot read "Queued. Thank you." inside of it. I cannot find any relevant functions to do that in the documentation. Am I missing something here ?

**Comment by dvdknaap** [comment]
hi @mihitha 

it return an object of `Mailgun\Model\Message\SendResponse`

To get the id you can just use `$response->getId()` for the message `$response->getMessage()`

**Comment by brandonmbanks** [comment]
I realize this is closed. Is there a way to get the Mailgun response? Like when adding a user to a mailing list?

Sample Response from Mailgun taken from [documentation](https://documentation.mailgun.com/en/latest/api-mailinglists.html#examples)
```json
{
  "member": {
      "vars": {
          "age": 26
      },
      "name": "Bob Bar",
      "subscribed": true,
      "address": "bar@example.com"
  },
  "message": "Mailing list member has been created"
}
```
It seems like we don't have access to that data. Only the Id and Message. Would appreciate advice on this.
