### ISSUE TITLE
Master branch documentation - Could not find resource using any discovery strategy

### ISSUE THREAD

**Issue by nox7** [mailgun/mailgun-php#623]
Using both the master and the 2.x branch installation methods (composer JSONs below) I am unable to install a working implementation of MailGun's PHP SDK without getting the following error
`
Fatal error: Uncaught Http\Discovery\Exception\DiscoveryFailedException: Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors - Puli Factory is not available - No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: Nyholm\Psr7\Factory\HttplugFactory, Http\Message\UriFactory\GuzzleUriFactory, Http\Message\UriFactory\DiactorosUriFactory, Http\Message\UriFactory\SlimUriFactory. - No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: . in /home/lumenshield/vendor/php-http/discovery/src/Exception/DiscoveryFailedException.php:41 Stack trace: #0 /home/lumenshield/vendor/php-http/discovery/src/ClassDiscovery.php(79): Http\Discovery\Exception\DiscoveryFailedException::create(Array) #1 /home/lumenshield/vendor/php-http/discovery/src/UriFactoryDiscovery.php(27): Http\Discovery\ClassDiscovery::fin in 
`

I've run the master branch composer as
`composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7`

Ending up with
```
{
    "require": {
        "mailgun/mailgun-php": "^2.8",
        "kriswallsmith/buzz": "^1.0",
        "nyholm/psr7": "^1.2"
    }
}

```

I've then attempted to install a previously working version set, but received the same error
```
{
    "require": {
        "mailgun/mailgun-php": "^2.6",
        "php-http/curl-client": "^1.7",
        "guzzlehttp/psr7": "^1.4"
    }
}
```

Is there a dependency change I am not aware of or should I be adjusted my installed versions of some package?

**Comment by DavidGarciaCat** [comment]
Hey @nox7 

Maybe you can use this as a reference; I've shared this code some time ago:

https://gist.github.com/DavidGarciaCat/acbf2141b62bdd3bfe3ddff8cafe31e9

Cheers,
