### ISSUE TITLE
failed to open stream: no suitable wrapper could be found in

### ISSUE THREAD

**Issue by Scumble373** [mailgun/mailgun-php#624]
Trying to test sending an email on our live website and I get the following error:

(note: This works using mamp on our test environment, but when setting it live, it doesn't. We made sure the php versions match and everything was uploaded correctly. Any ideas why we're getting this?) 

> [27-Aug-2019 19:22:56 UTC] PHP Fatal error:  Uncaught Buzz\Exception\NetworkException: file_get_contents(https://api.mailgun.net/v3/DOMAIN_NAME/messages): failed to open stream: no suitable wrapper could be found in /FTP_ROOT/vendor/kriswallsmith/buzz/lib/Client/FileGetContents.php:27
> 
> With the stack trace:
> 
> Stack trace:
> #0 /FTP_ROOT/vendor/php-http/client-common/src/HttpClientDecorator.php(28): Buzz\Client\FileGetContents->sendRequest(Object(Nyholm\Psr7\Request))
> 
> #1 /FTP_ROOT/vendor/php-http/client-common/src/PluginClient.php(82): Http\Client\Common\EmulatedHttpAsyncClient->sendRequest(Object(Nyholm\Psr7\Request))
> 
> #2 /FTP_ROOT/vendor/php-http/client-common/src/Plugin/HistoryPlugin.php(39): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(Nyholm\Psr7\Request))
> 
> #3 /FTP_ROOT/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\HistoryPlugin->handleR in /FTP_ROOT/vendor/kriswallsmith/buzz/lib/Client/FileGetContents.php on line 27

The setup and code were both taken from the main gethub page. 

```php
$subject = "New Catelog request from ".$company;
$message .= " Sent by ".$fromname.", ".$fromemail;
$mgClient = Mailgun::create('MY_API_KEY');
$mgClient->messages()->send('MY_DOMAIN', [
    'from'    => ' Postmaster <Sender@MY_DOMAIN>',
    'to'      => 'Scumble373@gmail.com',
    'subject' => $subject,
    'text'    => $message
]);
```

Thanks!

**Comment by DavidGarciaCat** [comment]
Hey, @Scumble373 

As a first check, if you've got SSH access to the server, I would suggest running `composer` there to install all the dependencies of your project. In this way, you can make sure that you're not missing anything and at the same time that the PHP version of the prod environment has all the required dependencies (especial emphasis on the PHP extensions).

Silly question, sorry for this but I need to ask: I guess that both `MY_DOMAIN` and `MY_API_KEY` are variables or constants that have been defined somewhere and you're passing them as expected, right?

Cheers,

**Comment by DavidGarciaCat** [comment]
Hey @Dcumble373

The current master branch expects 7.1; please check the requirements and suggestions here:

https://github.com/mailgun/mailgun-php/blob/master/composer.json

Cheers,

**Comment by DavidGarciaCat** [comment]
Thanks for the update. I'm glad that you found it.

Cheers,
