### ISSUE TITLE
Getting Error while sending message

### ISSUE THREAD

**Issue by mitulgolakiya** [mailgun/mailgun-php#627]
Hi, I'm trying to follow the doc and installed the following quick start packages.

`composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7`

And I wrote the following code,

```
// First, instantiate the SDK with your API credentials
$mg = Mailgun::create('key-example', 'https://api.eu.mailgun.net'); // For EU servers

// Now, compose and send your message.
// $mg->messages()->send($domain, $params);
$mg->messages()->send('my-domain-here', [
  'from'    => 'bob@example.com',
  'to'      => 'sally@example.com',
  'subject' => 'The PHP SDK is awesome!',
  'text'    => 'It is so simple to send a message.'
]);
```

When I call last ling, I'm getting following error.

`Argument 1 passed to Mailgun\Api\HttpApi::__construct() must implement interface Psr\Http\Client\ClientInterface, instance of Http\Client\Common\PluginClient given`

Am I missing something?

**Comment by DavidGarciaCat** [comment]
Hi @mitulgolakiya 

Can you please try using another HTTP Client? Any of the ones listed on the HttPlug docs should work:

http://docs.php-http.org/en/latest/clients.html

Cheers,

**Comment by p0358** [comment]
Getting exact same issue, after update it was complaining about missing HTTP clients or something, I ended up running the op's command, and now I got this...

**Comment by p0358** [comment]
Okay, fixed this by editing `composer.json`. I changed `"php-http/curl-client": "^1.7"` in `"require"` to `"php-http/curl-client": "^2.0"` and ran `composer update`, then it updated a few other components too to the latest versions

**Comment by DavidGarciaCat** [comment]
Hi, @p0358

Thanks for the update, and confirming that when the dependencies were updated then the issue was solved.

Enjoy the rest of your day,
