### ISSUE TITLE
Function for non-existent endpoint.

### ISSUE THREAD

**Issue by spencer-ryan** [mailgun/mailgun-php#628]
When calling the all() function on the Stats class:

`$mg->stats()->all($domain);`

I get the following exception:

`The endpoint you have tried to access does not exist. Check if the domain matches the domain you have configure on Mailgun.`

I can use the same domain to call:
`$mg->events()->get($domain)->total();`
and this works fine.

**Comment by DavidGarciaCat** [comment]
Hi, @spencer-ryan 

Browsing the [Mailgun's API Docs](https://documentation.mailgun.com/en/latest/api-stats.html#stats), I can't see any endpoint mapping the `all()` method. I guess that we'll need to remove it unless the Mailgun support team can give us an update about this one.

Cheers,

**Comment by DavidGarciaCat** [comment]
Already removed

https://github.com/mailgun/mailgun-php/blob/44a30f7dd1f7f06baa48ef2a70618af219594ad3/src/Api/Stats.php#L22-L35
