### ISSUE TITLE
New implementation for deprecated or new functionality

### ISSUE THREAD

**Issue by DavidGarciaCat** [mailgun/mailgun-php#633]
While updating the Mailgun API Docs and as per the issues that have been reported so far, the following functionalities are working based on the deprecated endpoints. New Pull Requests are accepted to expedite the new functionalities.

### ~Domains Tracking~

~https://documentation.mailgun.com/en/latest/api-domains.html?highlight=tracking#domains~

### ~Email Validation~

~https://documentation.mailgun.com/en/latest/api-email-validation.html~

~The API v4 for email validation requires a new implementation.~

~Please refer to the issues https://github.com/mailgun/mailgun-php/issues/617 and https://github.com/mailgun/mailgun-php/issues/619 and to the Pull Request https://github.com/mailgun/mailgun-php/issues/618 for additional information.~

### Mailboxes

https://documentation.mailgun.com/en/latest/api-mailboxes.html

### ~Mailing Lists validation~

~https://documentation.mailgun.com/en/latest/api-mailinglists.html~

### ~Webhooks~

~https://documentation.mailgun.com/en/latest/api-webhooks.html~

~The IDs have been renamed, and we can now pass an array of URLs instead of a single one.~

~Please refer to the Pull Request https://github.com/mailgun/mailgun-php/pull/609 and https://github.com/mailgun/mailgun-php/pull/749 for additional information.~

### ~Whitelist Suppression~

~https://documentation.mailgun.com/en/latest/api-suppressions.html#whitelists~

**Comment by uavn** [comment]
@DavidGarciaCat 

Since Domain Tracking, Mailing List Validation and Suppression Whitelists are done, 
Webhooks has already PR creted,
Mailboxes are deprecated (see the link: Warning Mailboxes is a legacy feature of Mailgun that is no longer offered to new customers. Please utilize the Store() endpoint instead.)

what else should be done here?

**Comment by DavidGarciaCat** [comment]
Hello @uavn 

We should review the [API Documentation](https://documentation.mailgun.com/en/latest/api_reference.html) and confirm if there's any other missing functionality. In the best-case scenario, everything will already be implemented.

And, although I have been saying it every time you pushed a PR, thank you very much for all your contributions.

**Comment by instalab** [comment]
Hi
I am unsure if here is the right place to inform about this issue; the Mailgun\Model\Webhook\IndexResponse does not correctly handle the webhook response. I am not sure if this is something that has changed recently as I've only started working with the Mailgun APIs recently, but the response I am getting from the Mailgun API is in the following format:
```json
{
  "webhooks": {
    "clicked": {
      "urls": []
    },
    "complained": {
      "urls": []
    },
    "delivered": {
      "urls": []
    },
    "opened": {
      "urls": []
    },
    "permanent_fail": {
      "urls": []
    },
    "temporary_fail": {
      "urls": []
    },
    "unsubscribed": {
      "urls": []
    }
  }
}
```

The class seems to be expecting a different format, e.g. "click" instead of "clicked".
Can we update the library to support the current response format?

**Comment by DavidGarciaCat** [comment]
Hi @instalab 

It would be better to create a new issue rather than using this one to post an error.

I have created this one for you, please let's follow up this case there: https://github.com/mailgun/mailgun-php/issues/769

Cheers,

**Comment by Pavlico** [comment]
> Hello @uavn
> 
> We should review the [API Documentation](https://documentation.mailgun.com/en/latest/api_reference.html) and confirm if there's any other missing functionality. In the best-case scenario, everything will already be implemented.
> 
> And, although I have been saying it every time you pushed a PR, thank you very much for all your contributions.

HI @DavidGarciaCat i was trying to look at documentation and its kind of hard task to find any lacks in docs, nevertheless i came across some misspelling and stuff like that in sample codes, how can i fix them ?
``

**Comment by DavidGarciaCat** [comment]
As far as I know - and I might be wrong - all Mailgun Docs are here: https://github.com/mailgun/documentation

Forks and Pull Requests are needed, then someone from Mailgun team needs to merge them
