### ISSUE TITLE
Uncaught InvalidArgumentException: First argument to "Http\Message\MultipartStream\MultipartStreamBuilder::createStream()" must be a string, resource or StreamInterface

### ISSUE THREAD

**Issue by indapublic** [mailgun/mailgun-php#637]
```
<?php

declare(strict_types=1);

require_once './vendor/autoload.php';

use Mailgun\Mailgun;

define("API_KEY", "");
define("API_DOMAIN", "");
define("SUBLIST", "");
define("EMAIL", "");

$mailgun = Mailgun::create(API_KEY);
$mailgun->mailingList()->member()->create(
    SUBLIST,
    EMAIL,
    null, // name
    [],
    false,
    true
);

$parameters = [
    'name' => null, // name
    'subscribed' => 'yes',
];

$mailgun->mailingList()->member()->update(
    SUBLIST,
    EMAIL,
    $parameters
);
```

Null name will cause error:

> PHP Fatal error:  Uncaught InvalidArgumentException: First argument to "Http\Message\MultipartStream\MultipartStreamBuilder::createStream()" must be a string, resource or StreamInterface. in /home/zolotukhin/Projects/github/test-mailgun/vendor/php-http/multipart-stream-builder/src/MultipartStreamBuilder.php:332

**Comment by rsignavong** [comment]
+1
Got the same error when trying too add member to maling list.

**Comment by kslr** [comment]
```php
$mg = Mailgun::create(config('services.mailgun.secret'));
$mg->mailingList()->member()->create('news@**.***.com', 'test@mail.com');
```

**Comment by kevinarrieta** [comment]
+1

**Comment by iget-master** [comment]
The cause looks similar to #652 cause, but in different parts of the code. This is some regression, but I'm not sure what version caused it.

**Comment by indapublic** [comment]
@iget-master You issue is related to 2.8.1 version, but my is for 3.x

**Comment by iget-master** [comment]
I know... But both have the similar causes

**Comment by johnsheehan** [comment]
I got this when setting `o:tracking` to `true` instead of `"true"`

**Comment by muzafarali** [comment]
```
$result = $mg->post("routes", array(
        'priority'    => 0,
        'expression'  => 'match_recipient(".*@mydomain.com")',
        'action'      => array('forward("http://bin.mailgun.net/7e1e6cx58")', 'stop()'),
        'description' => 'Sample route'
    ));
```
getting same error

**Comment by iget-master** [comment]
@muzafarali use string zero instead of number zero:

'priority' => '0'

**Comment by hemorej** [comment]
@iget-master kind of a strange problem no? 
But it also solves my issue. I had a `'o:require-tls' => true` option set to a native boolean that was causing the same issue, when using a string it works fine.

**Comment by kslr** [comment]
I recommend downgrading to 2.x

**Comment by iget-master** [comment]
@kslr this have the same root cause that issue #652 

See it and https://github.com/mailgun/mailgun-php/pull/653 for details

**Comment by kslr** [comment]
But no one is dealing with it now :-|

**Comment by fl90** [comment]
Is there anybody who will finish the PR and fix this problem?

**Comment by iget-master** [comment]
The pr is done. Lacks someone to approve and merge.

**Comment by bhensonweb** [comment]
> I got this when setting `o:tracking` to `true` instead of `"true"`

This was my problem but for 'o:testmode' param.
