### ISSUE TITLE
Uncaught Mailgun\Exception\HttpClientException: The parameters passed to the API were invalid. Check your inputs!  'vars' parameter is not a valid JSON in vendor/mailgun/mailgun-php/src/Exception/HttpClientException.php:63

### ISSUE THREAD

**Issue by indapublic** [mailgun/mailgun-php#638]
Passing `vars` parameter as array will cause error:

```
<?php

declare(strict_types=1);

require_once './vendor/autoload.php';

use Mailgun\Mailgun;

define("API_KEY", "");
define("API_DOMAIN", "");
define("SUBLIST", "");
define("EMAIL", "");
define("NAME", "");

$mailgun = Mailgun::create(API_KEY);
$mailgun->mailingList()->member()->create(
    SUBLIST,
    EMAIL,
    NAME,
    [],
    false,
    true
);

$parameters = [
    'vars' => [
        'foo' => 'bar',
    ],
    'name' => NAME,
    'subscribed' => 'yes',
];

$mailgun->mailingList()->member()->update(
    SUBLIST,
    EMAIL,
    $parameters
);
```

> PHP Fatal error:  Uncaught Mailgun\Exception\HttpClientException: The parameters passed to the API were invalid. Check your inputs!
> 
> 'vars' parameter is not a valid JSON in /home/zolotukhin/Projects/github/test-mailgun/vendor/mailgun/mailgun-php/src/Exception/HttpClientException.php:63

`vars` parameters are not json encoded ([only value](https://github.com/mailgun/mailgun-php/blob/master/src/Api/MailingList/Member.php#L202)) while request

**Comment by ZioCain** [comment]
You just have to run `json_encode` on the data you're passing as data, so something like

    json_encode( $paramenters )

**Comment by indapublic** [comment]
@ZioCain I know, but API allows pass array to `vars` (see asserts) but cannot process it.
I prefer pass pure array instead of JSON encoded
