### ISSUE TITLE
Default value for parameters with a class type hint can only be NULL

### ISSUE THREAD

**Issue by goaiworld** [mailgun/mailgun-php#640]
Fatal error occurring at line no 68 in mailgun.php
public static function create(string $apiKey, string $endpoint = 'https://api.mailgun.net'): self

the error message is "Default value for parameters with a class type hint can only be NULL"

i think the error is due to my php version (5.6). which version of the sdk supports php 5.6?

**Comment by goaiworld** [comment]
i have decided to move to php 7.1. now i have some other issues with the event polling. but that's another issue.

**Comment by DavidGarciaCat** [comment]
Hi @goaiworld 

The SDK v3 has - as a requirement - PHP 7.1. Please check the composer requirements here:

https://github.com/mailgun/mailgun-php/blob/master/composer.json#L5

Cheers,
