### ISSUE TITLE
Call to undefined method Mailgun\Mailgun::get()

### ISSUE THREAD

**Issue by goaiworld** [mailgun/mailgun-php#641]
This sample code is not working
```
# Include the Autoloader (see "Libraries" for install instructions)
require 'vendor/autoload.php';
use Mailgun\Mailgun;

# Instantiate the client.
$mgClient = new Mailgun('YOUR_API_KEY');
$domain = 'YOUR_DOMAIN_NAME';
$queryString = array(
    'begin'        => 'Fri, 3 May 2013 09:00:00 -0000',
    'ascending'    => 'yes',
    'limit'        =>  25,
    'pretty'       => 'yes',
    'subject'      => 'test'
);

# Make the call to the client.
$result = $mgClient->get("$domain/events", $queryString);
```
First of all, $mgClient = new Mailgun('YOUR_API_KEY'); should be $mgClient = Mailgun::create('YOUR_API_KEY');
Then we don't have a get method in Mailgun class!!!

**Comment by goaiworld** [comment]
use $mgClient->events()->get($domain, $queryString); instead.

**Comment by DavidGarciaCat** [comment]
Hi @goaiworld 

The SDK v3 was released a few days ago. The API Docs update is an already WIP, but there are close to 100 examples that need to be updated. I'll send the PR as soon as possible.

Cheers,
