### ISSUE TITLE
Uncaught TypeError: Argument 1 passed to Mailgun\Api\HttpApi::__construct() must implement interface Psr\Http\Client\ClientInterface

### ISSUE THREAD

**Issue by ZioCain** [mailgun/mailgun-php#642]
Hello, just updated Mailgun API (using composer).

then I try to send an e-mail after following documentation.
Test code is:

    $mg = Mailgun::create(MAILGUN_API_KEY, "https://api.eu.mailgun.net");
    $mg->messages()->send(DOMAIN, [
    	"from" => "myemail@mydoamin.com",
    	"to" => "myemail@mydoamin.com",
    	"subject" => "TEST",
    	"text" => "Testing mailgun"
    ]);

while running the code I get the following error:

    Uncaught TypeError: Argument 1 passed to Mailgun\Api\HttpApi::__construct() must implement interface Psr\Http\Client\ClientInterface, instance of Http\Client\Common\PluginClient given, called in /.../vendor/mailgun/mailgun-php/src/Mailgun.php on line 114 and defined in /.../vendor/mailgun/mailgun-php/src/Api/HttpApi.php:46
    --
      | Stack trace:
      | #0 /..../vendor/mailgun/mailgun-php/src/Mailgun.php(114): Mailgun\Api\HttpApi->__construct(Object(Http\Client\Common\PluginClient), Object(Mailgun\HttpClient\RequestBuilder), Object(Mailgun\Hydrator\ModelHydrator))
    #1 /..../testMail.php(24): Mailgun\Mailgun->messages()
    #2 {main}
      thrown in /..../vendor/mailgun/mailgun-php/src/Api/HttpApi.php on line 46

Is there any update or fix or something?

Quick update:
even without setting the european server, the issue persists

**Comment by libereducacao** [comment]
I am having the same problem. Anybody can give us a hand?

**Comment by ZioCain** [comment]
Ok, found a solution / hack.
Since in the [user-guide](https://documentation.mailgun.com/en/latest/api-sending.html#examples) they use CURL to send e-mails, I wrote a function to actually send emails with PHP using cURL:

    function postCurl($url, $data){
    	$ch=curl_init();
    	curl_setopt($ch, CURLOPT_URL,$url);
    	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    	curl_setopt($ch, CURLOPT_TIMEOUT, 30);
    	curl_setopt($ch, CURLOPT_POST, 1);
    	curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data));
    	curl_setopt($ch, CURLOPT_USERPWD, 'api:'.MAILGUN_API_KEY);
    	$o=curl_exec($ch);
    	curl_close($ch);
    	return $o;
    }

to be called like:

    postCurl("https://api.eu.mailgun.net/v3/YOUR_DOMAIN/messages", <PHP_ASSOC_WITH_DATA>);

**Comment by wejy** [comment]
Same issue here. Hoping for a fast fix. Using PHP 7.3 & Slim framework.

**Comment by rossbulat** [comment]
Experiencing the same issue here - falling back to raw cURL requests bypasses this and works.

**Comment by satoshinosekai** [comment]
You must be use the new syntax for php.

$mg = Mailgun::create('api-key'); // For US servers
$mg = Mailgun::create('api-key', 'https://api.eu.mailgun.net'); // For EU servers

// $mg->messages()->send($domain, $params);
$mg->messages()->send('example.com', [
  'from'    => 'bob@example.com',
  'to'      => 'sally@example.com',
  'subject' => 'The PHP SDK is awesome!',
  'text'    => 'It is so simple to send a message.'
]);

**Comment by jam1e** [comment]
Same issue here. Running Laravel 6.1.0

**Comment by micc83** [comment]
I had the same issue when first updated to v3. Try with the following updated packages in your `composer.json`:
```json
{
    "mailgun/mailgun-php": "~3.0.0",
    "guzzlehttp/guzzle": "^6.3",
    "php-http/guzzle6-adapter": "^2.0",
}
```

**Comment by DavidGarciaCat** [comment]
Sorry for the delay, guys, but I didn't have any time due to personal reasons.

Please don't upgrade just the SDK package; instead, please follow the instructions on the installation section: https://github.com/mailgun/mailgun-php#installation

Cheers,

**Comment by wejy** [comment]
> I had the same issue when first updated to v3. Try with the following updated packages in your `composer.json`:
> 
> ```json
> {
>     "mailgun/mailgun-php": "~3.0.0",
>     "guzzlehttp/guzzle": "^6.3",
>     "php-http/guzzle6-adapter": "^2.0",
> }
> ```

Thanks, this fixes the error and working now with EU api.

**Comment by hehez** [comment]
I still have the same issue

**Comment by tonythomas01** [comment]
I can see this issue still happening when using the psr implementation. Sounds like this assumption (or probably an expectation) in `Mailgun.php` is not working out so well. 

```
    /**
     * @var ClientInterface|PluginClient
     */
    private $httpClient;
```

Later in the code, the $httpClient is passed on to: 
```
    public function messages(): Api\Message
    {
        return new Api\Message($this->httpClient, $this->requestBuilder, $this->hydrator);
    }
```
and on the HTTPApi construct, we have the first param tied to type `ClientInterface`: 
```
    public function __construct(ClientInterface $httpClient, RequestBuilder $requestBuilder, Hydrator $hydrator)
    {
        $this->httpClient = $httpClient;
    }
```

Should'nt this be an actual bug and fixed properly, rather than closing ?

**Comment by josiahmann** [comment]
Same issue. Above composer.json fixes didn't work for me.

Laravel 5.7

**Comment by tonythomas01** [comment]
@josiahmann: Sounds like a problem when you are using the buzz adapter  `composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7` However, when I went for the guzzle using something like 
```
		"mailgun/mailgun-php": "3.0.0",
		"nyholm/psr7": "^1.2",
		"guzzlehttp/guzzle": "6.3.3",
		"php-http/guzzle6-adapter": "^2.0.1"
``` 

things just went through nice. I have a pull request  to fix it for the buzz adapter case though https://github.com/mailgun/mailgun-php/pull/660

**Comment by PawelGlow** [comment]
> @josiahmann: Sounds like a problem when you are using the buzz adapter  `composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7` However, when I went for the guzzle using something like
> 
> ```
> 		"mailgun/mailgun-php": "3.0.0",
> 		"nyholm/psr7": "^1.2",
> 		"guzzlehttp/guzzle": "6.3.3",
> 		"php-http/guzzle6-adapter": "^2.0.1"
> ```
> 
> things just went through nice. I have a pull request to fix it for the buzz adapter case though #660

Thank you! This config finally worked for me after 5hrs. The culprit was "nyholm/psr7" - I needed that for the setup to work, otherwise I would get the Argument 1 passed error.

I am surprised how the Mailgun docs are so out of date. Each documentation page practically shows a different way to send a simple email, of which none of them work. Thanks, Github community to for the support!

**Comment by kchoppin** [comment]
Switching to Guzzle also fixed it for me. The docs need updating to not suggest using buzz

**Comment by sanyatuning** [comment]
@DavidGarciaCat pls release it 
Thanks!

**Comment by DavidGarciaCat** [comment]
Hello @sanyatuning 

Please let me check if there's anything missing and if all is good to do then I will prepare a new release.

Thanks,

**Comment by DavidGarciaCat** [comment]
@sanyatuning https://github.com/mailgun/mailgun-php/releases/tag/3.2.0
