### ISSUE TITLE
No PSR-17 url factory found

### ISSUE THREAD

**Issue by krystalcode** [mailgun/mailgun-php#645]
Getting the following error when trying to upgrade to the latest release `3.0.0`.

`No PSR-17 url factory found. Install a package from this list: https://packagist.org/providers/psr/http-factory-implementation`.

`guzzlehttp/psr7` installed and latest version. Added the `kriswallsmith/buzz` package as someone suggested here but still does not work. It would be great to have clear installation instructions/requirements.

**Comment by reddingwebpro** [comment]
I had the same issue, but then I also ran the following composer command and it corrected the issue:

composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7

**Comment by DavidGarciaCat** [comment]
Hi @krystalcode 

As @reddingwebpro pointed out, the implementation needs to be provided by any of the packages that provide it. You can read more on the _README_ file, under the _Installation_ section

https://github.com/mailgun/mailgun-php#installation

Cheers,

**Comment by krystalcode** [comment]
@DavidGarciaCat I'm not sure if I understand the response. As I point out I have both `guzzleshttp/psr7` that provides the implementation (tried with `nyholm/psr7` as well) and also `kriswallsmith/buzz` and I get the error.

**Comment by DavidGarciaCat** [comment]
Hi, @krystalcode 

Can you please paste the whole stack trace of the error?

Cheers,

**Comment by davisben** [comment]
I ran into this error also. Turns out `guzzlehttp/psr7` only has the PSR-17 factory implementations in master, but not any tagged releases.

**Comment by maykino** [comment]
Any update on this? Did anyone get it to work?

**Comment by reddingwebpro** [comment]
Yes, try the composer command I posted above, it appears to resolve the issue.  Been running it flawlessly since I posted that solution back in October.

**Comment by MHamzaRana** [comment]
> I had the same issue, but then I also ran the following composer command and it corrected the issue:
> 
> composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7

Life Saver..

**Comment by Cepishmohnoril** [comment]
> Yes, try the composer command I posted above, it appears to resolve the issue. Been running it flawlessly since I posted that solution back in October.

Works for me! Thanks.
