### ISSUE TITLE
syntax error, unexpected '?'  in Mailgun.php file

### ISSUE THREAD

**Issue by ramkumawathis** [mailgun/mailgun-php#648]
Hello Support Team,
Mailgun working fine at local system but its not working on server.  Showing some error message. The message is :- 
Parse error: syntax error, unexpected '?' in vendor/mailgun/mailgun-php/src/Mailgun.php on line 77
Code :- 
line 77 code is : 
 public function getLastResponse(): ?ResponseInterface
    {
        return $this->responseHistory->getLastResponse();
    }

Server Configuration : 
PHP Version 7.0

Please suggest me. how to resolved it.

**Comment by mstroink** [comment]
Please use php 7.1 or higher

**Comment by trondhuso** [comment]
@ramkumawathis 

The ?ResponseInterface is telling the PHP compiler the return from this function could be a nullable ReponseInterface object. 
This feature was however introduced in 7.1. So in order to remove this error message you have to upgrade to 7.1 or newer.

**Comment by trondhuso** [comment]
You have two options:

1) Update your system to support php 7.1 or higher.

2) Go into the file and change the code to this:
    public function getLastResponse()
        {
            return $this->responseHistory->getLastResponse();
        }

**Comment by zhandos38** [comment]
I use php 7.4.4, but fails

**Comment by DavidGarciaCat** [comment]
The optional type hint `?ResponseInterface` should work with PHP 7.4

Is this still a problem? If so, can you please provide an updated piece of code to reproduce the error?

**Comment by Nyholm** [comment]
Closing this as it is resolved. It is a PHP version issue. Please use composer.
