### ISSUE TITLE
Attaching Data - sendMessage()

### ISSUE THREAD

**Issue by placeposition** [mailgun/mailgun-php#650]
Is there a breaking change to the latest SDK? Previously working methods with sendMessage() the way other open issues describe it no longer work. The 'fix' isn't a fix- it works but refused many parameters and doesn't address the real issue that a previously working function which is still in current documentation gives an error.

**Comment by placeposition** [comment]
$mg->messages()->send() gives me this error when I try to include v:my-var


First argument to "Http\Message\MultipartStream\MultipartStreamBuilder::createStream()" must be a string, resource or StreamInterface


$config = [
	'from'    	=> 	stripslashes($e->outbox_from_name).' <'.$e->outbox_from.'>',
	'to'      	=> 	$e->outbox_to,
	'subject' 	=> 	stripslashes($e->outbox_subject),
	'html'    	=> 	$markup,
	'o:tracking-clicks' => $track_clicks,
	'o:tracking-opens' => $track_opens,
	'v:custId' => $e->cust_id, // <- this kills it
];

**Comment by talovicnedim** [comment]
Same for me.

**Comment by talovicnedim** [comment]
@placeposition convert `$e->cust_id` to string:

You need to have something like this:

`
$config = [
	'from'    	=> 	stripslashes($e->outbox_from_name).' <'.$e->outbox_from.'>',
	'to'      	=> 	$e->outbox_to,
	'subject' 	=> 	stripslashes($e->outbox_subject),
	'html'    	=> 	$markup,
	'o:tracking-clicks' => $track_clicks,
	'o:tracking-opens' => $track_opens,
	'v:custId' => (string) $e->cust_id, // <- this kills it
];
`

and it will work.

**Comment by placeposition** [comment]
@talovicnedim  it does indeed thanks very much.

**Comment by DavidGarciaCat** [comment]
Closing the issue as it seems to be resolved.

Thanks @talovicnedim for providing a solution to the issue
