### ISSUE TITLE
sending with template just creates a message with the templatename

### ISSUE THREAD

**Issue by trondhuso** [mailgun/mailgun-php#651]
I am trying to send an e-mail using the template parameter. When I run the CURL-command I receive an e-mail and all looks good.
When I use the mailgun-php API the message bounces and in the log I can only see the name of the template.

The code is like this:

``

    $mg = Mailgun::create('key-*******'); 

    $fullName = 'john doe';
    $emailAddress = 'john.doe@example.com';
    $mailgunDomain = 'mailgun.example.com';

    $response = $mg->messages()->send($mailgunDomain, [
        'from'    => 'Example <email@example.com>',
        'to'      => $emailAddress,
        'subject' => 'Hello test',
        'template' => 'template_name_to_be_used',
        'h:X-Mailgun-Variables' => "{'URL': $url, 'user': $fullName}"
    ]);

The message is sent of and I get an OK message from the Mailgun-API-server, that is also it.

**Comment by trondhuso** [comment]
The reason why the above code did not work, was because the variables were not inside quotes.

Best approach here is:

    $variables = ['URL' => $url, 'user' => $fullName];

then

    'h:X-Mailgun-Variables'` => json_encode($variables)

**Comment by trondhuso** [comment]
Another thing I have found out is that if you add parameters 'text' => 'Some cool text here' or 'html' => '<b>some html code</b>'
Those will render the name of the template, not the content of the template.
If that is a bug or not, I don't know. Just mentioning it.

**Comment by iamaul** [comment]
> Another thing I have found out is that if you add parameters 'text' => 'Some cool text here' or 'html' => 'some html code'
> Those will render the name of the template, not the content of the template.
> If that is a bug or not, I don't know. Just mentioning it.

It is true. It won't render the value of the object if the output is HTML code otherwise it would be just raw output like (<p><b>hello</b></p>)

**Comment by DavidGarciaCat** [comment]
Just for the record, the JSON strings are supposed to be quoted **always** using double-quotes, so changing them should work:

```php
... => '{"URL": $url, "user": $fullName}'
```

Anyway, the concept of creating an array that becomes a JSON is easier and better for maintenance purposes

Regarding the text, html and templates, I usually have my own templates into the system and render them instead of using a Maingun template (it gives me more flexibility) but I never experienced any problem so far.
