### ISSUE TITLE
Broken $client->routes()->create() on v2.8.1

### ISSUE THREAD

**Issue by iget-master** [mailgun/mailgun-php#652]
Hi,

I've found that on V2.8.1 it's impossible to create a route due to an internal SDK error.

```
    $client->routes()->create([
        "expression" => "match_recipient('abc@xyz.com')",
        "actions" => "store(notify='https://mycallbackurl.com')",
        "description" => "foo bar biz"
    ]);
```

This will always throw an exception:

```
In MultipartStreamBuilder.php line 332:
                                                                                                                                          
  [InvalidArgumentException]                                                                                                              
  First argument to "Http\Message\MultipartStream\MultipartStreamBuilder::createStream()" must be a string, resource or StreamInterface.  
                                                                                                                                          

Exception trace:
  at /var/www/vendor/php-http/multipart-stream-builder/src/MultipartStreamBuilder.php:332
 Http\Message\MultipartStream\MultipartStreamBuilder->createStream() at /var/www/vendor/php-http/multipart-stream-builder/src/MultipartStreamBuilder.php:90
 Http\Message\MultipartStream\MultipartStreamBuilder->addResource() at /var/www/vendor/mailgun/mailgun-php/src/Mailgun/RequestBuilder.php:62
 Mailgun\RequestBuilder->create() at /var/www/vendor/mailgun/mailgun-php/src/Mailgun/Api/HttpApi.php:160
 Mailgun\Api\HttpApi->httpPostRaw() at /var/www/vendor/mailgun/mailgun-php/src/Mailgun/Api/HttpApi.php:144
 Mailgun\Api\HttpApi->httpPost() at /var/www/vendor/mailgun/mailgun-php/src/Mailgun/Api/Route.php:91
 Mailgun\Api\Route->create() at /var/www/my-script.php:60
```

**Comment by iget-master** [comment]
Following stack trace for this issue, I found that:

The 4th parameter to the `create()` method is `$priority` and it expects to receive an `integer` (see line 82 bellow):

https://github.com/mailgun/mailgun-php/blob/4af0346851914ae0d9a58bf9ddf17eb48f6498c8/src/Mailgun/Api/Route.php#L77-L82

Now following `httpPost()` method, let's stop on `RequestBuilder@create()` method:

https://github.com/mailgun/mailgun-php/blob/4af0346851914ae0d9a58bf9ddf17eb48f6498c8/src/Mailgun/RequestBuilder.php#L55-L63

Here it gets the parameters and one of it is `priority` with value of `0` (as integer).

On line 62 it calls the MultipartStreamBuilder@addResource() (from `php-http/multipart-stream-builder` package).

Here is where the problem occurs: that method only accept: `"string|resource|StreamInterface"`

# My fix suggestion

The fix for this issue is very simple: the `priority` parameter on Route@create() method must be converted to string:

Changing the line 85 from

            'priority' => $priority,

to

            'priority' => (string) $priority,

fixes the issue.

**Comment by iget-master** [comment]
Also, this is a regression, but I'm not sure which version caused it.

I'm sure that v2.8.1 is affected.

I'm **not** sure if v3.0.0 is affected.

**Comment by iget-master** [comment]
For who need, I'm using following workaround to don't need to change any code in vendor or create a alternate package while this is not merged:

```
        // @workaround
        // @todo: Remove this workaround after merging of https://github.com/mailgun/mailgun-php/pull/653
        $params = [
            'priority' => "0",
            'expression' => $expression,
            'action' => $actions,
            'description' => $description,
        ];

        $routes = $mailgunClient->routes(); // Replace this by your mailgun client variable
        $publicHttpPost = new \ReflectionMethod(\Mailgun\Api\Route::class, 'httpPost');
        $publicHttpPost->setAccessible(true);
        $response = $publicHttpPost->invoke($routes, '/v3/routes', $params);

        $publicHydrateResponse = new \ReflectionMethod(\Mailgun\Api\Route::class, 'hydrateResponse');
        $publicHydrateResponse->setAccessible(true);
        $response = $publicHydrateResponse->invoke($routes, $response, CreateResponse::class);

        // $response will contain the exact same response from $mailgunClient->routes()->create() method.
        // @end-workaround
```

**Comment by DavidGarciaCat** [comment]
Mailgun Support team has reached me again.

Given I didn't get a failing example to prove the error and given the functional API calls that they provided (that I attached five days ago), the support case is now resolved.

Thus, there's no need to keep this Pull Request open, as it was proved not to be a requirement, and (specially) because none of the stakeholders of this update posted a failing scenario to follow up this case with their support team.

Integers seem to be a functional case, and there's no need to force them as a string.

I am closing both the Issue and the Pull Request.

**Comment by hkmsadek** [comment]
I am facing this same problem, what is the solution?

**Comment by iget-master** [comment]
@DavidGarciaCat I gave the failing example. Or you are trying to reproduce on a different version, or the mailgun API changed. Keep in mind that this issue exists for almost a year.

**Comment by iget-master** [comment]
@hkmsadek See this comment: https://github.com/mailgun/mailgun-php/issues/652#issuecomment-567190676

**Comment by DavidGarciaCat** [comment]
We might need further testing, as seems hard to understand how this can be a problem, especially with the provided the examples that the Mailgun Support team itself sent and they were shared in the PR https://github.com/mailgun/mailgun-php/pull/653#issuecomment-677858637

Just out of curiosity: did you check if this is still a problem on v3?

**Comment by ethaniel** [comment]
I can recreate this bug if the text is simply an integer:

```
	$mg = Mailgun::create('key-KEY', 'https://api.eu.mailgun.net'); // For EU servers

	$mg->messages()->send('mailgun.domain.com', [
	'from'    => "SITE <from@from.com>",
	'to'      => "to@to.com",
	'subject' => "subject",
	'text'    => 123
	]);
```

**Comment by DavidGarciaCat** [comment]
The `text` field is the `plain/text` body of the email, which means it's supposed to be a `string` instead of an `integer`.

**Comment by ethaniel** [comment]
Yep, but it still dumps the same error instead of what you mentioned.

**Comment by vk-sourcefuse** [comment]
Same error

**Comment by chispitaos** [comment]
same error here
I've just update mailgun and all the dependencies and I can't send anymore

![image](https://user-images.githubusercontent.com/51212459/128617668-3900702c-e712-4e07-836e-38f1192d0df0.png)

Error:

Uncaught InvalidArgumentException: First argument to "Http\Message\MultipartStream\MultipartStreamBuilder::createStream()" must be a string, resource or StreamInterface. in /vendor/php-http/multipart-stream-builder/src/MultipartStreamBuilder.php:353
