### ISSUE TITLE
inline images in 3.0 through european server

### ISSUE THREAD

**Issue by azapater** [mailgun/mailgun-php#654]
We have updated to the last mailGun php 3.0 library in one of our projects because we wanted to start using the EU servers. After following the upgrade information and updating our code, we are experiencing a bug we can't find a solution for. We use inline images attached to the email, and following the same rules applied in the previous library version, the images are not attached. 

We pass the 'inline' param at the end of the call in an array with all the images. Here's an example:

```
$mg = Mailgun::create(MAILGUN_KEY, 'https://api.eu.mailgun.net'); 
$domain = OUR_DOMAIN;
$result = $mg->messages()->send($domain, $email, array('inline' => $images));
```

The email is sent but without any images. This format used to work in the previous library version and we can't find any info related with this issue.

**Comment by uavn** [comment]
@azapater, I tried to do the same and I was able to successfully send email with inline images using the following code:

```
$mg = Mailgun::create($key, 'https://api.mailgun.net');

$resp = $mg->messages()->send('MY_DOMAIN', [
	'from' => 'mailgun-sdk@uartema.com',
	'to' => 'artbonvic@gmail.com',
	'subject' => 'The PHP SDK is awesome! SDK Test',
	'text' => 'It is so simple to send a message.',
    'inline' => [
        ['filePath'=>'@./dell0.jpg', 'filename'=>'test.jpg']
    ]
]);
```
If to look on your code:

```
$mg = Mailgun::create(MAILGUN_KEY, 'https://api.eu.mailgun.net'); 
$domain = OUR_DOMAIN;
$result = $mg->messages()->send($domain, $email, array('inline' => $images));
```
We can see, that you are trying to pass images as third argument to the method send, instead of them to be part of $email.

**Comment by DavidGarciaCat** [comment]
Thanks @uavn  for providing a functional server

The email sending functionality including inline images should not be a problem either using an EU or US server.

Closing this issue
