### ISSUE TITLE
Set domain for the EU correctly, but get mailing lists from US.

### ISSUE THREAD

**Issue by jonathanpochini** [mailgun/mailgun-php#655]
Hi guys

Hope this can be fixed somehow...

I set up the code correctly to point to the EU server:

`$mg = Mailgun::create('my_api_key', 'https://api.eu.mailgun.net/v3/my_domain');`

and if I check the domains...

` $domains = $mg->domains()->index();
var_dump($domains);`

...everything works fine.
But if I want to get the mailing lists associated to domain in the EU server...

`$result = $mg->get("lists/pages", array(
    'limit'      =>  5
));
var_dump($result);`

I'm actually getting the mailing list associated with the domain in the US server...

Any idea how can I get the desired result?
I've lost a day yesterday trying to sort this issue...

**Comment by 1stevengrant** [comment]
which package version do you have installed?

**Comment by jonathanpochini** [comment]
After experiencing the issue the first times, I've reinstalled everything in another folder to test it (so I believe it's the last one).

**Comment by uavn** [comment]
@jonathanpochini 
try this:
```
$mg = Mailgun::create($key, 'https://api.eu.mailgun.net');
$domains = $mg->mailingList(['limit' => 5])->pages()->getLists();
```
or for US:
```
$mg = Mailgun::create($key, 'https://api.mailgun.net');
$domains = $mg->mailingList(['limit' => 5])->pages()->getLists();
```

**Comment by DavidGarciaCat** [comment]
@uavn is correct: the `Usage` section of the [README](https://github.com/mailgun/mailgun-php#usage) file shows the 2nd argument of the named constructor should include just the server, not the whole URL of the resource.

Closing this issue as it seems to be a development bug.
