### ISSUE TITLE
specific attachment to each recipient in batch emails

### ISSUE THREAD

**Issue by mirzahaseeb** [mailgun/mailgun-php#657]
i want to give array of attachment files where each file is related to one recipient in batch emails. for now we can send email to many recipients but attach file remains same for all emails.

**Comment by DavidGarciaCat** [comment]
I never tried a case like the one you are saying, buy maybe this solution works for you? https://github.com/mailgun/mailgun-php/issues/671

Cheers,

**Comment by Nyholm** [comment]
Closing due inactvity.
