### ISSUE TITLE
Webhook. Inconsistent info between code comment and documentation

### ISSUE THREAD

**Issue by victor-david** [mailgun/mailgun-php#658]
src/Api/Webhook.php says, regarding the **verifyWebhookSignature()** method that:

> If this function returns FALSE, you must not process the request.
> You should reject the request with status code 403 Forbidden.

However, according to the documentation:

https://documentation.mailgun.com/en/latest/user_manual.html#webhooks

a 403 will cause MailGun to retry the request

> - If Mailgun receives a 200 (Success) code it will determine the webhook POST is successful and **not retry**.
> - If Mailgun receives a 406 (Not Acceptable) code, Mailgun will determine the POST is rejected and **not retry**.
> - For _any other code_, Mailgun will retry ... according  to schedule below...

I'm not sure which answer is correct, 403 or 406. In my app, I issue a 406 according to the docs. Hopefully, you can clarify and fix the code comment or the docs. Thanks.

**Comment by victor-david** [comment]
Followup: I sent a single message that bounced and had my web hook reply with 403. Here are the results:

![mailgun](https://user-images.githubusercontent.com/17145322/71332584-55ea5300-24fc-11ea-9c5c-a1172b912aab.jpg)

This test demonstrates two things:

1.  With a 403 response, MailGun continues to retry. The documentation is correct in this respect. When I changed the response to 406, MailGun stopped its retries.
2. From the timestamps, you can see that the documentation is not quite right regarding the retry intervals.

> Mailgun will retry (other than for delivery notification) during 8 hours at the following intervals before stop trying: 10 minutes, ~~10 minutes~~, 15 minutes, 30 minutes, 1 hour, 2 hour and 4 hours.

**Comment by DavidGarciaCat** [comment]
The `403 Forbidden` status code seems to be related to a potential case of invalid credentials.

Can you please review your credentials and confirm if this is still a problem?

Thanks,

**Comment by victor-david** [comment]
This doesn't have anything to do with my credentials. I was just pointing out the inconsistency in the documentation in case Mail Gun wants to update it.

**Comment by DavidGarciaCat** [comment]
The documentation doesn't provide (yet) the updated behaviour using the current version of the SDK.

I'm closing this issue due to we already have other issues raising an inconsistency between the SDK and the Documentation page.
