### ISSUE TITLE
Call to undefined method Mailgun\Mailgun::post()

### ISSUE THREAD

**Issue by dissolvdgrl** [mailgun/mailgun-php#659]
I am trying to post to a mailing list via a form in my Laravel 6.9 app, I've followed the PHP documentation and I get an error `Call to undefined method Mailgun\Mailgun::post()`

I had to google around to figure out that I must use `Mailgun::create` instead of `new Mailgun`, it doesn't reflect in the docs.

My function body looks like this: 
`$mgClient = Mailgun::create('my-key', 'https://api.eu.mailgun.net');

            $mailingList = 'my-list@domain.com';
            $mgClient->post("lists/$mailingList/members", array(
                'address'     => $recipientAddress,
                'description' => 'Form Opt In',
                'subscribed'  => true    
            ));

Is there different syntax to post to a mailing list now?

**Comment by DavidGarciaCat** [comment]
Hi @dissolvdgrl 

the `post` method was in use when the SDK v2 was here, the new v3 SDK uses helpers to access to the resources. Try with this method and provide the required data:

```
$mgClient->mailingList()->create(...);
```

Your IDE should help you with the calls, providing the helpers that you need to get access to all the functions.

Cheers,

**Comment by dissolvdgrl** [comment]
Thanks, I will test this within the next day and edit this comment with feedback.
