### ISSUE TITLE
name cannot be null adding to a mailing list

### ISSUE THREAD

**Issue by 1stevengrant** [mailgun/mailgun-php#662]
Consider this simple Laravel controller that attempts to add an email to a mailing list

https://gist.github.com/1stevengrant/5ff8a382719cdc5118bff874cdcaafa5

When I don't pass a name into the create method, we land with this error

```
[2020-01-20 15:55:48] local.ERROR: First argument to "Http\Message\MultipartStream\MultipartStreamBuilder::createStream()" must be a string, resource or StreamInterface. {"exception":"[object] (InvalidArgumentException(code: 0): First argument to \"Http\\Message\\MultipartStream\\MultipartStreamBuilder::createStream()\" must be a string, resource or StreamInterface. at /Users/steven/Sites/sermontranscriber/vendor/php-http/multipart-stream-builder/src/MultipartStreamBuilder.php:332)
```

For now (because it suits) I can add a static value of 'name' because I don't necessarily need it, but it makes the data dirty. I've attempted to even pass a null value but it seems it always wants a string.

I'm using the latest PHP package. From my last few days using the docs and PHP package, I've found them to be at odds with one another in terms of what the docs say and what methods are actually available.

Any guidance?

I got this from your support team

```
Hello Steven,

Thanks for reaching out to Mailgun Support.  After further testing on our side, we do believe this is a bug in the PHP-SDK and recommend opening an issue in Github repository for the PHP developers maintaining the SDK to address. The root of the issue seems to stem from the HTTP client being used.  It does not accept null values for parameters and an empty string is not accepted by our API, causing the failures you are seeing for this particular call.

Let us know if you see any further issues we can assist with.

Thank You,
Levi@MG
```

**Comment by DavidGarciaCat** [comment]
This is now fixed on `master`
