### ISSUE TITLE
How to get json instance of object in suppressions bounces API  

### ISSUE THREAD

**Issue by ajaybairagi** [mailgun/mailgun-php#663]
[Hello,]
I am calling bounces API using PHP but return `Mailgun\Model\Suppression\Bounce\IndexResponse` Object
How to get in json format 

```php
require 'vendor/autoload.php';
use Mailgun\Mailgun;

$mgClient = Mailgun::create('PRIVATE_API_KEY', 'https://API_HOSTNAME');
$domain   = 'YOUR_DOMAIN_NAME';
$result = $mgClient->suppressions()->bounces()->index($domain);
```

Return 

```
Mailgun\Model\Suppression\Bounce\IndexResponse Object
(
    [items:Mailgun\Model\Suppression\Bounce\IndexResponse:private] => Array
        (
            [0] => Mailgun\Model\Suppression\Bounce\Bounce Object
                (
                    [address:Mailgun\Model\Suppression\Bounce\Bounce:private] => bounce1@gmail.com
                    [code:Mailgun\Model\Suppression\Bounce\Bounce:private] => 550
                    [error:Mailgun\Model\Suppression\Bounce\Bounce:private] => this is bounce first 
                    [createdAt:Mailgun\Model\Suppression\Bounce\Bounce:private] => DateTimeImmutable Object
                        (
                            [date] => 2018-05-21 10:16:49.000000
                            [timezone_type] => 3
                            [timezone] => UTC
                        )
                )
        )

    [paging:Mailgun\Model\Suppression\Bounce\IndexResponse:private] => Array
        (
            [first] => https://api.mailgun.net/v3/sandboxa311.mailgun.org/bounces?limit=100
            [last] => https://api.mailgun.net/v3/sandboxa311.mailgun.org/bounces?page=last&limit=100
            [next] => https://api.mailgun.net/v3/sandboxa311.mailgun.org/bounces?page=next&address=ffff%40example.com&limit=100
            [previous] => https://api.mailgun.net/v3/sandboxa311.mailgun.org/bounces?page=previous&address=&limit=100
        )
)
```

Thanks 
Ajay Bairagi

**Comment by DavidGarciaCat** [comment]
Hi @ajaybairagi 

By default, the SDK maps the returned JSON string through an object so we can use the getters that simplify the development for less experienced developers and also provides better integration with the IDEs.

You can pass the `ArrayHydrator` instead of keeping the one loaded by default, and then you can use the `json_encode` function to keep the result as a JSON string.

Alternatively, you can send a Pull Request with a new `JsonHydrator` where we can return the content as retrieved by the API call.

Cheers,

**Comment by nguyen-tam** [comment]
> Hi @ajaybairagi
> 
> By default, the SDK maps the returned JSON string through an object so we can use the getters that simplify the development for less experienced developers and also provides better integration with the IDEs.
> 
> You can pass the `ArrayHydrator` instead of keeping the one loaded by default, and then you can use the `json_encode` function to keep the result as a JSON string.
> 
> Alternatively, you can send a Pull Request with a new `JsonHydrator` where we can return the content as retrieved by the API call.
> 
> Cheers,

Very bad reply, you should provide a code example instead of only explaination
