### ISSUE TITLE
webhooks and url parameter

### ISSUE THREAD

**Issue by jackfoust** [mailgun/mailgun-php#666]
Am I missing something or does the PHP library for Mailgun not support the 3 URL parameters that other languages do? I don't see a way to use `$mailgun->webhooks()->create('example.com', 'accept', 'https://www.exmple.com/webhook');` to include more than 1 URL.

**Comment by findsynonyms** [comment]
Looking for it!

**Comment by DavidGarciaCat** [comment]
There is a (now merged) pull request to fix this issue https://github.com/mailgun/mailgun-php/pull/675

There are no tags yet so, in the meantime, you can use the master branch - but a new tag should come soon
