### ISSUE TITLE
Batch sending with Laravel

### ISSUE THREAD

**Issue by ChrAus** [mailgun/mailgun-php#667]
Hello guys,

since the laravel integration is archived and the batch sending does not work for me, I would like to implement this SDK into Laravel directly.
Has anyone here done this before? 
I am just looking for batch sending with user variables.

Regards Christoph

**Comment by DavidGarciaCat** [comment]
Hi @ChrAus 

There are some closed issues with examples for sending batch emails:

https://github.com/mailgun/mailgun-php/issues/671

https://github.com/mailgun/mailgun-php/issues/611

https://github.com/mailgun/mailgun-php/issues/610

Cheers,

**Comment by ChrAus** [comment]
Yes, cheers. I think I sorted it out.

Regards
