### ISSUE TITLE
Mailgun Version API V4 Integration

### ISSUE THREAD

**Issue by AndyMental** [mailgun/mailgun-php#678]
Do we have integration of Mailgun API v4 to be done soon.

**Comment by DavidGarciaCat** [comment]
Hi @AndyMental 

Mailgun API got a set of new versions that the community applied to release the v3 of the SDK and there are still some missing features that didn't exist when we were working on the v3 Roadmap

An update to v4 might be useful, indeed, but given this is an OpenSource project under the MIT license (so no one gets paid and we work on it when we have time to spare), we cannot commit to a specific date.

You are more than welcome if you want to send new Pull Requests with the required updates, and once all changes are implemented, we can tag a new `4.x.x` release.

Cheers,

**Comment by DavidGarciaCat** [comment]
It seems that, at the moment, most of the API docs are still referring to the `API v3`. There's maybe one or two exceptions targeting the `API v4`, which I believe were already implemented. Thus, I believe we can close this issue.

If this becomes a problem in the future, we can open a new issue to track the progress.
