### ISSUE TITLE
Specifying o:tag causes Mailgun to add unsubscribe headers

### ISSUE THREAD

**Issue by mdb-mdb** [mailgun/mailgun-php#682]
Spent quite some time looking for a solution so I thought I'd create an issue for it: 

Recently Mailgun started adding unsubscribe headers to e-mails when the "o:tag" parameter is specified.  

This behavior is confirmed by Mailgun support:
<blockquote>We have reviewed this in more detail, and we can confirm this is expected.  The use of tags is the foundation of campaign-based emails, and due to various changes in the email industry, certifications, and laws a List-Unsubscribe header is required with more types of email.  It's a relatively recent change that was made, but we can confirm the use of tags will add the List-Unsubscribe.</blockquote>

I noticed this when my ProtonMail webclient started adding an "unsubscribe" button to my Mailgun e-mails which is not desired when sending transactional e-mails.(see https://protonmail.com/support/knowledge-base/auto-unsubscribe/)

**Comment by DavidGarciaCat** [comment]
Hi @mdb-mdb 

As you have stated as per the Mailgun support team:

> We have reviewed this in more detail, and we can confirm this is expected.

So, if `this is expected` and it's not hardcoded as part of the SDK, then we can't do anything to support, as it must be included on the Mailgun servers when processing your request to apply with the legal regulations.

Cheers,
