### ISSUE TITLE
Incorrect exception thrown for Bounce->show()

### ISSUE THREAD

**Issue by stefanoboggian** [mailgun/mailgun-php#683]
Hi,

using SDK version 3.0.0 :

`$mg = Mailgun::create(API_KEY);
$mg->suppressions()->bounces()->show(MY_DOMAIN, 'email@address.com');`

looks like if the email address is not listed in bounced addresses, the API responds correctly with

{"message":"Address not found in bounces table"}

but the SDK throws a

Mailgun \ Exception \ HttpClientException

**Comment by DavidGarciaCat** [comment]
This happens because the status code is not between 200 and 299. The SDK doesn't try to determinate if the request/response was a success by inspecting the JSON but the status code that the API sends.
