### ISSUE TITLE
Paginating events without reference to the full previous response

### ISSUE THREAD

**Issue by timvdalen** [mailgun/mailgun-php#691]
I am trying to paginate events in a UI.
As such, I only want to request the next page of events when the user makes the next page request.

Right now, it looks like I'd have to serialize the previous response somewhere and rehydrate it on the next request cycle to get access to the next page.
I can get access to the underlying URL of the next page, but then I'd have to make that request myself (and I'd basically escape the client library).

Is there a way to achieve this currently?

**Comment by uavn** [comment]
@timvdalen 
you can do like this:
```
$mg = Mailgun::create($key);

$eventsResponse = $mg->events()->get($domain);
$nextPageEventsResponse = $mg->events()->nextPage($eventsResponse);
```

**Comment by timvdalen** [comment]
@uavn the problem is that I don't have access to the previous `$eventsRepsonse`, as I'm doing this interactively.
The way the client library is currently set up means that I would have to re-request `n` pages to load page `n+1`.

**Comment by DavidGarciaCat** [comment]
Hi @timvdalen 

The solution that @uavn provided is the right one, as you can also see on the Mailgun Docs page for the most basic `curl`, where the links for the previous and next page are also there, as part of the response

https://documentation.mailgun.com/en/latest/api-events.html#examples

The point here is that no one knows how many events have happened and, thus, no one can just concatenate one call after another until who knows when to retrieve thousands (or millions) of records.

The pagination is here precisely to solve the problem, and it aims to match with the API docs.

Cheers,

**Comment by DavidGarciaCat** [comment]
@timvdalen quick question: did you consider running several calls and cache the content, so when you actually change the page then the cached content is presented? I don't think it's ideal (especially if you have active movement of emails and events coming from them) but it might be an easy way to pre-load content.

**Comment by Nyholm** [comment]
Closing due inactivity.

**Comment by timvdalen** [comment]
This is still very relevant to me. This functionality is not available in the SDK, but it is available in the API.

**Comment by Nyholm** [comment]
That is correct. 
I would ask you to provide a PR or don't use the sdk for this feature specifically.
