### ISSUE TITLE
Mailing List Member Name Cannot be NULL (fix included)

### ISSUE THREAD

**Issue by AlmostInteractive** [mailgun/mailgun-php#692]
https://github.com/mailgun/mailgun-php/blob/5975310f0ee1d2e26d06941584244415904ca070/src/Api/MailingList/Member.php#L98

The default value for `name` is `NULL` but this is not allowed by the stream creator. Instead, including the name in the params only if it's not null will allow the member to be created without a name value.  Or find another way to fix it, I'm not picky.

```
    public function create(string $list, string $address, string $name = null, array $vars = [], bool $subscribed = true, bool $upsert = false)
    {
        Assert::stringNotEmpty($list);
        Assert::stringNotEmpty($address);
        Assert::nullOrStringNotEmpty($name);

        $params = [
            'address' => $address,
            'vars' => \json_encode($vars),
            'subscribed' => $subscribed ? 'yes' : 'no',
            'upsert' => $upsert ? 'yes' : 'no',
        ];

        if ($name) {
            $params['name'] = $name;
        }

        $response = $this->httpPost(sprintf('/v3/lists/%s/members', $list), $params);

        return $this->hydrateResponse($response, CreateResponse::class);
    }
```

**Comment by codepilotnl** [comment]
I'm having the same issue,  the name parameter cannot be null when creating a new Mailing List Member. It seems this bug has also been reported in #662.

**Comment by DavidGarciaCat** [comment]
This is now fixed on `master`
