### ISSUE TITLE
Issue with creating suppression using current method for obtaining MG client

### ISSUE THREAD

**Issue by trstaley** [mailgun/mailgun-php#696]
For a long time we have always obtained a MG client in php using the code below:

`use Mailgun\Mailgun;
$mailgun_client = new Mailgun(MAILGUN_API_KEY);`

We tried to create a suppression by using the following code:
`$result = $mailgun_client->suppressions()->bounces()->create(MAILGUN_DOMAIN, $email_address);`

However, when issuing this call, we received the following error:
`Argument 1 passed to Mailgun\Api\Suppression::__construct() must be an instance of Http\Client\HttpClient, null given, called in /vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php on line 399 and defined in /vendor/mailgun/mailgun-php/src/Mailgun/Api/Suppression.php:46`

After contacting MG chat, they advised we use a different method for obtaining a MG client as shown below:

`$mailgun_client  = Mailgun::create(MAILGUN_API_KEY, 'https://api.mailgun.net');`

This method did allow for the suppression call to work properly,
We are not sure if there is a bug in MG using the connect method we are using, or if there is a reason we must use the connect method the MG support tech supplied.

Can someone help us understand the issue; and should we modify all our old connect method statements to the the new one we were provided?

**Comment by DavidGarciaCat** [comment]
Mailgun as a service provider offers both API and SMTP options to send emails. This SDK is an open-source project, offered under the MIT license. So, "officially" and "strictly speaking" their support team don't maintain this repo, but the community is always welcome to send new Pull Requests.

Having said that, Mailgun SDK was updated several months ago, and the newer version doesn't expect you to use the constructor (`new Mailgun()`) but to use a named constructor instead (`Mailgun::create()`). You can see these details in the readme, just browsing the landing page of this repository:

https://github.com/mailgun/mailgun-php#usage

The SDK also offers now HttPlug support so there's no need to use a very specific HTTP Client. Please check the install section for further information

https://github.com/mailgun/mailgun-php#installation

Hope it helps.

**Comment by trstaley** [comment]
Thanks David,  we will move all our connection requests to the new method.  Sure would be nice if MG sent out an alert to its clients, letting us know about this change.
