### ISSUE TITLE
Not receiving Events Info

### ISSUE THREAD

**Issue by karquieta** [mailgun/mailgun-php#697]
Hello, i'm traying to get info about the sending logs from my mailgun domain but when I checked the $result content, it is empty. The API KEY and the domain are correct, the email I'm using is also listing logs in the mailgun console.

Here my code.

            // Instantiate the client.
            $mgClient    = Mailgun::create("API KEY");
            $domain      = "domain.com";
            $queryString = array(
                "begin"        => "Wed, 1 Jan 2020 09:00:00 -0000",
                "ascending"    => "yes",
                "limit"        =>  25,
                "pretty"       => "yes",
                "recipient"    => "email@example.com"
            );

            // Issue the call to the client.
            $result = $mgClient->events()->get($domain, $queryString);

Edit: I added to $result the method getItems(); So it can be seen like this

            $result = $mgClient->events()->get($domain, $queryString)->getItems();

But, same thing, when I see the $result content I can see the quantity of events that match that email, but are empy objects.

           data: [
                 0: {}
                 1: {}
                 ....
           ]

**Comment by DavidGarciaCat** [comment]
Hi there,

Can you please check the returned response using the `ArrayHydrator` as per the Readme example?

https://github.com/mailgun/mailgun-php#response

Cheers,

**Comment by DavidGarciaCat** [comment]
Hi @karquieta 

Did you try setting the `ArrayHydrator`? Did it solve your problem?

Cheers,

**Comment by Nyholm** [comment]
Closing due inactivity.
