### ISSUE TITLE
Code for campaign API missing?

### ISSUE THREAD

**Issue by ketanshah79** [mailgun/mailgun-php#70]
Hi,

I was wondering if this SDK supports the campaign API? http://documentation.mailgun.com/api-campaigns.html

I skimmed over the repository but could not find anything relevant?

Thank you,
- Ketan

**Comment by dbebawy** [comment]
+1

**Comment by lezhnev74** [comment]
+1

**Comment by Nyholm** [comment]
Hey. Sorry for the very late response. 

Mailgun (@pirogoeth) could correct me if Im wrong but the Campaign API is deprecated in favor for the Tag API.
