### ISSUE TITLE
The endpoint you've tried to access does not exist

### ISSUE THREAD

**Issue by ezyone123** [mailgun/mailgun-php#71]
I am getting this error when trying to send a simple email. I have double checked my domain as that was the solution for the few other people who had the same issue, I'm sure its the same one I used to set up my malign account.  

      <br />
      <b>Notice</b>:  Array to string conversion in <b>/var/www/html/php_libs/vendor/mailgun/mailgun-     php/src/Mailgun/Mailgun.php</b> on line <b>36</b><br />
     <br />
     <b>Fatal error</b>:  Uncaught exception 'Mailgun\Connection\Exceptions\MissingEndpoint' with message 'The endpoint you've tried to access does not exist. Check your URL.' in /var/www/html/php_libs/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:133
     Stack trace:
     #0 /var/www/html/php_libs/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(90): Mailgun\Connection\RestClient-&gt;responseHandler(Object(Guzzle\Http\Message\Response))
     #1 /var/www/html/php_libs/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(80): Mailgun\Connection\RestClient-&gt;post('Array/messages', Array, Array)
     #2 /var/www/html/php_libs/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(36): Mailgun\Mailgun-&gt;post('Array/messages', Array, Array)
     #3 /var/www/html/api/newuser.php(136): Mailgun\Mailgun-&gt;sendMessage(Array, Array)
     #4 {main}
     thrown in <b>/var/www/html/php_libs/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php</b> on line <b>133</b><br />

my code:

     require '/var/www/html/php_libs/vendor/autoload.php';
     use Mailgun\Mailgun;
     $mg = new Mailgun("key-3f2814XXXXXXX");
     $domain = 'stnatoday.com';
     $mg->sendMessage($domain, array('from'    => 'me@stnatoday.com', 
                                'to'      => trim($_REQUEST['identifier']), 
                                'subject' => 'The PHP SDK is awesome!', 
                                'text'    => 'It is so simple to send a message.'));

**Comment by CupOfTea696** [comment]
Go to the RestClient.php file and edit it where the error originated:

```````
		elseif($httpResponseCode == 400){
            die(var_dump((string) $responseObj->getBody()));
			throw new MissingRequiredParameters(EXCEPTION_MISSING_REQUIRED_PARAMETERS);
		}
		elseif($httpResponseCode == 401){
            die(var_dump((string) $responseObj->getBody()));
			throw new InvalidCredentials(EXCEPTION_INVALID_CREDENTIALS);
		}
		elseif($httpResponseCode == 404){
            die(var_dump((string) $responseObj->getBody()));
			throw new MissingEndpoint(EXCEPTION_MISSING_ENDPOINT);
		}
```````

This way you can actually see the response from the request to Mailgun. It might help you figure out what went wrong. 
Mailgun should update their package to show this info in the error. I'm gonna make this a bit better looking and create a pull request.

**Comment by ezyone123** [comment]
It says domain not found. Is the domain I use not the one listed in : I have exactly that (stnatoday.com) listed as my domain
![screen shot 2015-01-13 at 5 41 17 pm](https://cloud.githubusercontent.com/assets/2058024/5730831/af05ffc4-9b4b-11e4-8922-e885354abae0.png)

**Comment by ezyone123** [comment]
Turns out I had not verified my account. Got it figured out, thanks!

**Comment by CupOfTea696** [comment]
You're welcome!

**Comment by mnpenner** [comment]
Looks like the error messages were never updated. I just downloaded the SDK and got this cryptic message today. I thought I had to supply the 2nd arg to the c'tor, but that led to a whole new set of problems.

**Comment by andrebruton** [comment]
Is it not possible for the PHP library code to return an error instead of a fatal error. I do not want fatal errors in a production environment.

I check for returned code and if 200 then i know the email has been delivered to Mailgun.

**Comment by mnpenner** [comment]
@andrebruton You can always put a `try {} catch {}` around it.

This error message should still be updated to say "This domain has not been verified yet" or something, if that is indeed the problem.

**Comment by andrebruton** [comment]
Thank you. Tried it and I get a message back. Does this look good?

`    try {
      # Now, compose and send your message.
      $result=$mg->sendMessage($domain, array('from'     => 'info@mg.domain.co.za', 
                                              'to'       => 'user@email.com', 
                                              'subject'  => $subject, 
                                              'text'     => $message,
                                              'html'     => $message_html
                                              ));
  
    if ($result->http_response_code == 200) {

      echo "Email Successfully Sent<br>";

      echo "<pre>";
      print_r($result);
      echo "</pre>";

      echo "Result: " . $result->http_response_code . "<p>";
  
    } else {
       echo "Error sending email<br>";
    }
  
    } catch(Exception $e) {
      // Mandrill errors are thrown as exceptions
      echo "Error occured: " . $e->getMessage() . "<br>";
    }
`
