### ISSUE TITLE
No support for newer webhook types

### ISSUE THREAD

**Issue by ash-jc-allen** [mailgun/mailgun-php#715]
Sorry in advance if I'm completely wrong on this one!

I'm trying to fetch the webhooks for a domain at the moment using the following code:

```php
$this->mailgun->webhooks()->index($domainGoesHere);
```

When I use that, none of the webhooks seem to be set in the ``` IndexResponse ``` class that's returned. If I check each webhook individually using the following code, they all return as expected:

```php
$this->mailgun->webhooks()->show($domainGoesHere, 'delivered');
```

As an example for the 'delivered' webhook, it looks like ` deliver ` is the legacy hook and ` delivered ` is the newer name for it. But in the ` IndexResponse::create() ` method, it's only checking for the older legacy hooks to build up the model. Is there are a newer way of getting the webhooks that I've completely missed?

If not, if this is a change that you think might need adding, I'd be happy to try and put together a PR for this :smile:

Reference to IndexResponse: https://github.com/mailgun/mailgun-php/blob/1fd018d61c4a2034a69525d07a08075dda84f792/src/Model/Webhook/IndexResponse.php#L33

**Comment by DavidGarciaCat** [comment]
Hello @ash-jc-allen 

There is this PR (https://github.com/mailgun/mailgun-php/pull/609 Support for new webhook endpoints) that I still need to do a final code review, maybe a bit of testing and then merge it, so we can make them publicly available through a new tag.

I will try to do it ASAP, as there are another 2 updates that I need to merge too.

Cheers,

**Comment by ash-jc-allen** [comment]
Perfect! I did see that PR and thought it might have solved this issue but wasn't 100% sure.

I'll close this and wait for a new tag. Cheers!
