### ISSUE TITLE
Support for Guzzle 7 (and therefore Laravel 8)

### ISSUE THREAD

**Issue by jonaslm** [mailgun/mailgun-php#718]
Any plans regarding support for Guzzle 7? As of now, this cannot be installed together with Laravel 8, since that has a dependency on Guzzle 7.

Specifically, composer compains that
```
php-http/guzzle6-adapter v1.1.1 requires guzzlehttp/guzzle ^6.0 [...] but these conflict with your requirements or minimum-stability
```

**Comment by DavidGarciaCat** [comment]
Mailgun does not support any specific HTTP client, but the HttPlug component. If there's a necessity of upgrading the HttPlug component, it can be done, but the Guzzle 7 support belongs to a Guzzle 7 adapter, that integrates the HttPlug dependencies as we do.

**Comment by DavidGarciaCat** [comment]
Guzzle 7 Adapter (https://packagist.org/packages/php-http/guzzle7-adapter) requires (so, implements):
- `php: ^7.2 | ^8.0`
- `guzzlehttp/guzzle: ^7.0`
- `php-http/httplug: ^2.0`
- `psr/http-client: ^1.0` ← match

Mailgun SDK (https://packagist.org/packages/mailgun/mailgun-php) requires (so, implements):
- `php: ^7.1`
- `php-http/client-common: ^1.9 || ^2.0`
- `php-http/discovery: ^1.6`
- `php-http/multipart-stream-builder: ^1.0`
- `psr/http-client: ^1.0` ← match
- `webmozart/assert: ^1.6`

Knowing that the required HTTP Client package is shared (`psr/http-client: ^1.0`) by the SDK and the Guzzle 7 Adapter, is this still causing you a problem?

Maybe we should know how you install the dependencies to decide if we really need to update the SDK

:thinking:

**Comment by jonaslm** [comment]
I believe the dev dependency is the issue here, as `mailgun/mailgun-php` defines
`php-http/guzzle6-adapter: ^1.0 || ^2.0` in its require-dev, and `php-http/guzzle6-adapter` in turn requires `guzzlehttp/guzzle: ^6.0`.

**Comment by DavidGarciaCat** [comment]
the `require-dev` is used as part of the SDK development, so devs can use the SDK calls out of the box. When including the Mailgun SDK into your project through a composer dependency, the SDK dev packages are being ignored.

Can you please add here how you require the content of your own `composer.json` file?

If you are trying to install Mailgun (assuming you don't have it yet) can you please include the `composer...` command that you're running too?

Please note that given Mailgun SDK relies on the HttPlug component, you must require more than one package to install and use it. Here's an example: https://github.com/mailgun/mailgun-php#installation

**Comment by jonaslm** [comment]
I was mistaken; we were in fact including `php-http/guzzle6-adapter` ourselves as well, since we were using it to feed the package the HttpClient back when guzzle 6 was used. I realize this is no longer necessary.

Since this is no longer a problem, I'll just close the issue. Apologies for the misunderstanding.

**Comment by DavidGarciaCat** [comment]
No problem. I'm glad you found the issue.
