### ISSUE TITLE
Provide PHP 8.x support

### ISSUE THREAD

**Issue by DavidGarciaCat** [mailgun/mailgun-php#725]
Currently, the SDK provides support for PHP version 7.x but it doesn't for the upcoming 8.x due to a composer restriction:

https://github.com/mailgun/mailgun-php/blob/a084abdb8601c0380b668651c169e0560fb435d0/composer.json#L5

An update of the `composer.json` file to allow PHP 8.x also requires an update of the PHP Unit version, as the current one is set for 7.5, that is also restricted to PHP version 7.x.

https://github.com/mailgun/mailgun-php/blob/a084abdb8601c0380b668651c169e0560fb435d0/composer.json#L13

https://packagist.org/packages/phpunit/phpunit#7.5.20

Upgrading the SDK for this newer PHP version might imply a BC Break for previous PHP versions, so maybe is worth creating a new major release as we can drop support for PHP 7.1 and 7.2.

**Comment by semihkeskindev** [comment]
with all my respect, when php 8.x support coming? i was gonna use in my project but i realised last version supports only 7.1. 😞

**Comment by DavidGarciaCat** [comment]
Hi @semihkeskindev

The current restriction is `"php": "^7.1"` meaning any PHP version greater than or equal to 7.1 but not reaching 8.x will work. If your project uses PHP 7.1, 7.2, 7.3 or 7.4, then it works.

The PR to enable PHP 8.x support is currently a draft, and I will work on it again as soon as I have some time. I have several open fronts now, and I need to spare my time and set priorities according to the most important points.

Thanks for your understanding and your interest.

**Comment by symisc** [comment]
Any updates for the 8.x support? We are migrating our codebase to PHP8. Everything compiles fines except the mailgun SDK which fallback to 1.x when using composer due to `"php": "^7.1"`

**Comment by semihkeskindev** [comment]
> @DavidGarciaCat Any updates for the 8.x support? We are migrating our codebase to PHP8. Everything compiles fines except the mailgun SDK which fallback to 1.x when using composer due to `"php": "^7.1"`

if it takes long time to update for 8.x support, might be ignore php requirement with "**--ignore-platform-reqs**".  i added as requirements like below:

`composer require mailgun/mailgun-php --ignore-platform-reqs`

I definitely cannot recommend this way but i had to use... so i didn't see any error or buggy situation in php 7.4. Better than nothing 😄

**Comment by DavidGarciaCat** [comment]
Still WIP, but I will try to invest some time this month.

**Comment by DavidGarciaCat** [comment]
The PR should be ready for a review.

**Comment by DavidGarciaCat** [comment]
Tagged version `3.3.0` is now available with PHP 8 support
