### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Http\Client\Common\PluginClient' not found in

### ISSUE THREAD

**Issue by ss-756** [mailgun/mailgun-php#729]
I got this error using php/mailgun. Is there someone who has experience in this kind of error?
![image](https://user-images.githubusercontent.com/61330113/100555433-72911e00-3269-11eb-9704-44f730ad73ac.png)

**Comment by uavn** [comment]
@SterlingSmith0 try to run composer install again, looks like installation was incomplete

**Comment by DavidGarciaCat** [comment]
Can you pleas try following the install steps? https://github.com/mailgun/mailgun-php#installation

**Comment by Nyholm** [comment]
One should always use composer.
