### ISSUE TITLE
Update Mailgun to use GuzzleHttp

### ISSUE THREAD

**Issue by virgofx** [mailgun/mailgun-php#73]
Please update the http request methods to use the latest GuzzleHttp package. This is useful because it helps prevent redundancy in up-to-date packages from having to download both GuzzleHttp\ and Guzzle\ packages.

**Comment by andreasbernhard** [comment]
+1

**Comment by auro1** [comment]
Please update to use GuzzleHttp/Guzzle:~6 instead of 5 since I'm already using v6 in my application and therefore I am unable to use your library :disappointed:

**Comment by virgofx** [comment]
Any way we can merge PR #86?

**Comment by auro1** [comment]
It breaks backwards-compability (php 5.4 support), so it would have to be a new major release for mailgun/mailgun-php

You could choose to just use my branch? I'm using it in production. Eventually I'll merge it into mailgun/mailgun-php.

**Comment by virgofx** [comment]
@auro1 Auro -- we ended up using your branch .. works perfectly. 

Moving forward, I'm in favor of creating a new major release that breaks php 5.4 as I know Guzzle6 requires php 5.5 with your PR merged :)

**Comment by Nyholm** [comment]
Mailgun 2.0 is not coupled to Guzzle. One can use any library for sending HTTP messages.
