### ISSUE TITLE
Authorization header gets discarded

### ISSUE THREAD

**Issue by jerome2710** [mailgun/mailgun-php#730]
I am having a hard time getting the mailgun-php SDK to work. I believe I have followed the documentation carefully, but I keep getting the message "_Your credentials are incorrect._". I have also tried the [Postman integration](https://documentation.mailgun.com/en/latest/api-intro.html#postman-integration) to verify that my API key is indeed correct, which sends my mail successfully. 

If I dump the request in the [Guzzle client](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L131), it seems that the authorization header is empty:

```
["headers":protected]=>
    array(4) {
      ["authorization"]=>
      object(Slim\Psr7\Header)#106 (3) {
        ["originalName":"Slim\Psr7\Header":private]=>
        string(13) "Authorization"
        ["normalizedName":"Slim\Psr7\Header":private]=>
        string(13) "authorization"
        ["values":"Slim\Psr7\Header":private]=>
        array(1) {
          [0]=>
          string(0) ""
        }
      }
...
```

I verified that the API key is actually being set from my environment files, as it is present in the `\Http\Client\Common\PluginClient::sendRequest()` function.

Can anyone point me in the right direction?

---

Some additional information:

```
"mailgun/mailgun-php": "^3.2",
"php-http/guzzle7-adapter": "^0.1.1"
```

```php
public function sendEmail(string $recipient, string $subject, string $body)
{
    $client = Mailgun::create($_ENV['MAILGUN_SENDING_API_KEY'], $_ENV['MAILGUN_SENDING_API']);
    
    return $client->messages()->send(
        $_ENV['MAILGUN_SENDING_DOMAIN'],
        [
            'from'    => $_ENV['MAILGUN_FROM_EMAIL'],
            'to'      => $recipient,
            'subject' => $subject,
            'text'    => $body,
        ]
    );
}
```

**Comment by beko1997** [comment]
I just had the same issue. When I checked the headers they were missing, which caught me off guards.

In the end I double checked the domain I used. In my case the domain was not registered on the used api key/EU version. It seems this raises the same error message and the authorization header is set later into the request.

Furthermore did you found this #454 older issue? There might be more information there.

**Comment by DavidGarciaCat** [comment]
Hello @jerome2710 

The https://github.com/mailgun/mailgun-php/issues/454 might be a good starting point, as @beko1997 has mentioned.

Please make sure the API endpoint matches (so don't cross EU and US servers and registered domains) as well as not mixing the registered domain with any other derivated subdomain. Also, make sure the API key/secret are matching with the ones available on your Mailgun account.

Cheers

**Comment by jerome2710** [comment]
Hi @DavidGarciaCat and @beko1997,

Thank you for looking into this. I managed to work around this last week by using SwiftMailer and the SMTP credentials, they seemed to work at the time while the SDK did not. I was however still curious what I was doing wrong with the SDK.

As you pointed out, I did use the EU API endpoint, as the domain is registered on the EU servers. I could list our domains with `->domains()->index()`, just not send any mails. Trying again just a minute ago, it is working now with the exact same code. Could there be a delay within the app vs. the API regarding the domain verification?

**Comment by uavn** [comment]
@jerome2710 This happens when you have IP whitelist, you can't send messages:
```
[10-Dec-2020 20:45:45 UTC] PHP Fatal error:  Uncaught Mailgun\Exception\HttpClientException: Your credentials are incorrect. in /var/www/mailgun-php/src/Exception/HttpClientException.php:68
Stack trace:
#0 /var/www/mailgun-php/src/Api/HttpApi.php(91): Mailgun\Exception\HttpClientException::unauthorized(Object(GuzzleHttp\Psr7\Response))
#1 /var/www/mailgun-php/src/Api/HttpApi.php(73): Mailgun\Api\HttpApi->handleErrors(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/mailgun-php/src/Api/Message.php(63): Mailgun\Api\HttpApi->hydrateResponse(Object(GuzzleHttp\Psr7\Response), 'Mailgun\\Model\\M...')
#3 /var/www/mailgun-php-client/index.php(21): Mailgun\Api\Message->send('example.com', Array)
#4 {main}
  thrown in /var/www/mailgun-php/src/Exception/HttpClientException.php on line 68
```

but you can get everything else.

Check Account Security -> API security -> IP whitelist
if you have IPs in whitelist - you will only be allowed to send messages from that IPs (IP of the server from where script is running, not your local IP from what you call the script).

You can also see a Warning there:
```
Warning: Adding an item to this whitelist will remove access from IPs that are not specified below.
```

**Comment by DavidGarciaCat** [comment]
I'm closing this issue as it seems to be resolved following the two previous comments and the details provided.

**Comment by jerome2710** [comment]
I did not add any IP whitelists to the API security, so this can't be the cause of this issue.

**Comment by DavidGarciaCat** [comment]
Does your `MAILGUN_SENDING_DOMAIN` env var contain your own domain or a demo domain assigned by Mailgun?
