### ISSUE TITLE
Get individual ID when batch sending

### ISSUE THREAD

**Issue by heyabredda** [mailgun/mailgun-php#731]
I was wondering if there's a way of getting individual ID as soon as an email has been sent to a recipient through the batch sending?

What I am currently doing is:

```
$all_users["data"] = [
      "mikedal@gmail.com" => [ "first_name" => "Mike", "last_name" => "Dallas" ],
      "paullo@gmail.com" => [ "first_name" => "Paul", "last_name" => "Long" ]
];

$mgClient = Mailgun::create("API-KEY", "https://api.eu.mailgun.net");

$grouped_users = array_chunk($all_users["data"], 1000, true);

foreach ($grouped_users as $user) {
    $result = $mgClient->messages()->send("my-domain-here.org", [
    'from'    => 'from@test.org',
    'to'      => array_keys($user),
    'subject' => 'Hey! This is a test!',
    'text'    => 'Testing some Mailgun awesomness!',
  ]);
};
```

Once the message has been sent I would like to fetch and store each individual ID (from each email sent to a recipient). Is this possible? Thank you.

**Comment by DavidGarciaCat** [comment]
Hello @heyabredda 

Given you're running a loop and getting access to each item of the array one-by-one for individual sending, I can't say this is a batch sending, but individual sending, so you can get the ID of the message for each `$result` just after sending it:

```php
$messageId = $result->getId();
```

If you want to send batch emails, then you can use the `Batch Message` component:

```php
$batchMessageBuilder = $mailguin->messages()->getBatchMessage();
```

This component extends the Message Builder, so you can prepare the sending according to your needs before sending the message; please check their PHP Classes or let your IDE tell you the available methods for this component:

- https://github.com/mailgun/mailgun-php/blob/master/src/Message/BatchMessage.php
- https://github.com/mailgun/mailgun-php/blob/master/src/Message/MessageBuilder.php

Once sent, the new `$result` will have a method to get all the IDs for all Messages.

Cheers,

**Comment by heyabredda** [comment]
Thank you @DavidGarciaCat
