### ISSUE TITLE
Error deleting email from mailing list

### ISSUE THREAD

**Issue by leopinzon** [mailgun/mailgun-php#750]
I have the same exact issue mentioned on this previous (closed) one: https://github.com/mailgun/mailgun-php/issues/669

Same implementations is working ok for adding/updating members to/from the MailingList, but when it comes to the removal, it throws back the following exception: 

**API call**
```
$mgClient = Mailgun::create("MY_MAILGUN_PRIVATE_KEY", "https://api.mailgun.net");
return $mgClient->mailingList()->member()->delete(
	"MY_MAILING_LIST@example.com",
	"email@to-delete.com"
);

```
**Error:** 
```
"PHP message: Mailgun\Exception\HttpClientException: The endpoint you have tried to access does not exist. Check if the domain matches the domain you have configure on Mailgun. in /.../myproject/vendor/mailgun/mailgun-php/src/Exception/HttpClientException.php:78

Stack trace:

#0 /.../myproject/vendor/mailgun/mailgun-php/src/Api/HttpApi.php(97): Mailgun\Exception\HttpClientException::notFound(Object(Nyholm\Psr7\Response))

#1 /.../myproject/vendor/mailgun/mailgun-php/src/Api/HttpApi.php(73): Mailgun\Api\HttpApi->handleErrors(Object(Nyholm\Psr7\Response))

#2 /.../myproject/vendor/mailgun/mailgun-php/src/Api/MailingList/Member.php(246): Mailgun\Api\HttpApi->hydrateResponse(Object(Nyholm\Psr7\Response), 'Mailgun\\Model\\M...')

#3 /.../myproject/app/Helpers/MailgunClientHelper.php(161): Mailgun\Api\MailingList\Member->delete('test_integracio...', 'natalia.varela0...')
```

**Using:**

PHP 7.3
Laravel 5.5 LTS
mailgun/mailgun-php 3.4.1

**Comment by leopinzon** [comment]
Yes, I still do: 

`Mailgun\Exception\HttpClientException: The endpoint you have tried to access does not exist. Check if the domain matches the domain you have configure on Mailgun. in /[full path]/vendor/mailgun/mailgun-php/src/Exception/HttpClientException.php:78`

**Comment by DavidGarciaCat** [comment]
According to the API documentation, the API endpoint is: `DELETE /lists/<address>/members/<member_address>`

![image](https://user-images.githubusercontent.com/7809429/110348633-c316d500-8029-11eb-88aa-b0330fa65d94.png)

https://documentation.mailgun.com/en/latest/api-mailinglists.html#mailing-lists

![image](https://user-images.githubusercontent.com/7809429/110349398-944d2e80-802a-11eb-9ede-0ecb5a67c986.png)

https://documentation.mailgun.com/en/latest/api-mailinglists.html#examples

----

At the moment, this SDK sends a `DELETE` request to the expected API endpoint (it matches with both the official documentation that we use to keep this SDK up to date and the example you get when scrolling down):

https://github.com/mailgun/mailgun-php/blob/f109b4a2f7914548932a422b9cfc3c3607be1b03/src/Api/MailingList/Member.php#L239-L247

----

Please:
- ensure that all your variables and constants are valid, including the API key, domain, mailing list and address.
- ensure you don't have any extra blank space before or after any of your parameters
- ensure both the list address and the member address are matching, avoiding any case-sensitive issue

If you use the US servers, then don't pass the base string to the named constructor as the SDK sets it automatically for you.

Without further details, there's not much more we can do

**Comment by DavidGarciaCat** [comment]
Actually, if the problem persists after checking all these details, please try to run the request through you terminal via `curl` command

**Comment by leopinzon** [comment]
You're completely right. 

Double checking my code vs. the endpoint it makes the request to, I did realize that the exception is triggered when the email address to be removed is (for whatever reason) not present within the mailing list. Therefore, It automatically turns the endpoint as invalid. 

I assumed that in those cases, a detailed error was coming back within the json reponse, but this is not the case. 

Thanks a lot for your help.

**Comment by DavidGarciaCat** [comment]
I'm glad you found it :-)
