### ISSUE TITLE
Main readme needs links updated

### ISSUE THREAD

**Issue by fmp777** [mailgun/mailgun-php#754]
"This SDK includes a **Message Builder**, **Batch Message** and **Opt-In Handle**r component."

these 3 links are 404

**Comment by DavidGarciaCat** [comment]
Hello,

The `Opt-In Handler` seems a deprecated feature we had in version 2.x:
- https://github.com/mailgun/mailgun-php/blob/2.x/src/Mailgun/Lists/OptInHandler.php

Given its part of the `Lists` package, makes sense to use the Mailing List component instead:
- https://github.com/mailgun/mailgun-php/blob/master/src/Api/MailingList.php

Both the Message Builder and the Batch Message are available on version 3.x of the SDK:
- https://github.com/mailgun/mailgun-php/blob/master/src/Message/MessageBuilder.php
- https://github.com/mailgun/mailgun-php/blob/master/src/Message/BatchMessage.php

Feel free to send a Pull Request fixing these links and we can amend them ;-)

Cheers,

**Comment by Pavlico** [comment]
#770
