### ISSUE TITLE
Mailgun website uses outdated PHP

### ISSUE THREAD

**Issue by Brandin** [mailgun/mailgun-php#756]
This library isn't compatible with the example for PHP on the Mailgun Dashboard. Please forward this to the appropriate team to have it updated.

**Comment by tongcheong** [comment]
i'm just curious. In what way is it not compatible?

**Comment by DavidGarciaCat** [comment]
What he means is the SDK methods are not aligned with the Mailgun Documentation page

**Comment by Pavlico** [comment]
documentation updated so im closing issue
