### ISSUE TITLE
Doesn't work with Guzzle 7

### ISSUE THREAD

**Issue by csimpi** [mailgun/mailgun-php#757]
Hi, I just upgraded to the newest version and getting an error:
`No PSR-17 url factory found. Install a package from this list: https://packagist.org/providers/psr/http-factory-implementation`

I've installed:

```
        "php-http/guzzle7-adapter": "^1.0",
        "php-http/message": "^1.11",
        "guzzlehttp/psr7": "^1.8"
```

I'm still getting the error. I would like to use this package with `"guzzlehttp/guzzle": "^7.0.1",` (Laravel 8).

**Comment by DavidGarciaCat** [comment]
Can you please try installing the dependencies we have in the Readme?

https://github.com/mailgun/mailgun-php#installation

```
composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7
```

If you want to use Guzzle7 then just replace the adapter:

```
composer require mailgun/mailgun-php php-http/guzzle7-adapter nyholm/psr7
```

I guess it's not the case, but please make sure you're using the named constructor, passing the API Key and targeting the right region.

**Comment by csimpi** [comment]
@DavidGarciaCat 

Thank you!
It's partly working now (I use Guzzle). 

I don't understand why the error message suggests that I should install `a package from this list: https://packagist.org/providers/psr/http-factory-implementation`, it should suggest I should install nyholm/psr7`.

It still throwing errors in debug mode though. The email arrives in the bin but throws a response formatting error since the debug message response content-header is not `json`. This should be handled by this package internally.

**Comment by DavidGarciaCat** [comment]
He @csimpi 

If you have a chance, could you paste a stack here so someone can take a look on that error?

Cheers,

**Comment by csimpi** [comment]
@DavidGarciaCat 
Thank you for pinging me. 
I've managed it using `NoopHydrator`.

The problem is here:
https://github.com/mailgun/mailgun-php/blob/f109b4a2f7914548932a422b9cfc3c3607be1b03/src/Hydrator/ModelHydrator.php

Debug mode returns with `text` instead of `application/json` so it throws en exception. 
It should not throw exceptions when debug mode is enabled.

**Comment by zanderwar** [comment]
> Can you please try installing the dependencies we have in the Readme?
> 
> https://github.com/mailgun/mailgun-php#installation
> 
> ```
> composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7
> ```
> 
> If you want to use Guzzle7 then just replace the adapter:
> 
> ```
> composer require mailgun/mailgun-php php-http/guzzle7-adapter nyholm/psr7
> ```
> 
> I guess it's not the case, but please make sure you're using the named constructor, passing the API Key and targeting the right region.

https://github.com/mailgun/mailgun-php/blob/master/composer.json#L21

Why does nyholm/psr7 need to be required at project level if it's already required at package level?

**Comment by DavidGarciaCat** [comment]
Because it is `NOT` required as a package level :smile: 

If you pay attention to the `composer.json` file, you will notice the `nyholm/psr7` package is included as part of this SDK as one of the `dev` packages, which means it's only installed if you clone this repo and install the dependencies to maintain the code.

If you use this SDK alongside other vendors in your project, that doesn't install any `dev` package, which means the `nyholm/psr7` dependency is not installed.

![image](https://user-images.githubusercontent.com/7809429/120596981-5a7aa100-c43c-11eb-92c0-6a6786d102ef.png)

**Comment by zanderwar** [comment]
I must've been having a bad day lol.

**Comment by Pavlico** [comment]
So I guess everything is sorted out and we can close this issue :)
