### ISSUE TITLE
credentials are incorrect

### ISSUE THREAD

**Issue by sagartmg** [mailgun/mailgun-php#759]
Where are the correct credentials located ??

tried all from setting> API sercurity 

Private API key
a349dd7553f81c4d629c3c3abe963eea-ea44b6dc-6c19028a
Public validation key
pubkey-c83e1e9c1e07ec660e9f2bab07fbfbcd
This key is used for our email validation service. Check out the documentation for more information.
HTTP webhook signing key
a349dd7553f81c4d629c3c3abe963eea-ea44b6dc-6c19028a

 $mgClient =  Mailgun::create('a349dd7553f81c4d629c3c3abe963eea-ea44b6dc-6c19028a');
        $domain = "sandboxb99e1ca4def54b5b9f055716746afe17.mailgun.org";

        # Make the call to the client.
        $result = $mgClient->messages()->send($domain, array(
            'from'	=> 'postmaster@sandboxb99e1ca4def54b5b9f055716746afe17.mailgun.org',
            'to'	=> 'custom70@gmail.com',
            'subject' => 'Hello',
            'text'	=> 'Testing some Mailgun awesomness!'
        ));

got Mailgun\Exception\HttpClientException: Your credentials are incorrect.

**Comment by DavidGarciaCat** [comment]
Open your user menu (top-right corner) and choose API Keys: https://app.mailgun.com/app/account/security/api_keys

Please note at the time you instantiate your Mailgun client, you should use the named constructor:

```php
$mg = Mailgun::create('key-example'); // For US servers
$mg = Mailgun::create('key-example', 'https://api.eu.mailgun.net'); // For EU servers
```

**Extremely important** don't forget to set the EU server if you registered your domain in the EU, or it won't work and you will get the invalid credentials error.

**Comment by DavidGarciaCat** [comment]
Note: when browsing that page, please make sure to reset your API key, as it seems you posted them here.
