### ISSUE TITLE
Proper way to get Exception Data?

### ISSUE THREAD

**Issue by brandinarsenault** [mailgun/mailgun-php#760]
Hello,

What is the best way with this class to get Exception Data? A bunch of my emails are sending `UnknownErrorException` and when I try to get the error using `$e->getMessage()` is empty so I'm unable to determine the issue that raised?

Brandin.

**Comment by DavidGarciaCat** [comment]
Hi @brandinarsenault 

The `UnknownErrorException` extends from the basic `Exception`, so it should be handled in the same way as any other exception.

https://github.com/mailgun/mailgun-php/blob/master/src/Exception/UnknownErrorException.php

This SDK may throw exceptions based on different types of errors (client, server, and more) and their status code (which is used to determine what happened), meaning the `Unknown` one is when we got an unexpected error:

https://github.com/mailgun/mailgun-php/blob/f109b4a2f7914548932a422b9cfc3c3607be1b03/src/Api/HttpApi.php#L84-L107

The main difference here is the `UnknownErrorException` doesn't set the parent data, hence you don't get an error message as you said:

https://github.com/mailgun/mailgun-php/blob/f109b4a2f7914548932a422b9cfc3c3607be1b03/src/Api/HttpApi.php#L105

So the two options are:
1. Someone sends a new PR with the required update and tests to track and expose the previous [exception] data; and/or
2. You can `try-catch` and `var_dump` your process to find out where it fails and what data you pass right before getting the error

Hope it helps,

**Comment by DavidGarciaCat** [comment]
By the way, we are now adding a new status code + error: https://github.com/mailgun/mailgun-php/pull/758
