### ISSUE TITLE
Could not find a matching version of package mailgun/mailgun-php

### ISSUE THREAD

**Issue by sohailanwarpk** [mailgun/mailgun-php#762]
Hi , i am trying to run following command (reference https://github.com/mailgun/mailgun-php)
composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7

But getting following error
[InvalidArgumentException]
Could not find a matching version of package mailgun/mailgun-php. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

Tested on PHP version 7.3 and 7.4

**Comment by DavidGarciaCat** [comment]
Can you please copy/paste the full output of the following commands?

```
php --version
```

```
composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7
```

Cheers,

**Comment by sohailanwarpk** [comment]
php --version
PHP 7.3.28 (cli) (built: May 6 2021 04:07:27) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.28, Copyright (c) 1998-2018 Zend Technologies

composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7


[InvalidArgumentException]
Could not find a matching version of package mailgun/mailgun-php. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...

**Comment by DavidGarciaCat** [comment]
Well, the 3 packages you're requesting require one of the following minimum PHP version:
- 7.1 ( the two dependencies )
  - https://packagist.org/packages/kriswallsmith/buzz
  - https://packagist.org/packages/nyholm/psr7
- 7.3 ( this SDK )
  - https://packagist.org/packages/mailgun/mailgun-php

Given your PHP version matches that criteria, it should work.

Someone will need to investigate a little bit about this issue.

**Comment by DavidGarciaCat** [comment]
Are you running your app through a WAMP / LAMP / MAMP pre-set package?

**Comment by sohailanwarpk** [comment]
I have tested on LAMP and also on XAMPP on local machine

**Comment by DavidGarciaCat** [comment]
interesting... because it means maybe the PHP version in your packaged software doesn't match with the version used by the host or the version that `composer` uses.

Anyway, some further testing might be required, but knowing you're using a packaged *AMP environment, my first suggestion would be to confirm which PHP binary is Composer using, as it seems to be a crossed-version issue based on what you just said.

**Comment by sohailanwarpk** [comment]
I have only two versions of PHP installed 7.3 and 7.4 , and have checked composer is using PHP 7.3 which is enabled version and running.

**Comment by Pavlico** [comment]
hi @sohailanwarpk do you have any issues installing other packages? It only just mailgun?

**Comment by sohailanwarpk** [comment]
Issue solved, It was with mailgun only, i have deleted composer.lock file and installed again and its worked successfully.
