### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by rugabarbo** [mailgun/mailgun-php#763]
README section: https://github.com/mailgun/mailgun-php/blob/9b270d07b8bc3e4b77df63397ac8a24713eeeafe/src/Message/README.md#more-documentation

Broken link: https://documentation.mailgun.com/api-sending.html

**Comment by DavidGarciaCat** [comment]
Feel free to send a PR with the updated link ;-)

Cheers

**Comment by Pavlico** [comment]
Fixed
