### ISSUE TITLE
Github Student Developer Pack

### ISSUE THREAD

**Issue by Inderveer0909** [mailgun/mailgun-php#764]
There is No Option To set Id Pass after autho plzz tell me solution

**Comment by DavidGarciaCat** [comment]
Hello, @Inderveer0909

Excuse me, but I am not sure to understand what you mean:
- What is this `Github Student Developer Pack` that you're referring and how is it even related to this repository?
- What is this option to ser any Id Pass that you say is missing?

Maybe you have posted an issue to the wrong repository?

Cheers,
