### ISSUE TITLE
how to get next page event

### ISSUE THREAD

**Issue by darshitkkhatri** [mailgun/mailgun-php#767]
How can i convert my response from object base to array.
Problem is when i use this code

$configurator = new HttpClientConfigurator();
$configurator->setApiKey('key-example');
$mg = new Mailgun($configurator, new ArrayHydrator());

It returns response in array but then I cannot use this response to get the next page with as it expecting page object
$nextPage = $mgClient->events()->nextPage($result);

When i use this 
$mgClient    = Mailgun::create('PRIVATE_API_KEY', 'https://API_HOSTNAME');
$domain      = 'YOUR_DOMAIN_NAME';
$queryString = array(
    'begin'        => 'Wed, 1 Jan 2020 09:00:00 -0000',
    'ascending'    => 'yes',
    'limit'        =>  25,
    'pretty'       => 'yes'
);
$result = $mgClient->events()->get($domain, $queryString);
I am able to get the response for next page but the result is again reponseobject and not array.

Can somebody help me here from converting object to array.

**Comment by darshitkkhatri** [comment]
Please ignore this, i resolved it.

**Comment by DavidGarciaCat** [comment]
👍 closing this issue
