### ISSUE TITLE
BatchMessage does not account for overall message size?

### ISSUE THREAD

**Issue by vinnyusestrict** [mailgun/mailgun-php#768]
I am custom building batch messages for my clients (not using the SDK) and one client ran into a scenario where the message body/replacements were too large for the API call, even though the number of recipients was capped at 1000.

From Mailgun support:

> We have a recipient variable limit of 16KB and a messaging limit of 25 MBs for the entire message, body, and content of the message combined.

I am considering switching over to the SDK but a quick code check shows that it also only looks for the 1000 recipient limit. No checks seem to be done regarding the overall message size.

Is this being handled elsewhere in the code that I didn't see? Can I safely re-implement my code using the BatchMessage SDK or will we run into the same issue?

Cheers,
Vinny

**Comment by DavidGarciaCat** [comment]
Hi @vinnyusestrict 

Unless the official API docs state somewhere the size limit, probably no one implemented it. If you switch to the SDK and pass the same content, you might get the same error.

My advice here is, either if you decide to switch to the SDK or keep using your native implementation, to reduce the number of data you're sending so you won't reach those limits.

Cheers,
