### ISSUE TITLE
Using SMTP creds in existing system not list email sent

### ISSUE THREAD

**Issue by Kulkarniharish** [mailgun/mailgun-php#77]
Hi,
I am using Mailgun's SMTP creds to send email from my existing mail system.But emails are going but they are not listed in Logs tab in my account for a particular domain.

Please let me know.

Thanks

**Comment by DavidGarciaCat** [comment]
Hi @Kulkarniharish - I think all emails are now listed. Please have a look and let know to Mailgun's team if they can close this ticket (or do it yourself). Regards,

**Comment by Kulkarniharish** [comment]
Hi there,


Thanks for replying back on this.
I just want to understand how long the sent emails will be stored in maligun ? and thru API how long we can keep accessing ?what if we need to access stored emails longer than 3 days?
Because you have mentioned that 
"Stored messages are retained in the system for 3 days and automatically purged after this retention period, therefore there is no need to delete messages explicitly.”.

Thanks
Harish Kulkarni

**Comment by DavidGarciaCat** [comment]
Hello @Kulkarniharish 

What I understand is you want to check your messages history through Mailgun API. Is this right? If this is the case, a Mailgun team member should answer to your question, I'm afraid I'm just a developer and I cannot answer 😅 However I remember I read the same copy you added when I was looking for a service like Mailgun, so if a team member can clarify this will be great.

Given my experience, is a better idea store a copy of the data that you need in your own database, so you know the data won't be deleted (except if you do it) and you can create customised reports when needed. Given Mailgun gives you the ability to add new Webhooks for each domain you manage, you can enable a Callback endpoint on your system and process those callbacks.

Anyway, this is up to you.

Cheers,

**Comment by Nyholm** [comment]
I agree with @DavidGarciaCat. Keep a local copy of the emails. 

> I just want to understand how long the sent emails will be stored in maligun ? and thru API how long we can keep accessing ?what if we need to access stored emails longer than 3 days?

I guess you will get a 404. Not sure to be honest. I use webhooks and keep a local log of all emails. 

This issue is not related to the API-client. You should contact the Mailgun support.
