### ISSUE TITLE
Tracking events - queryString with message-id returns a list of results

### ISSUE THREAD

**Issue by Sharvadze** [mailgun/mailgun-php#772]
Hi, I'm trying to check the status of a specific email using a message-id field, but it doesn't seem to work the way I want it to work. It returns an array of results and I'd like to track a specific record. Here is a snippet I'm using, any help is greatly appreciated. 

```
public function getStatus($email)
    {
        $mgClient = Mailgun::create($this->privateKey, $this->hostname);

        $queryString = array(
            'message-id' => '<20210807145120.1.A4197FA3CC61CB49@domain.com>',
        );

        return $mgClient->events()->get($this->domain, $queryString);
    }
```

**Comment by DavidGarciaCat** [comment]
Hi, @Sharvadze 

The getter implemented by this SDK is a wrapper for the official API docs:

https://documentation.mailgun.com/en/latest/api-events.html#events

Based on the current code of the `get` method, as well as the API docs, we get all the events matching the data passed as arguments:

https://github.com/mailgun/mailgun-php/blob/0a0f68c23c484e88aa38b98e2d4de83dfea94c01/src/Api/Event.php#L26-L40

If you are using a specific `message-id`, then you will get one result. Still, the API will return a list, even if it just contains one item. The only point here is that you are filtering by a specific field that makes the result unique.

I recommend you to get the first position of the array, that's the easiest way to solve "your requirement".

```php
$queryString = array('message-id' => '<20210807145120.1.A4197FA3CC61CB49@domain.com>');

$mgClient = Mailgun::create($this->privateKey, $this->hostname);
$events = $mgClient->events()->get($this->domain, $queryString);

return $event[0];
```
