### ISSUE TITLE
Update "array" param doc block

### ISSUE THREAD

**Issue by Nyholm** [mailgun/mailgun-php#779]
Currently we express our doc blocks like this: 

```php
    /**
     * @param array $variables {
     *
     *     @var string $id
     *     @var string $full_name
     *     @var string $first
     *     @var string $last
     * }
     *
     * @throws MissingRequiredParameter
     * @throws TooManyRecipients
     */
```

At the time of writing that code, it was the most prominent standard. However, the "correct" way of doing it nowadays are: 

```php
    /**
     * @param array {
     *   id?: string,
     *   full_name?: string,
     *   first?: string,
     *   last?: string,
     * } $variables
     *
     * @throws MissingRequiredParameter
     * @throws TooManyRecipients
     */
```

This will improve IDE support. 

(It will also help us remove [the psalm complaints](https://github.com/mailgun/mailgun-php/pull/776/files#diff-c14e887ba2298fbb63a975cf0c54b0a157aec2ae313973f0bf532233c5527334R82).)

**Comment by oleksandr-mykhailenko** [comment]
Hello @Nyholm 
Did you mean this ? - https://github.com/mailgun/mailgun-php/pull/846/files
