### ISSUE TITLE
Access properties after events->get()

### ISSUE THREAD

**Issue by DigitalSolo** [mailgun/mailgun-php#782]
All of the properties of the $result object are now private. I used to be able to query a sent email and get the status of the event `$result->items[0]->event`. I'm not sure how I'm supposed to get an email status now?

Here is the example from the mailgun site: [https://documentation.mailgun.com/en/latest/api-events.html#examples](url)

`# Include the Autoloader (see "Libraries" for install instructions)
require 'vendor/autoload.php';
use Mailgun\Mailgun;

# Instantiate the client.
$mgClient    = Mailgun::create('PRIVATE_API_KEY', 'https://API_HOSTNAME');
$domain      = 'YOUR_DOMAIN_NAME';
$queryString = array(
    'begin'        => 'Wed, 1 Jan 2020 09:00:00 -0000',
    'ascending'    => 'yes',
    'limit'        =>  25,
    'pretty'       => 'yes',
    'recipient'    => 'bob@example.com'
);

# Issue the call to the client.
$result = $mgClient->events()->get($domain, $queryString);`

**Comment by Pavlico** [comment]
Hello @DigitalSolo , since they are private you can access them with methods that are prepared for them for example:
getEvent() or getDeliveryStatus()
$mgClient->events()->get($domain, $queryString)->getItems()[0]->getEvent();
$mgClient->events()->get($domain, $queryString)->getItems()[0]->getDeliveryStatus();

**Comment by DigitalSolo** [comment]
I appreciate the update. I can't seem to find this documented anywhere. It might be my ignorance.

**Comment by DavidGarciaCat** [comment]
Hey @DigitalSolo 

Some documentation posted on Mailgun's website might not be fully updated yet, but we will work on it.

In the meantime, if you can't see what you need on the Documentation page, please let me suggest using the IDE helpers (as Pavlico just pointed out, there are plenty of getters to get access to any data coming from the API).

Cheers,

PS: closing this issue, as it seem to be resolved.
