### ISSUE TITLE
Webhook is still using ClientInterface type declaration

### ISSUE THREAD

**Issue by ixarlie** [mailgun/mailgun-php#783]
The Webhook class which is extending from HttpApi is still using the Psr\Http\Client\ClientInterface type declaration.

This is raising an exception, so as it was done for its parent class HttpApi, the type declaration should be less strict.
```
"Argument 1 passed to Mailgun\Api\Webhook::__construct() must implement interface
Psr\Http\Client\ClientInterface, instance of Http\Client\Common\PluginClient given,
called in .../vendor/mailgun/mailgun-php/src/Mailgun.php on line 139"
```

Relates https://github.com/mailgun/mailgun-php/issues/642

Mailgun\Api\Suppression is using the same type declaration Psr\Http\Client\ClientInterface, but I am not sure if this class should be updated as well.

Thanks

**Comment by oleksandr-mykhailenko** [comment]
Fixes were made
