### ISSUE TITLE
Pool ID parameter is missing from Domain::create

### ISSUE THREAD

**Issue by RoyHP** [mailgun/mailgun-php#788]
The `pool_id` parameter is missing from the payload defined in Domain::create(). Your [web documentation](https://documentation.mailgun.com/en/latest/api-domains.html#domains) states that the `ips` parameter can be specified or the `pool_id` parameter.

See attached screenshots from the docs and code:
<img width="1302" alt="Screen Shot 2021-09-10 at 3 36 34 PM" src="https://user-images.githubusercontent.com/1066439/132908197-81604f1f-c02a-488a-ab04-80a5b84ace63.png">
<img width="695" alt="Screen Shot 2021-09-10 at 3 37 14 PM" src="https://user-images.githubusercontent.com/1066439/132908207-41bcacaa-84e9-41c7-8be7-9f12bed5282e.png">

I'm happy to provide a PR adding the parameter, but are the two ip-related parameters supposed to be mutually exclusive? 
Thanks!

**Comment by RoyHP** [comment]
Attempted fix in https://github.com/mailgun/mailgun-php/pull/789

**Comment by Pavlico** [comment]
Hi can you add tests? :)

**Comment by Pavlico** [comment]
Added tests, done
