### ISSUE TITLE
How to send multiple mails to multiple email Ids?

### ISSUE THREAD

**Issue by deepak-atariya** [mailgun/mailgun-php#800]
I have 100 of contacts and I want to send bulk mails with different body for each email id. 

I have been using sendgrid, they are providing this feature to set multiple bodies to multiple recipients.

Is it possible with mailgun API ?

**Comment by deepak-atariya** [comment]
Thank you!

If I want to set few of custom arguments that should be returned by webbook provided by you. 

I need assistance. please let me know

**Comment by Pavlico** [comment]
Mhm :) so i guess you got it?

**Comment by deepak-atariya** [comment]
Yes, Thank you
