### ISSUE TITLE
$mgClient->events()->get() returns object with private variables

### ISSUE THREAD

**Issue by markhaj** [mailgun/mailgun-php#808]
I am using
$result = $mgClient->events()->get($domain, $queryString);
The examples show this returning a JSON output but it is a php object.
I have tried using |json_encode()| but because all the variables in the object are private it returns an empty string.

**Comment by Pavlico** [comment]
Hi @markhaj  Well typically there are some methods that can help you grab info from this object.
you can use get_class_methods($result) to get available methods an work with that

**Comment by markhaj** [comment]
Hi @Pavlico,
Thanks for your time but that returns an empty string too. I think all the methods are private too. Could this be a bug?

**Comment by Pavlico** [comment]
Can you put whole php code sample, that would help me a lot :) i will try to recreate your scenerio mb

**Comment by markhaj** [comment]
<?php

# Include the Autoloader (see "Libraries" for install instructions)
require_once ('vendor/autoload.php');
use Mailgun\Mailgun;
# Instantiate the client.
$mgClient    = Mailgun::create('PRIVATE_API_KEY','https://api.eu.mailgun.net');
$domain = "DOMAIN";

$queryString = array(
    'begin'        => 'Mon, 25 Oct 2021 03:00:00 -0000',
    'ascending'    => 'yes',
    'limit'        =>  1,
    'pretty'       => 'yes'
#    'recipient'    => 'bob@example.com'
);

# Issue the call to the client.
$result = $mgClient->events()->get($domain, $queryString);

print(json_encode($result)); #empty
print_r ($result); # all vars are private
print_r (get_class_methods($result)); # gives
#Array
#(
#    [0] => create
#    [1] => getItems
#    [2] => getNextUrl
#    [3] => getPreviousUrl
#    [4] => getFirstUrl
#    [5] => getLastUrl
#) - not an empty string as I said before. The returned object of getItems() also has all private vars and no methods.
?>

**Comment by markhaj** [comment]
`<?php

Include the Autoloader (see "Libraries" for install instructions)
require_once ('/var/www/dashdb/mailgun/vendor/autoload.php');
use Mailgun\Mailgun;

Instantiate the client.
$mgClient = Mailgun::create('PRIVATE_API_KEY','https://api.eu.mailgun.net');
$domain = "mg.devonsmallholders.uk";

$queryString = array(
'begin' => 'Mon, 25 Oct 2021 03:00:00 -0000',
'ascending' => 'yes',
'limit' => 1,
'pretty' => 'yes'

'recipient' => 'bob@example.com'
);

Issue the call to the client.
$result = $mgClient->events()->get($domain, $queryString);

print(json_encode($result)); #empty
print_r ($result); # all vars are private
print_r (get_class_methods($result)); # gives
#Array
#(

[0] => create
[1] => getItems
[2] => getNextUrl
[3] => getPreviousUrl
[4] => getFirstUrl
[5] => getLastUrl
#) - not an empty string as I said before. The returned object of getItems() also has all private vars and no methods.
?>`

**Comment by Pavlico** [comment]
Well you can use get_class_methods for either result or getItems() result, keeping in mind that getItems returns array of objects, you can foreach and then for example:
```
foreach ($result->getItems() as $item) {
    var_dump(get_class_methods($item));
    var_dump($item->getRecipient());
}

**Comment by markhaj** [comment]
Thanks for your help @Pavlico, all sorted now.
