### ISSUE TITLE
The parameters passed to the API were invalid. Check your inputs! Routes quota (0) is exceeded

### ISSUE THREAD

**Issue by andy236726493** [mailgun/mailgun-php#809]
when I run The following code

        $mailgun     = Mailgun::create('myapikey','https://api.mailgun.net');
        $expression  = "match_recipient('.*@mydomain.com')";
        $actions     = ["forward('user***@gmail.com')"];
        $description = 'Test route';
        $mailgun->routes()->create($expression, $actions, $description);

An error occurred

The parameters passed to the API were invalid. Check your inputs! Routes quota (0) is exceeded

**Comment by Pavlico** [comment]
Hey, @andy236726493 are you using paid plan https://www.mailgun.com/pricing/ ? Routes are not available in free (flex) plan
