### ISSUE TITLE
CC/BCC is ignored when using MIME message

### ISSUE THREAD

**Issue by gondo** [mailgun/mailgun-php#81]
I'am creating email message with SwiftMailer, than casting it `toString()` and passing it as 3rd parameter to `sendMessage()` function, as shown in documentation:  https://documentation.mailgun.com/user_manual.html#sending-via-api
section: "Sending a MIME message which you pre-build yourself using a MIME library of your choice"

```
$result = $mgClient->sendMessage(
    $domain, array(
        'to' => 'to@example.com'
    ),
    $message->toString()
);
```
however `cc` and `bcc` message headers are ignored and email is sent only to `to` recipient.

example of my MIME message:
```
Message-ID: <xxx@example.com>
Date: Tue, 28 Apr 2015 14:05:30 +0200
Subject: test
From: from@example.com
To: to@example.com
Cc: cc@example.com
Bcc: bcc@example.com
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable
X-Mailgun-Drop-Message: yes

testing cc/bcc
```

**Comment by Nyholm** [comment]
I can confirm the bug. But this is not a bug in the API client. The API client is working and sending the proper HTTP request. There is a bug on the API server. 

@travelton can you confirm the bug on the API server?


Btw, this does not work (form the docs): 
```php
$mgClient->sendMessage(
    $domain, array(
        'to' => 'to@example.com'
        'cc' => 'cc@example.com'
        'bcc' => 'bcc@example.com'
    ),
    $message->toString()
);
```

**Comment by jessespears** [comment]
Though it's a bit unintuitive, the behavior is consistent with our [documentation's explanation](https://documentation.mailgun.com/api-sending.html#sending): all recipients must be included in the 'to' parameter.

Your code will look like this:
```php
$mgClient->sendMessage(
    $domain,
    array(
             'to' => ['to@example.com', 
                       'cc@example.com', 
                       'bcc@example.com']
     ),
    $message->toString()
);
```

I admit that the behavior is not as expected.  Note that all recipients will see any `bcc` recipients that are in the MIME.  Recipients won't see who was specified in your `'to' => [...]` array, so all that's needed to keep your `bcc`s secret is to just not specify them in the MIME.

**Comment by gondo** [comment]
@jessespears but how do you specify what recipient is CC and what is BCC if you can use only `to` param as in your example, and you cant specify CC/BCC in MIME?

**Comment by jessespears** [comment]
Here's what you'll want to do:

To: specify in the `'to'` param and also in the To: header of the MIME
Cc: specify in the `'to'` param and also in the Cc: header of the MIME
Bcc: specify only in the `'to'` param.

If you submit using a `text` or `html` field instead of MIME, each recipient will see themselves as the only recipient mentioned in their To: field in their client.

**Comment by Nyholm** [comment]
Thank you for the clarification.

> Though it's a bit unintuitive, the behavior is consistent with our documentation's explanation: all recipients must be included in the 'to' parameter.

Is this true only for MIME messages? 

> If you submit using a text or html field instead of MIME, each recipient will see themselves as the only recipient mentioned in their To: field in their client.

I'm not too sure this is correct, or I might misunderstand you. 
```php 
$result = $mgClient->sendMessage($domain, array(
            'from'    => 'Excited User <from@example.com>',
            'to'      => ['foo@example.com', 'tobias@happyr.com'],
            'cc'      => 'baz@example.com',
            'bcc'     => 'tobias.nyholm@gmail.com',
            'subject' => 'Hello',
            'text'    => 'Testing some Mailgun awesomness!',
            'html'    => '<html>HTML version of the body</html>'
        ));
```

This will send an email to tobias@happyr.com mailbox and one to tobias.nyholm@gmail.com mailbox. In both mailboxes I can see the following recipients. 
![screen shot 2015-05-06 at 21 49 17](https://cloud.githubusercontent.com/assets/1275206/7502111/eb2dd660-f439-11e4-971f-63e62d6ca8ea.png)

**Comment by jessespears** [comment]
@Nyholm you are absolutely right.  I was mistaken.  The `to`, `cc:`, and `bcc` fields are supported for the non-MIME messages.  I have edited my previous comment.  Thanks for catching that!

**Comment by DavidGarciaCat** [comment]
Of course not, that's why it's called `blind`

https://duckduckgo.com/?q=meaning+of+bcc+in+email

**Comment by chebee7i** [comment]
Hey all, it would be really nice if this could make it way (back) into the official documentation. The link provided in the response (https://github.com/mailgun/mailgun-php/issues/81#issuecomment-99568829), is no longer valid, and the official documentation (https://documentation.mailgun.com/docs/mailgun/api-reference/send/mailgun/messages/post-v3--domain-name--messages-mime) doesn't mention this at all anymore.
