### ISSUE TITLE
Support for 2048 DKIM key size while domain creation

### ISSUE THREAD

**Issue by faizanakram99** [mailgun/mailgun-php#812]
Mailgun API allows one to specify `dkim_key_size` when creating domains.

![image](https://user-images.githubusercontent.com/10880992/145354743-47d819bd-c5a8-4c2d-84e8-5f7914cd4c63.png)

**Comment by DavidGarciaCat** [comment]
Thanks for reporting this new field via API calls

Feel free to contribute to this repo, if you want and need this update ASAP.

As far as I can remember, the two files that should be updated are:

Source code:
https://github.com/mailgun/mailgun-php/blob/master/src/Api/Domain.php

PHPUnit test:
https://github.com/mailgun/mailgun-php/blob/master/tests/Api/DomainTest.php

If you can't contribute to this repo and provide the update, another community member will send the update as soon as possible.

Thanks!

**Comment by Pavlico** [comment]
#813

**Comment by Pavlico** [comment]
merged fixes
