### ISSUE TITLE
Type Error Mailgun\Api\Suppression::__construct()

### ISSUE THREAD

**Issue by bondydaa** [mailgun/mailgun-php#814]
Hi,
I'm trying to access the Suppression API and get this error when trying to test out the bounces end points.

I've edited the original calls to remove our domain but here are the errors:
```
>>> $mailgun->suppressions()->bounces()->index('ourdomain@example.com');
TypeError: Argument 1 passed to Mailgun\Api\Suppression::__construct() must implement interface Psr\Http\Client\ClientInterface, instance of Http\Client\Common\PluginClient given, called in /vagrant/Web-Expensify/vendor/mailgun/mailgun-php/src/Mailgun.php on line 124
```
```
>>> $mailgun->suppressions()->bounces()->delete('ourdomain@example.com', 'test@example.com');
TypeError: Argument 1 passed to Mailgun\Api\Suppression::__construct() must implement interface Psr\Http\Client\ClientInterface, instance of Http\Client\Common\PluginClient given, called in /vagrant/Web-Expensify/vendor/mailgun/mailgun-php/src/Mailgun.php on line 124
```

I've been able to fix this locally by editing https://github.com/mailgun/mailgun-php/blob/4db9d9bb6390df783bcfd51a76836b763f4f0b05/src/Api/Suppression.php#L44 and removing the type hint `ClientInterface`.

After that I can call those without the TypeError and get successful responses.

I don't think that is the "proper" fix though, it could be that the call to `createConfiguredClient` is returning a `PluginClient` https://github.com/mailgun/mailgun-php/blob/4db9d9bb6390df783bcfd51a76836b763f4f0b05/src/HttpClient/HttpClientConfigurator.php#L82

Or possibly this could be something within our composer dependency chain and the PSR implementation we're using? 

We're currently using v3.2.0 which I know if a few versions behind the latest release but from what I can tell this suppressions / bounce code hasn't really changed, I've run into some issues trying to get it updated which is why I went the "hack" route of just removing the type hint for now so that I could at least do some testing to confirm changes I'll need to implement in our system.

**Comment by Pavlico** [comment]
hello @bondydaa i could not recreate issue, this code havent produced any error, everything worked as expected from documentation

```$mgClient->suppressions()->bounces()->create($domain, $recipient);
$result = $mgClient->suppressions()->bounces()->index($domain);
var_dump($result);

**Comment by bondydaa** [comment]
Hi sorry was offline all last week. 

It must be caused by another dependency then, maybe guzzle or whatever implements the `Psr18ClientDiscovery` class that we have installed https://github.com/mailgun/mailgun-php/blob/4db9d9bb6390df783bcfd51a76836b763f4f0b05/src/HttpClient/HttpClientConfigurator.php#L130

I'll try and figure out what packages and versions I have locally and see if updating those will fix.

**Comment by bondydaa** [comment]
Yep looks like we solved this by updating the `php-http/discovery` package we had installed as a dependency from the mailgun sdk. sorry about that!
