### ISSUE TITLE
Unable to attach file from php

### ISSUE THREAD

**Issue by ahmedanees** [mailgun/mailgun-php#82]
## Test code is here

$file_name =  "/public_html/solfreaks/test/uploads/4-29-2015 2-21-46 PM.png";
            $messageBldr->addAttachment($file_name);
            //$messageBldr->setDeliveryTime("tomorrow 8:00AM", "PST");
            $messageBldr->setClickTracking(true);
print_r($messageBldr);

```
        # Finally, send the message.
        $return = $mg->post("{$domain}/messages", $messageBldr->getMessage(), $messageBldr->getFiles());    
```

---
## POst array

Mailgun\Messages\MessageBuilder Object
(
    [message:protected] => Array
        (
            [from] => Array
                (
                    [0] => 'hareem haque' 
                )

```
        [to] => Array
            (
                [0] => 'Ahmed ANees' 
            )

        [subject] => A message from the PHP SDK using Message Builder!
        [text] => This is the text body of the message!
        [o:tracking-clicks] => yes
    )

[variables:protected] => Array
    (
    )

[files:protected] => Array
    (
        [attachment] => Array
            (
                [0] => Array
                    (
                        [filePath] => /public_html/solfreaks/test/uploads/4-29-2015 2-21-46 PM.png
                        [remoteName] => 
                    )

            )

    )

[counters:protected] => Array
    (
        [recipients] => Array
            (
                [to] => 1
                [cc] => 0
                [bcc] => 0
            )

        [attributes] => Array
            (
                [attachment] => 0
                [campaign_id] => 0
                [custom_option] => 0
                [tag] => 0
            )

    )
```

)

**Comment by auro1** [comment]
Could you please send a request to a http://bin.mailgun.net/ ?? It's easier that way. :+1:

**Comment by Nyholm** [comment]
Is this still an issue in the latest version of the client?

**Comment by joshpennington** [comment]
I am having the same issue. Here is my code (using Laravel):

`$email_message = 'This is a test email';
        $mailgun = new Mailgun(config('mail.mailgun_key'), new Client());

        $message = $mailgun->MessageBuilder();
        $message->setFromAddress(config('mail.from_address'));

        foreach(config('mail.donation_request_recipients') as $recipient) {
            $message->addToRecipient($recipient);
        }

        $message->setSubject('New Donation Request');
        $message->setHtmlBody(nl2br($email_message));
        $message->setTextBody($email_message);
        $message->addTag('wps4-donation-request');

        $message->addAttachment($request->file('irs_letter')->getRealPath());`

Output of $message is: 

`
Mailgun\Messages\MessageBuilder Object
(
    [message:protected] => Array
        (
            [from] => Array
                (
                    [0] => xxxxxx@xxxxx.com
                )

            [to] => Array
                (
                    [0] => xxxx@xxxxxx.com
                )

            [subject] => New Donation Request
            [html] => This is a test email
            [text] => This is a test email
            [o:tag] => Array
                (
                    [0] => wps4-donation-request
                )

        )

    [variables:protected] => Array
        (
        )

    [files:protected] => Array
        (
            [attachment] => Array
                (
                    [0] => Array
                        (
                            [filePath] => /tmp/phpvRYhBT
                            [remoteName] => 
                        )

                )

        )

    [counters:protected] => Array
        (
            [recipients] => Array
                (
                    [to] => 1
                    [cc] => 0
                    [bcc] => 0
                )

            [attributes] => Array
                (
                    [attachment] => 0
                    [campaign_id] => 0
                    [custom_option] => 0
                    [tag] => 1
                )

        )

)
`

If you can better explain this bin.mailgun.net thing, I can send info from there but right now there is not enough direction.

**Comment by Nyholm** [comment]
Thank you @joshpennington. Can you try with the latest version of the api and with the new signatures?

You have to use the new factory method and then follow these examples: https://github.com/mailgun/mailgun-php/blob/master/doc/attachments.md#attachments

```php

$mg = Mailgun::create('key-example');

```

**Comment by joshpennington** [comment]
Using that new factory method gives me the following error:

Call to undefined method Mailgun\Mailgun::create()

Is there a new version I should be using? In my composer file I currently have `"mailgun/mailgun-php": "^2.1",` for MailGun

**Comment by joshpennington** [comment]
I just updated to 2.3 and now I am getting the following error message:

`Call to undefined method Mailgun\Mailgun::message()`

Looking at the class I see there is no method called message. I see a sendMessage method that looks like it would work but it is deprecated.

My new code looks like this:

`
$mg = Mailgun::create(config('mail.mailgun_key'));

        $mg->message()->send('example.com', [
            'from'    => config('mail.from_address'),
            'to'      => implode(',', config('mail.donation_request_recipients')),
            'subject' => 'xxxx',
            'text'    => $email_message,
            'attachment' => [
                ['filePath' => $request->file('xxxx')->getRealPath(), 'filename'=>'test.pdf']
            ]
        ]);
`

**Comment by joshpennington** [comment]
I found my issue. The method name is messages() and not message().

Things are working as expected now. Thank you

**Comment by teamcoltra** [comment]
This should be closed
