### ISSUE TITLE
Support for stream in fetching rawMime (Message::show(url, true))

### ISSUE THREAD

**Issue by faizanakram99** [mailgun/mailgun-php#821]
This thing here hydrates responses into `Mailgun\Model\ApiResponse\ShowResponse` and in case of rawMime, the string is way too big and causes out of memory issues when working on it. Maybe it should be split into two methods, a dedicated method for returning rawMime as a readable stream ?

https://github.com/mailgun/mailgun-php/blob/2395e5d2322d322cce4155f810c1e1f7e035d5b1/src/Api/Message.php#L120

**Comment by oleksandr-mykhailenko** [comment]
Hello @faizanakram99 
This was fixed in latest version. 
Thanks for using our library
