### ISSUE TITLE
Adding search functionality for domains

### ISSUE THREAD

**Issue by talhaamir4130** [mailgun/mailgun-php#822]
For example I have users with emails like :

abc@gmail.com
def@gmail.com
ghi@hotmail.com

Each email has event.

I want to search through events, and get all the uses with domain `@gmail.com`.

There should be a functionality to specify search either full or by domain. Thanks.

**Comment by oleksandr-mykhailenko** [comment]
> For example I have users with emails like :
> 
> [abc@gmail.com](mailto:abc@gmail.com) [def@gmail.com](mailto:def@gmail.com) [ghi@hotmail.com](mailto:ghi@hotmail.com)
> 
> Each email has event.
> 
> I want to search through events, and get all the uses with domain `@gmail.com`.
> 
> There should be a functionality to specify search either full or by domain. Thanks.

Hello, thank you. I passed your request to the development department
