### ISSUE TITLE
BatchMessage generates "invalid" JSON for recipients with an empty set of recipient-variables

### ISSUE THREAD

**Issue by dbaeck** [mailgun/mailgun-php#825]
According to mailgun api docs, recipient variables should be sent as a json dictionary with entries of the form `"mail-address":{...}` (https://documentation.mailgun.com/en/latest/user_manual.html#batch-sending-1).

Since a few days, mailgun seems to apply different validation rules on this json dictionary, and no longer allows `"mail-address":[]` for empty entries, which is also valid json and worked until recently. `"mail-adress": {}` is totally fine.

The problem now is, mailgun-php would encody an empty `$variables` array as `[]`. Also, `$batchMessage->setFromAddress(...)` adds an entry to the `recipient-variables`. So setting the sender address without variables (which would normaly be the case), leads directly to invalid `recipient-variables` and an API error (400) on sending.

Maybe `JSON_FORCE_OBJECT` when encoding would fix this problem already.

**Comment by deviarte** [comment]
We are getting the same issue. Impacting many sends!

**Comment by oleksandr-mykhailenko** [comment]
Changes were merged in another PR. Thank you
