### ISSUE TITLE
Undefined index: assignable_to_pools - Ip\IndexResponse

### ISSUE THREAD

**Issue by TWithers** [mailgun/mailgun-php#827]
When using the following code:

`$mg->ips()->domainIndex('my.domain.mg');`

I get the warning:

`PHP Notice:  Undefined index: assignable_to_pools`

It looks like the IPs API is not returning that field in all instances, and probably should be changed to a null coalescing operator inside Mailgun\Model\Ip\IndexResponse on line 45:

`$model->assignableToPools = $data['assignable_to_pools'] ?? [];`

**Comment by oleksandr-mykhailenko** [comment]
Proposed changes were merge in another PR. Thank you
