### ISSUE TITLE
Mailgun API Compatability with Godaddy/PHP 5.4

### ISSUE THREAD

**Issue by NerdsvilleCEO** [mailgun/mailgun-php#83]
I developed a little php script that makes use of the curl API, and allows for multiple attachments, naming of attachments and sending of html/plain text email... it is super basic, however it is useful for anyone who is on Godaddy as it seems they have a block on outgoing SMTP and also their servers seem to operate on PHP 5.4 which doesn't seem to support namespacing as far as I can tell. Here is a link to the project in case you guys are interested in the idea, just thought I would let you guys know! :)

https://github.com/NerdsvilleCEO/NerdsvilleMailgunAPI/blob/master/NerdsvilleMailGun.php

**Comment by nhajiyani** [comment]
On a tangent isn't PHP 5.4 security support ending by Sep 2015, I suppose it might be relevant to look at other versions soon.
http://php.net/supported-versions.php

**Comment by NerdsvilleCEO** [comment]
Yes, however godaddy shared hosting does not allow updating php as far as I am aware, and this was for a customer of mine, again this is for a very specific situation

**Comment by Nyholm** [comment]
Thank you for this info.
