### ISSUE TITLE
Bug: On sending bulk email recipient variable issue

### ISSUE THREAD

**Issue by furqee** [mailgun/mailgun-php#830]
Hye 

I'm getting this error on sending bulk email, with custom html template using dynamic variables, sometimes it shows me this error but sometimes it doesn't throw error using everything same.

`The parameters passed to the API were invalid. Check your inputs! 'recipient-variables' parameter is not a valid JSON`

**Comment by oleksandr-mykhailenko** [comment]
Hello @furqee  This issues was fixed few days ago. Here is PR - https://github.com/mailgun/mailgun-php/pull/829/files
So probably you should update your library

**Comment by oleksandr-mykhailenko** [comment]
@furqee is everything is ok ? We can close the issue ?

**Comment by furqee** [comment]
Yes, @oleksandr-mykhailenko Thanks.
