### ISSUE TITLE
https clic tracking via API

### ISSUE THREAD

**Issue by Francois-Francois** [mailgun/mailgun-php#831]
Support for choosing protocol (http/https) for click tracking.

Currently, there is no way to enable click tracking by choosing HTTPS via the API, nor is there a way to enable the SSL certificate.

These 2 actions are only possible via the dashboard, , which makes automation impossible.

**Comment by oleksandr-mykhailenko** [comment]
@rikless Hello
Please, could you provide more details ? Maybe I can help you. Is it something about UI or you make a specific call tp the API ?

**Comment by oleksandr-mykhailenko** [comment]
So I tried on my sandbox account next request

```
<?php
# Include the Autoloader (see "Libraries" for install instructions)
require 'vendor/autoload.php';
use Mailgun\Mailgun;
# Instantiate the client.

$client = Mailgun::create(
    'xxx',
    'xxx'
);

$domain = 'xxx';
$result = $client->domains()->updateClickTracking($domain, 'yes');

print_r($result);
```

And I got next response 

![image](https://user-images.githubusercontent.com/9269550/180606474-611bb7e4-e15a-43d9-8bf1-b78dfa6cae02.png)


And my setting was enabled

![image](https://user-images.githubusercontent.com/9269550/180606543-a804df2f-108e-4972-8e50-426700d90772.png)

**Comment by rikless** [comment]
I'm actually trying to do this through the API :

![image](https://user-images.githubusercontent.com/2073369/180971423-e49dde29-54e0-4ca6-83c8-07d92cc710a8.png)

**Comment by oleksandr-mykhailenko** [comment]
@rikless I get it, thanks
So I will redirect your message to the next department, who is responsible for defining such features

**Comment by rikless** [comment]
Great thanks !
