### ISSUE TITLE
Templates API

### ISSUE THREAD

**Issue by Radiergummi** [mailgun/mailgun-php#832]
The [templates API](https://documentation.mailgun.com/en/latest/api-templates.html#store-new-template) doesn't seem to be implemented in the SDK, which is a bit unfortunate for my use case. This would be easier if the Mailgun instance exposed a method to perform manual API requests, so we could simply implement the calls ourselves, but there doesn't seem to be a way to get a hold of the HTTP client - thus forcing us to create a separate client with separate credentials to work with message templates.

Are there any plans to add support for the templates API?

**Comment by oleksandr-mykhailenko** [comment]
Hello @Radiergummi this one is on discussion right now. When we have an answer, I will post it here. Your request was passed to the department of development

**Comment by Radiergummi** [comment]
Hi @oleksandr-mykhailenko, got any news on this? If adding full support for the templates API is too much work and doesn't fit on the backlog currently, maybe just exposing the private HTTP client instance (`public function getClient(): HttpClientInterface`) would make our life way easier and allow for customers to implement endpoint support on their own. I could also open a PR for this, if you'd like?

**Comment by oleksandr-mykhailenko** [comment]
Hello @Radiergummi 
I do not have an answer about templates API yet, but about your request for exposing client, sounds good for me. I think, we will implement such feature soon (maybe this week even). So I will let you know about this

**Comment by oleksandr-mykhailenko** [comment]
Hello @Radiergummi 
We added class for working with httpClient if you want to make customized requests. Here is link for usage https://github.com/mailgun/mailgun-php#custom-http-request-to-the-api
