### ISSUE TITLE
Call to a member function getId() on string

### ISSUE THREAD

**Issue by c1am** [mailgun/mailgun-php#838]
When trying to get mailgun events, my API result is grabbed with 

`$curl = curl_init();
					curl_setopt($curl, CURLOPT_URL, $url);
					curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
					curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
					curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
					curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

					$result = curl_exec($curl);
					echo "\n $result";
					$message_id = $result->getId();`

That last line is my attempt at getting the message-id, but I get the "Call to a member function getId() on string" error. Anyone have any insight on this?

When I echo the result, the response has all the correct data, I'm just having trouble selecting certain data.

**Comment by oleksandr-mykhailenko** [comment]
Hello @c1am 
you can't use data as object, because after this line `$result = curl_exec($curl);`
$result is string. you it does not have methods at all, only fields.
so you should use 
```
$responseArray = json_decode($result, true);
```
and you will have an array with data

**Comment by c1am** [comment]
Thank you @oleksandr-mykhailenko! That solved it!

**Comment by jvddrift** [comment]
I get the same error using the Mailgun PHP SDK v.3.5.8, when sending a batchmessage

I use `ArrayHydrator`
```
use Mailgun\HttpClient\HttpClientConfigurator;
use Mailgun\Hydrator\ArrayHydrator;
use Mailgun\Mailgun;

...

$this->mailgun = new Mailgun($configurator, new ArrayHydrator());
```

when running
```
....
$batchMessage->finalize();
```

I get the error
```
Error: Call to a member function getId() on array in file /vendor/mailgun/mailgun-php/src/Message/BatchMessage.php on line 137
```

The batch ís working, mails are sent.
