### ISSUE TITLE
message with the o:tag option: not accepting array value on that case provide Array string

### ISSUE THREAD

**Issue by heysushil** [mailgun/mailgun-php#839]

**Comment by heysushil** [comment]
$params = array(
    'from'    => 'Excited User <YOU@YOUR_DOMAIN_NAME>',
    'to'      => 'bob@example.com',
    'subject' => 'Hello',
    'text'    => 'Testing some Mailgun awesomness!',
    'o:tag'   => array('Tag1', 'Tag2', 'Tag3')
);

In this case in 'o:tag' only accept single value

**Comment by oleksandr-mykhailenko** [comment]
Hello @heysushil and do you have a link to the API doc ? and what type of param it accepts

**Comment by heysushil** [comment]
Yes, I'm using this doc: [MailGun Doc Link](https://documentation.mailgun.com/en/latest/api-sending.html#examples)
and passing these params as per described in doc:

```
# Instantiate the client.
$mgClient = Mailgun::create('PRIVATE_API_KEY', 'https://API_HOSTNAME');
$domain = "YOUR_DOMAIN_NAME";
$params = array(
    'from'    => 'Excited User <YOU@YOUR_DOMAIN_NAME>',
    'to'      => 'bob@example.com',
    'subject' => 'Hello',
    'text'    => 'Testing some Mailgun awesomness!',
    'o:tag'   => array('Tag1', 'Tag2', 'Tag3')
);

# Make the call to the client.
$result = $mgClient->messages()->send($domain, $params);
```

**Comment by oleksandr-mykhailenko** [comment]
Hello @heysushil 
Could you provide your response message, please ?
I tried example from the API docs and everything works well for me.
On Mailgun account I have success message
![image](https://user-images.githubusercontent.com/9269550/189693607-c012e5b9-13e2-414a-acbc-fd159f3520cc.png)

And I have successful response from the API too
![image](https://user-images.githubusercontent.com/9269550/189693720-9618437e-2562-4b73-9d9f-555f29e51a6b.png)

**Comment by heysushil** [comment]
I tried to fetch MailGun mailbox data with a few reference information which I passed on `o:tags` but it was provided `Array` in the case when passing data as index array but when passing single data or data in JSON format it will provide result.

This is the example code that I implemented to fetch the data:

`An example of how to tag a message with the o:tag option:`

# Include the Autoloader (see "Libraries" for install instructions)
require 'vendor/autoload.php';
use Mailgun\Mailgun;

```
# Instantiate the client.
$mgClient = Mailgun::create('PRIVATE_API_KEY', 'https://API_HOSTNAME');
$domain = "YOUR_DOMAIN_NAME";
$params = array(
    'from'    => 'Excited User <YOU@YOUR_DOMAIN_NAME>',
    'to'      => 'bob@example.com',
    'subject' => 'Hello',
    'text'    => 'Testing some Mailgun awesomness!',
    'o:tag'   => array('Tag1', 'Tag2', 'Tag3')
);

# Make the call to the client.
$result = $mgClient->messages()->send($domain, $params);
```

Here I passed variables that hold numeric data something like this:
$id_1 = 1;
$id_2 = 2;
$id_3 = 3;

```
# Instantiate the client.
$mgClient = Mailgun::create('PRIVATE_API_KEY', 'https://API_HOSTNAME');
$domain = "YOUR_DOMAIN_NAME";
$params = array(
    'from'    => 'Excited User <YOU@YOUR_DOMAIN_NAME>',
    'to'      => 'bob@example.com',
    'subject' => 'Hello',
    'text'    => 'Testing some Mailgun awesomness!',
    'o:tag'   => array($id_1, $id_2, $id_3)
);

# Make the call to the client.
$result = $mgClient->messages()->send($domain, $params);
```
This API return all data right only `o:tags`  provide this when pass array:

```
{
      "tags": Array,
      rest data is right
}

**Comment by oleksandr-mykhailenko** [comment]
Hello @heysushil 
Code was fixed and right now it allow to have numeric values. They will be converted to string and it will work
