### ISSUE TITLE
Swift Mailer deprecation

### ISSUE THREAD

**Issue by srdjanmarjanovic** [mailgun/mailgun-php#845]
Some parts of documentation are suggesting to use the [Swift Mailer](https://swiftmailer.symfony.com/docs/introduction.html) which is no longer maintained. Swift Mailer instead suggests using [Symfony Mailer ](https://symfony.com/doc/current/mailer.html). 

1. Are there any plans to move to Symfony Mailer, or anything else for that matter? 
2. Is Symfony Mailer supported in Mailgun PHP SDK out of  the box?
3. Is it enough just to adjust the docs of the SDK?

**Comment by oleksandr-mykhailenko** [comment]
You can use Symfony Mailer. Mailgun support this. In the new version we will give an example of usage. But there is no limitations right now
