### ISSUE TITLE
How to use the HTTP Client for api requests?

### ISSUE THREAD

**Issue by cggit** [mailgun/mailgun-php#848]
When attempting to use the http client for an api request eg. v3/lists:

    $resultGet = $mgClient->httpClient()->httpGet('v3/lists', []);

All I get back is 200 ok header information but no body content like I do with the equivalent curl request.

Can someone shed light on how to use it properly?

**Comment by oleksandr-mykhailenko** [comment]
> When attempting to use the http client for an api request eg. v3/lists:
> 
> ```
> $resultGet = $mgClient->httpClient()->httpGet('v3/lists', []);
> ```
> 
> All I get back is 200 ok header information but no body content like I do with the equivalent curl request.
> 
> Can someone shed light on how to use it properly?

Hello. Please, make sure that you're using API in correct way.
Here is my example

I have next code:
```
$mgClient = Mailgun::create('key-xxxx', 'https://api.mailgun.net/v3/sandboxxxx.mailgun.org');
$domain = "sandbox1zcwer34gdfgfdmailgun.org";


# Make the call to the client.
$res = $mgClient->httpClient()->httpGet(sprintf('/v3/domains/%s', $domain));
print_r($res->getBody()->getContents());
```

So when I run it, I have a results.
Probably you do not have lists or read the answer in wrong way

**Comment by oleksandr-mykhailenko** [comment]
Hello @cggit 
Did you solve your issue ?

**Comment by cggit** [comment]
Yes, thank you. I was missing the $res->getBody()->getContents() part.

I had actually tried $res->getBody() after doing a get_class_method on the response but never thought to do another on getBody.

**Comment by oleksandr-mykhailenko** [comment]
> Yes, thank you @oleksandr-mykhailenko. I was missing the $res->getBody()->getContents() part.
> 
> I had actually tried $res->getBody() after doing a get_class_method on the response but never thought to do another on getBody.
Great

Closing the issue
