### ISSUE TITLE
\stdClass returned instead of an array

### ISSUE THREAD

**Issue by robcaw** [mailgun/mailgun-php#85]
Why is the response a \stdClass and not an associative array?

**Comment by auro1** [comment]
If you need it as an array, (array) $object it?

**Comment by robcaw** [comment]
Because that's not recursive

**Comment by auro1** [comment]
Perhaps this googlefu will help you?  :-)

http://www.if-not-true-then-false.com/2009/php-tip-convert-stdclass-object-to-multidimensional-array-and-convert-multidimensional-array-to-stdclass-object/

**Comment by robcaw** [comment]
I'm not asking how to do it, but wondering why it is done this way.

**Comment by maximevalette** [comment]
:+1:

**Comment by Nyholm** [comment]
There has been no answer in a year. I guess the best we have right now is "I do not know". I hope you do not mind if Im closing this.
