### ISSUE TITLE
Webmozart/path-util is abandoned

### ISSUE THREAD

**Issue by mroeling** [mailgun/mailgun-php#850]
According to the composer installation, the package should not be used anymore.

`Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.`

**Comment by oleksandr-mykhailenko** [comment]
Hello @mroeling 
Thank you, we will investigate and change this

**Comment by oleksandr-mykhailenko** [comment]
So path-util is not used directly in our SDK. During tests I did not find an issue here
