### ISSUE TITLE
error when running composer to update to latest php library - solved

### ISSUE THREAD

**Issue by trstaley** [mailgun/mailgun-php#851]
We have been running MG in our PHP app for many years. We use composer to update our libraries. We current run version 2.4.1 of the MG library. When we modified our composer.json file to use version 3.5.1 of the MG php lib, we get the following error message from composer:

Problem 1
- Conclusion: remove php-http/httplug v1.1.0
- Conclusion: don't install php-http/httplug v1.1.0|keep php-http/httplug v1.1.0
- php-http/curl-client v1.7.1 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.1.0, v1.0.0].
- php-http/curl-client v1.7.1 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.1.0, v1.0.0].
- php-http/curl-client v1.7.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.1.0, v1.0.0].
- Conclusion: don't install php-http/httplug v1.0.0|keep php-http/httplug v1.1.0|install php-http/httplug v1.1.0
- Installation request for php-http/curl-client ^1.7.0 -> satisfiable by php-http/curl-client[v1.7.0, v1.7.1].

The error message is conflicting itself. First it says remove php-http plug, but then it says to keep php-http.httplug V1.1.0

We have attached two files showing our composer.json files, along with images of the output from composer for both versions of the MG library.  It works for 2.4.1 but not for 3.5.1.

Please let us know what we need to do to upgrade to the latest MG php lib, since our attempts to upgrade using composer are failing.

**Comment by trstaley** [comment]
We needed to update to the latest version of the php/http/curl-client.

**Comment by oleksandr-mykhailenko** [comment]
Great, thank you
