### ISSUE TITLE
ShowResponse hardcoded to specific PSR-7 implementation

### ISSUE THREAD

**Issue by bizurkur** [mailgun/mailgun-php#859]
Is there a reason `Mailgun\Model\Message\ShowResponse` is specifically coded to require a `Nyholm\Psr7\Stream` instead of a PSR `StreamInterface`?

It was added not to long ago in this commit: https://github.com/mailgun/mailgun-php/commit/68d33e8bdc2f44626cc355c959e2520032644b78

I'm getting this error: 
```
Mailgun\Model\Message\ShowResponse::setRawStream(): Argument #1 ($rawStream) must be of type ?Nyholm\Psr7\Stream, GuzzleHttp\Psr7\Stream given, called in /var/www/vendor/mailgun/mailgun-php/src/Hydrator/ModelHydrator.php on line 52
```

The entire rest of the library seems to be implementation agnostic (minus the tests).

**Comment by oleksandr-mykhailenko** [comment]
Hello, excuse me for the long answer. So I made a fix and merged already. This is one of the future updates, so we made it on our side. But anyway. Thank you for your work
