### ISSUE TITLE
Fatal error: Class 'Mailgun\Connection\RestClient' not found in /var/www/mysite.xyz/www/inc/libs/Mailgun/Mailgun.php on line 38

### ISSUE THREAD

**Issue by johncave** [mailgun/mailgun-php#87]
I'm getting an error while trying to use this PHP SDK (not installed through Composer, I really prefer managing code dependencies manually so as to minimise them).

To fix the above error I can add the line `require "Connection/RestClient.php";` just above the first class declaration in Mailgun.php, but this in turn causes the error 
```
Fatal error: Class 'GuzzleHttp\Client' not found in /var/www/mysite.xyz/www/inc/libs/Mailgun/Connection/RestClient.php on line 41
``` 
and I imagine if I kept going I'd be caught in a big tangled web of them.

I'm really hoping that this is just a matter of a required PHP module being missing, but my [question on StackOverflow](http://stackoverflow.com/questions/31634163/mailgun-sdk-unable-to-find-required-classes-php) did not get any answers, so I'm posting here.

**Comment by RubenKruiswijk** [comment]
If you choose to install without Composer you'll have to resolve all dependencies yourself. You'll have to look in the composer.json file what dependencies are required and follow the dependencies to see if a dependency depends on another.

That's why composer is so handy :-)

**Comment by johncave** [comment]
Ah, I see now, so this issue is due to missing other packages that Composer would handle for me if I used it, not due to the configuration of my server?

I think I'll just use CURL directly if that's the case, that sounds much more straightforward.

**Comment by RubenKruiswijk** [comment]
Correct. 

Using CURL would work fine too, although you have to implement it yourself, something that this library is built for.

**Comment by johncave** [comment]
Thanks for your timely reply, Ruben :smile:, I'll get onto that tomorrow.

**Comment by jawizie** [comment]
I install with composure but i am having a similar issue

**Comment by Nyholm** [comment]
@jawizie This is a very old issue. Please open a new one if you experiencing problems.
