### ISSUE TITLE
Oudated symfony/http version

### ISSUE THREAD

**Issue by ThomasVeld** [mailgun/mailgun-php#870]
Hi there,

In my composer.json (Laravel project) I was using the http/symfony 6.3 version, although this gave an issue with making Http requests to the Mailgun client.

The following error occured: Undefined constant `CURL_SSLVERSION_TLSv1_2`

This project is using the http/symfony 5.3.0 version in the composer.json file. After changing it to the same version in the Laravel project it worked.

Is there a reason for this outdated http/symfony version?

Thanks!

**Comment by lcottingham** [comment]
+1 on this. This package currently conflicts with Symfony `mercure bundle` being installed due to a conflict with `php-http/discovery <1.15` and `symfony/http-client`. Running 6.3 as above

**Comment by oleksandr-mykhailenko** [comment]
Hello 
Thank you, we will take a look into it and make an update
