### ISSUE TITLE
PHPDoc Type issue in Mailgun\Api\MailingList\Member

### ISSUE THREAD

**Issue by gam04** [mailgun/mailgun-php#873]
The method `createMultiple` in ` Mailgun\Api\MailingList\Member` has the return PHPDoc type as `Mailgun\Model\MailingList\Member\UpdateResponse` but it actually returns `Mailgun\Model\MailingList\UpdateResponse` (due to the `Hydrator`)

**Comment by gam04** [comment]
> The method `createMultiple` in ` Mailgun\Api\MailingList\Member` has the return PHPDoc type as `Mailgun\Model\MailingList\Member\UpdateResponse` but it actually returns `Mailgun\Model\MailingList\UpdateResponse` (due to the `Hydrator`)

Sorry, maybe it's related to the [PR-801](https://github.com/mailgun/mailgun-php/pull/801)

**Comment by oleksandr-mykhailenko** [comment]
Hello
Php doc types were changed a lot since that time. So we are closing issue
