### ISSUE TITLE
TypeError: Mailgun\Api\Suppression\Bounce::show()

### ISSUE THREAD

**Issue by Quarkay** [mailgun/mailgun-php#878]
The code to replicate the issue is as follows:

```php
$mg = Mailgun::create('key-example');
$mg->suppressions()->bounces()->show('domain', $email);
```

The error message is as follows:

```
TypeError: Mailgun\Api\Suppression\Bounce::show(): 
Return value must be of type ?Mailgun\Model\Suppression\Bounce\ShowResponse, Mailgun\Model\Suppression\Bounce\Bounce returned
```

The reason for this issue is:

1. The `create()` method provided by the class `Mailgun\Model\Suppression\Bounce\Bounce` uses `new self()` during instantiation and use `self` as return type.
2. Class `Mailgun\Model\Suppression\Bounce\ShowResponse` extended `Mailgun\Model\Suppression\Bounce\ShowResponse`，if we call `ShowResponse::create()` the actual return type will be `Mailgun\Model\Suppression\Bounce\Bounce`.
3. In [this commit](https://github.com/mailgun/mailgun-php/commit/38d5ecca8d359de9b4e50125d6801d76a07571ab), native php type restrictions were added for the `show()` method. This change exposed the issue.

**Comment by oleksandr-mykhailenko** [comment]
This one is fixed already. Thank you
