### ISSUE TITLE
Errors after latest update regarding json syntax

### ISSUE THREAD

**Issue by cswiers** [mailgun/mailgun-php#884]
See my comment in the commit:
https://github.com/mailgun/mailgun-php/commit/888d70f20c93278ea525c448d88a9f114b5649ae#r133802506

Hope this is helpful to you.

With kind regards,
@cswiers

**Comment by oleksandr-mykhailenko** [comment]
Hello @cswiers 
we released a new version with better error handling flow

**Comment by cswiers** [comment]
Thanks!
