### ISSUE TITLE
Endpoint not correct for Tag > stats()

### ISSUE THREAD

**Issue by achilleus68** [mailgun/mailgun-php#899]
Hi,

I am trying to get the stats for a tag.

In Mailgun\Api\Tag -> stats(), line 102 the endpoint is formatted as follows
```
$response = $this->httpGet(sprintf('/v3/%s/tags/%s/stats', $domain, $tag), $params);
```

however using this function generates an error `The endpoint you have tried to access does not exist. Check if the domain matches the domain you have configure on Mailgun.` 

E.g. the `show()` function in Mailgun\Api\Tag works fine

I don't see an endpoint in this format in the documentation on `Get stats by tag` https://documentation.mailgun.com/docs/mailgun/api-reference/openapi-final/tag/Tags/#tag/Tags/operation/api.InitTagsAPIController.checkErr.func7-8

What is the correct way to get the stats for a tag?

**Comment by oleksandr-mykhailenko** [comment]
Hello @achilleus68 
The library was update and you can use correct methods right now
