### ISSUE TITLE
Feature Request: Add dkim_host_name and dkim_selector options to domains()->create() method

### ISSUE THREAD

**Issue by creamailer-ape** [mailgun/mailgun-php#907]
Hello Mailgun PHP client team,

First off, thank you for your hard work on the Mailgun PHP client. It's been incredibly useful.

I noticed that the `domains()->create()` method includes many configurable options, which is great. However, it appears that the options `dkim_host_name` and `dkim_selector` are not currently supported. These options are available in the Mailgun API as documented here: [Mailgun API Reference - Create Domain](https://documentation.mailgun.com/docs/mailgun/api-reference/openapi-final/tag/Domains/#tag/Domains/operation/httpapi.(*T).CreateDomain-fm-6).

Could you please let me know if there are any plans to include these options in an upcoming release? Adding these would greatly enhance the functionality for users needing detailed DKIM configurations directly via the PHP client.

Thank you for considering this enhancement.

Best regards,

Arto

**Comment by oleksandr-mykhailenko** [comment]
Hello @creamailer-ape 
We've added those params into the method

Thank you and have a nice day

**Comment by creamailer-ape** [comment]
Awesome! Thank you.
