### ISSUE TITLE
The template search filters do not match the documentation.

### ISSUE THREAD

**Issue by carloslabrador** [mailgun/mailgun-php#908]
Hello Mailgun PHP client team,

In the template filters, the 'skip' parameter is used, which in the documentation is referred to as 'page'.

Documentation: https://documentation.mailgun.com/docs/mailgun/api-reference/openapi-final/tag/Templates/#tag/Templates/operation/httpapi.(*TemplateAPIControler).GetPage-fm-9!in=query&path=page&t=request
Code Line: https://github.com/mailgun/mailgun-php/blob/4329fc6065adbb1e73792e0f6223c03200b8bc6e/src/Api/Templates.php#L50C8-L50C20

Thanks.

**Comment by oleksandr-mykhailenko** [comment]
Thank you, we updated this in the new version
