### ISSUE TITLE
php mailgun not work with php version 8.3

### ISSUE THREAD

**Issue by citadelind2** [mailgun/mailgun-php#910]
we try to run mailgun-php sdk in php 8.3  my linux server  got below error 

Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Symfony\Component\OptionsResolver\OptionsResolver: :offsetExists($option) should either be compatible with ArrayAccess: :offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange
] attribute should be used to temporarily suppress the notice in /var/www/html/lib/mailgun/vendor/symfony/options-resolver/OptionsResolver.php: 1160

**Comment by oleksandr-mykhailenko** [comment]
Hello @citadelind2 
Looks like this component does not support 8.3 yet. Probably, you should install manually this one - https://symfony.com/doc/current/components/options_resolver.html
