### ISSUE TITLE
Webhook IndexResponse missing "accepted"?

### ISSUE THREAD

**Issue by njt1982** [mailgun/mailgun-php#915]
https://github.com/mailgun/mailgun-php/blob/9b6391df672a73c6cdf1e1bc60014a337ca60ccf/src/Model/Webhook/IndexResponse.php#L54-L60

Shouldn't `accepted` be in this API list?
https://documentation.mailgun.com/docs/mailgun/api-reference/openapi-final/tag/Webhooks/#tag/Webhooks/operation/httpapi.(*T).GetAllDomainWebhooks-fm-25

**Comment by oleksandr-mykhailenko** [comment]
> https://github.com/mailgun/mailgun-php/blob/9b6391df672a73c6cdf1e1bc60014a337ca60ccf/src/Model/Webhook/IndexResponse.php#L54-L60
> 
> Shouldn't `accepted` be in this API list? https://documentation.mailgun.com/docs/mailgun/api-reference/openapi-final/tag/Webhooks/#tag/Webhooks/operation/httpapi.(*T).GetAllDomainWebhooks-fm-25

Hello @njt1982 
Thank you, we will update this soon

**Comment by oleksandr-mykhailenko** [comment]
Hello
This one was fixed
Thank you
