### ISSUE TITLE
The parameters passed to the API were invalid. Check your inputs

### ISSUE THREAD

**Issue by vinita90** [mailgun/mailgun-php#92]
$mg = new Mailgun('key-');
		$domain = "domain.com";
		$file="test";
		try
                {
		$mg->sendMessage($domain,array(
                                'from'=> 'support@domain.com', 
                                'to'      =>'id@domain.com', 
                                'subject' => $subject, 
                                'html'    => '$body';
                                                ));
                }
                catch(Exception $e) {
	    echo '{"error":{"text":'. $e->getMessage() .'}}'; 
	}

and i am not able to findout the error.

**Comment by aJamDonut** [comment]
'html' => '$body';
to
'html' => $body;

**Comment by anshu300** [comment]
Read this 
https://help.mailgun.com/hc/en-us/articles/217531258-Authorized-Recipients
