### ISSUE TITLE
Follow semver

### ISSUE THREAD

**Issue by ProPheT777** [mailgun/mailgun-php#95]
Hey, 

Please is it possible to follow semver, because go from 1.7 to 1.8 is not possible since you bump php version, so application under 5.3 doesn't not work after the update via ~1.7. It's problematic because minor patch must work.

Take care ;)

Cheers

**Comment by Nyholm** [comment]
Hey. 
Bumping PHP version is allowed even in patch versions according to Semver. We are not breaking the public API by updating our dependencies. Also, composer will not install the new 1.8 version if you do not have the required PHP version. So nothing will break in your system running PHP 5.3 when you do `composer update`. You will simply not get the latest version... 

Also, you should consider updating your system to a supported PHP version.
