### ISSUE TITLE
Small refactor to verifyWebhookSignature() method

### ISSUE THREAD

**Issue by BentCoder** [mailgun/mailgun-php#96]
Hi,

I think you should refactor https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Mailgun.php#L85 method to handle incoming data better otherwise in some cases it causes `500 Internal Server` error. I know it can be done before calling the method but it is good to handle it in your code as well.

Regards

**CURRENT**
```
function verifyWebhookSignature($postData = NULL) {
	return is_null($postData) ? 'NULL' : 'Not NULL';
}
foreach (['', null, [], [1, 2]] as $postDate) {
	echo verifyWebhookSignature($postDate)."<br />";
}
```
**Result**
```
Not NULL
NULL
Not NULL
Not NULL
```

**PROPOSED**
```
function verifyWebhookSignature($postData = NULL) {
	return !$postData ? 'NULL' : 'Not NULL';
}

foreach (['', null, [], [1, 2]] as $postDate) {
	echo verifyWebhookSignature($postDate)."<br />";
}
```
**Result**
```
NULL
NULL
NULL
Not NULL
```

**Comment by Nyholm** [comment]
Could you provide a PR with such refactoring?

**Comment by Nyholm** [comment]
Im going to close this issue because of inactivity. Feel free to open a PR with this. That would be appreciated.
