### ISSUE TITLE
Please review and include my mailgun cakephp plugin link in your readme, framework integration section

### ISSUE THREAD

**Issue by motsmanish** [mailgun/mailgun-php#99]
Please review and include my mailgun cakephp plugin link in your readme, framework integration section, let me know if any issues. Will be adding tests cases soon.
https://github.com/motsmanish/cakephp-mailgun

**Comment by Nyholm** [comment]
Nice work. But this cakephp integration has barley 200 downloads. Please come back when your library is **the** library for cackephp mailgun integration.
